apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: cognitouserpools.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: CognitoUserPool
    listKind: CognitoUserPoolList
    plural: cognitouserpools
    singular: cognitouserpool
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            adminCreateUserConfig:
              items:
                properties:
                  allowAdminCreateUserOnly:
                    type: boolean
                  inviteMessageTemplate:
                    items:
                      properties:
                        emailMessage:
                          type: string
                        emailSubject:
                          type: string
                        smsMessage:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  unusedAccountValidityDays:
                    format: int64
                    type: integer
                type: object
              maxItems: 1
              type: array
            aliasAttributes:
              items:
                type: string
              type: array
            arn:
              type: string
            autoVerifiedAttributes:
              items:
                type: string
              type: array
            creationDate:
              type: string
            deviceConfiguration:
              items:
                properties:
                  challengeRequiredOnNewDevice:
                    type: boolean
                  deviceOnlyRememberedOnUserPrompt:
                    type: boolean
                type: object
              maxItems: 1
              type: array
            emailConfiguration:
              items:
                properties:
                  replyToEmailAddress:
                    type: string
                  sourceArn:
                    type: string
                type: object
              maxItems: 1
              type: array
            emailVerificationMessage:
              type: string
            emailVerificationSubject:
              type: string
            endpoint:
              type: string
            id:
              type: string
            lambdaConfig:
              items:
                properties:
                  createAuthChallenge:
                    type: string
                  customMessage:
                    type: string
                  defineAuthChallenge:
                    type: string
                  postAuthentication:
                    type: string
                  postConfirmation:
                    type: string
                  preAuthentication:
                    type: string
                  preSignUp:
                    type: string
                  preTokenGeneration:
                    type: string
                  userMigration:
                    type: string
                  verifyAuthChallengeResponse:
                    type: string
                type: object
              maxItems: 1
              type: array
            lastModifiedDate:
              type: string
            mfaConfiguration:
              type: string
            name:
              type: string
            passwordPolicy:
              items:
                properties:
                  minimumLength:
                    format: int64
                    type: integer
                  requireLowercase:
                    type: boolean
                  requireNumbers:
                    type: boolean
                  requireSymbols:
                    type: boolean
                  requireUppercase:
                    type: boolean
                type: object
              maxItems: 1
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            schema:
              items:
                properties:
                  attributeDataType:
                    type: string
                  developerOnlyAttribute:
                    type: boolean
                  mutable:
                    type: boolean
                  name:
                    type: string
                  numberAttributeConstraints:
                    items:
                      properties:
                        maxValue:
                          type: string
                        minValue:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  required:
                    type: boolean
                  stringAttributeConstraints:
                    items:
                      properties:
                        maxLength:
                          type: string
                        minLength:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                required:
                - attributeDataType
                - name
                type: object
              maxItems: 50
              minItems: 1
              type: array
            smsAuthenticationMessage:
              type: string
            smsConfiguration:
              items:
                properties:
                  externalID:
                    type: string
                  snsCallerArn:
                    type: string
                required:
                - externalID
                - snsCallerArn
                type: object
              maxItems: 1
              type: array
            smsVerificationMessage:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            userPoolAddOns:
              items:
                properties:
                  advancedSecurityMode:
                    type: string
                required:
                - advancedSecurityMode
                type: object
              maxItems: 1
              type: array
            usernameAttributes:
              items:
                type: string
              type: array
            verificationMessageTemplate:
              items:
                properties:
                  defaultEmailOption:
                    type: string
                  emailMessage:
                    type: string
                  emailMessageByLink:
                    type: string
                  emailSubject:
                    type: string
                  emailSubjectByLink:
                    type: string
                  smsMessage:
                    type: string
                type: object
              maxItems: 1
              type: array
          required:
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                adminCreateUserConfig:
                  items:
                    properties:
                      allowAdminCreateUserOnly:
                        type: boolean
                      inviteMessageTemplate:
                        items:
                          properties:
                            emailMessage:
                              type: string
                            emailSubject:
                              type: string
                            smsMessage:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      unusedAccountValidityDays:
                        format: int64
                        type: integer
                    type: object
                  maxItems: 1
                  type: array
                aliasAttributes:
                  items:
                    type: string
                  type: array
                arn:
                  type: string
                autoVerifiedAttributes:
                  items:
                    type: string
                  type: array
                creationDate:
                  type: string
                deviceConfiguration:
                  items:
                    properties:
                      challengeRequiredOnNewDevice:
                        type: boolean
                      deviceOnlyRememberedOnUserPrompt:
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
                emailConfiguration:
                  items:
                    properties:
                      replyToEmailAddress:
                        type: string
                      sourceArn:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                emailVerificationMessage:
                  type: string
                emailVerificationSubject:
                  type: string
                endpoint:
                  type: string
                id:
                  type: string
                lambdaConfig:
                  items:
                    properties:
                      createAuthChallenge:
                        type: string
                      customMessage:
                        type: string
                      defineAuthChallenge:
                        type: string
                      postAuthentication:
                        type: string
                      postConfirmation:
                        type: string
                      preAuthentication:
                        type: string
                      preSignUp:
                        type: string
                      preTokenGeneration:
                        type: string
                      userMigration:
                        type: string
                      verifyAuthChallengeResponse:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                lastModifiedDate:
                  type: string
                mfaConfiguration:
                  type: string
                name:
                  type: string
                passwordPolicy:
                  items:
                    properties:
                      minimumLength:
                        format: int64
                        type: integer
                      requireLowercase:
                        type: boolean
                      requireNumbers:
                        type: boolean
                      requireSymbols:
                        type: boolean
                      requireUppercase:
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                schema:
                  items:
                    properties:
                      attributeDataType:
                        type: string
                      developerOnlyAttribute:
                        type: boolean
                      mutable:
                        type: boolean
                      name:
                        type: string
                      numberAttributeConstraints:
                        items:
                          properties:
                            maxValue:
                              type: string
                            minValue:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      required:
                        type: boolean
                      stringAttributeConstraints:
                        items:
                          properties:
                            maxLength:
                              type: string
                            minLength:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                    required:
                    - attributeDataType
                    - name
                    type: object
                  maxItems: 50
                  minItems: 1
                  type: array
                smsAuthenticationMessage:
                  type: string
                smsConfiguration:
                  items:
                    properties:
                      externalID:
                        type: string
                      snsCallerArn:
                        type: string
                    required:
                    - externalID
                    - snsCallerArn
                    type: object
                  maxItems: 1
                  type: array
                smsVerificationMessage:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                userPoolAddOns:
                  items:
                    properties:
                      advancedSecurityMode:
                        type: string
                    required:
                    - advancedSecurityMode
                    type: object
                  maxItems: 1
                  type: array
                usernameAttributes:
                  items:
                    type: string
                  type: array
                verificationMessageTemplate:
                  items:
                    properties:
                      defaultEmailOption:
                        type: string
                      emailMessage:
                        type: string
                      emailMessageByLink:
                        type: string
                      emailSubject:
                        type: string
                      emailSubjectByLink:
                        type: string
                      smsMessage:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
              required:
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
