apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: albtargetgroups.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: AlbTargetGroup
    listKind: AlbTargetGroupList
    plural: albtargetgroups
    singular: albtargetgroup
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            arn:
              type: string
            arnSuffix:
              type: string
            deregistrationDelay:
              format: int64
              type: integer
            healthCheck:
              items:
                properties:
                  enabled:
                    type: boolean
                  healthyThreshold:
                    format: int64
                    type: integer
                  interval:
                    format: int64
                    type: integer
                  matcher:
                    type: string
                  path:
                    type: string
                  port:
                    type: string
                  protocol:
                    type: string
                  timeout:
                    format: int64
                    type: integer
                  unhealthyThreshold:
                    format: int64
                    type: integer
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            lambdaMultiValueHeadersEnabled:
              type: boolean
            name:
              type: string
            namePrefix:
              type: string
            port:
              format: int64
              type: integer
            protocol:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            proxyProtocolV2:
              type: boolean
            slowStart:
              format: int64
              type: integer
            stickiness:
              items:
                properties:
                  cookieDuration:
                    format: int64
                    type: integer
                  enabled:
                    type: boolean
                  type:
                    type: string
                required:
                - type
                type: object
              maxItems: 1
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
            targetType:
              type: string
            vpcID:
              type: string
          required:
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                arn:
                  type: string
                arnSuffix:
                  type: string
                deregistrationDelay:
                  format: int64
                  type: integer
                healthCheck:
                  items:
                    properties:
                      enabled:
                        type: boolean
                      healthyThreshold:
                        format: int64
                        type: integer
                      interval:
                        format: int64
                        type: integer
                      matcher:
                        type: string
                      path:
                        type: string
                      port:
                        type: string
                      protocol:
                        type: string
                      timeout:
                        format: int64
                        type: integer
                      unhealthyThreshold:
                        format: int64
                        type: integer
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                lambdaMultiValueHeadersEnabled:
                  type: boolean
                name:
                  type: string
                namePrefix:
                  type: string
                port:
                  format: int64
                  type: integer
                protocol:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                proxyProtocolV2:
                  type: boolean
                slowStart:
                  format: int64
                  type: integer
                stickiness:
                  items:
                    properties:
                      cookieDuration:
                        format: int64
                        type: integer
                      enabled:
                        type: boolean
                      type:
                        type: string
                    required:
                    - type
                    type: object
                  maxItems: 1
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
                targetType:
                  type: string
                vpcID:
                  type: string
              required:
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
