apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: route53healthchecks.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: Route53HealthCheck
    listKind: Route53HealthCheckList
    plural: route53healthchecks
    singular: route53healthcheck
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            childHealthThreshold:
              format: int64
              type: integer
            childHealthchecks:
              items:
                type: string
              type: array
            cloudwatchAlarmName:
              type: string
            cloudwatchAlarmRegion:
              type: string
            enableSni:
              type: boolean
            failureThreshold:
              format: int64
              type: integer
            fqdn:
              type: string
            id:
              type: string
            insufficientDataHealthStatus:
              type: string
            invertHealthcheck:
              type: boolean
            ipAddress:
              type: string
            measureLatency:
              type: boolean
            port:
              format: int64
              type: integer
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            referenceName:
              type: string
            regions:
              items:
                type: string
              type: array
            requestInterval:
              format: int64
              type: integer
            resourcePath:
              type: string
            searchString:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            type:
              type: string
          required:
          - providerRef
          - type
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                childHealthThreshold:
                  format: int64
                  type: integer
                childHealthchecks:
                  items:
                    type: string
                  type: array
                cloudwatchAlarmName:
                  type: string
                cloudwatchAlarmRegion:
                  type: string
                enableSni:
                  type: boolean
                failureThreshold:
                  format: int64
                  type: integer
                fqdn:
                  type: string
                id:
                  type: string
                insufficientDataHealthStatus:
                  type: string
                invertHealthcheck:
                  type: boolean
                ipAddress:
                  type: string
                measureLatency:
                  type: boolean
                port:
                  format: int64
                  type: integer
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                referenceName:
                  type: string
                regions:
                  items:
                    type: string
                  type: array
                requestInterval:
                  format: int64
                  type: integer
                resourcePath:
                  type: string
                searchString:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                type:
                  type: string
              required:
              - providerRef
              - type
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
