apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: vpcendpoints.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: VpcEndpoint
    listKind: VpcEndpointList
    plural: vpcendpoints
    singular: vpcendpoint
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            autoAccept:
              type: boolean
            cidrBlocks:
              items:
                type: string
              type: array
            dnsEntry:
              items:
                properties:
                  dnsName:
                    type: string
                  hostedZoneID:
                    type: string
                type: object
              type: array
            id:
              type: string
            networkInterfaceIDS:
              items:
                type: string
              type: array
            ownerID:
              type: string
            policy:
              type: string
            prefixListID:
              type: string
            privateDNSEnabled:
              type: boolean
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            requesterManaged:
              type: boolean
            routeTableIDS:
              items:
                type: string
              type: array
            securityGroupIDS:
              items:
                type: string
              type: array
            serviceName:
              type: string
            state:
              type: string
            subnetIDS:
              items:
                type: string
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
            vpcEndpointType:
              type: string
            vpcID:
              type: string
          required:
          - providerRef
          - serviceName
          - vpcID
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                autoAccept:
                  type: boolean
                cidrBlocks:
                  items:
                    type: string
                  type: array
                dnsEntry:
                  items:
                    properties:
                      dnsName:
                        type: string
                      hostedZoneID:
                        type: string
                    type: object
                  type: array
                id:
                  type: string
                networkInterfaceIDS:
                  items:
                    type: string
                  type: array
                ownerID:
                  type: string
                policy:
                  type: string
                prefixListID:
                  type: string
                privateDNSEnabled:
                  type: boolean
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                requesterManaged:
                  type: boolean
                routeTableIDS:
                  items:
                    type: string
                  type: array
                securityGroupIDS:
                  items:
                    type: string
                  type: array
                serviceName:
                  type: string
                state:
                  type: string
                subnetIDS:
                  items:
                    type: string
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
                vpcEndpointType:
                  type: string
                vpcID:
                  type: string
              required:
              - providerRef
              - serviceName
              - vpcID
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
