apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: gameliftfleet.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: GameliftFleet
    listKind: GameliftFleetList
    plural: gameliftfleet
    singular: gameliftfleet
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            arn:
              type: string
            buildID:
              type: string
            description:
              type: string
            ec2InboundPermission:
              items:
                properties:
                  fromPort:
                    format: int64
                    type: integer
                  ipRange:
                    type: string
                  protocol:
                    type: string
                  toPort:
                    format: int64
                    type: integer
                required:
                - fromPort
                - ipRange
                - protocol
                - toPort
                type: object
              maxItems: 50
              type: array
            ec2InstanceType:
              type: string
            id:
              type: string
            logPaths:
              items:
                type: string
              type: array
            metricGroups:
              items:
                type: string
              type: array
            name:
              type: string
            newGameSessionProtectionPolicy:
              type: string
            operatingSystem:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            resourceCreationLimitPolicy:
              items:
                properties:
                  newGameSessionsPerCreator:
                    format: int64
                    type: integer
                  policyPeriodInMinutes:
                    format: int64
                    type: integer
                type: object
              maxItems: 1
              type: array
            runtimeConfiguration:
              items:
                properties:
                  gameSessionActivationTimeoutSeconds:
                    format: int64
                    type: integer
                  maxConcurrentGameSessionActivations:
                    format: int64
                    type: integer
                  serverProcess:
                    items:
                      properties:
                        concurrentExecutions:
                          format: int64
                          type: integer
                        launchPath:
                          type: string
                        parameters:
                          type: string
                      required:
                      - concurrentExecutions
                      - launchPath
                      type: object
                    maxItems: 50
                    type: array
                type: object
              maxItems: 1
              type: array
          required:
          - buildID
          - ec2InstanceType
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                arn:
                  type: string
                buildID:
                  type: string
                description:
                  type: string
                ec2InboundPermission:
                  items:
                    properties:
                      fromPort:
                        format: int64
                        type: integer
                      ipRange:
                        type: string
                      protocol:
                        type: string
                      toPort:
                        format: int64
                        type: integer
                    required:
                    - fromPort
                    - ipRange
                    - protocol
                    - toPort
                    type: object
                  maxItems: 50
                  type: array
                ec2InstanceType:
                  type: string
                id:
                  type: string
                logPaths:
                  items:
                    type: string
                  type: array
                metricGroups:
                  items:
                    type: string
                  type: array
                name:
                  type: string
                newGameSessionProtectionPolicy:
                  type: string
                operatingSystem:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                resourceCreationLimitPolicy:
                  items:
                    properties:
                      newGameSessionsPerCreator:
                        format: int64
                        type: integer
                      policyPeriodInMinutes:
                        format: int64
                        type: integer
                    type: object
                  maxItems: 1
                  type: array
                runtimeConfiguration:
                  items:
                    properties:
                      gameSessionActivationTimeoutSeconds:
                        format: int64
                        type: integer
                      maxConcurrentGameSessionActivations:
                        format: int64
                        type: integer
                      serverProcess:
                        items:
                          properties:
                            concurrentExecutions:
                              format: int64
                              type: integer
                            launchPath:
                              type: string
                            parameters:
                              type: string
                          required:
                          - concurrentExecutions
                          - launchPath
                          type: object
                        maxItems: 50
                        type: array
                    type: object
                  maxItems: 1
                  type: array
              required:
              - buildID
              - ec2InstanceType
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
