apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: opsworksinstances.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: OpsworksInstance
    listKind: OpsworksInstanceList
    plural: opsworksinstances
    singular: opsworksinstance
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            agentVersion:
              type: string
            amiID:
              type: string
            architecture:
              type: string
            autoScalingType:
              type: string
            availabilityZone:
              type: string
            createdAt:
              type: string
            deleteEbs:
              type: boolean
            deleteEip:
              type: boolean
            ebsBlockDevice:
              items:
                properties:
                  deleteOnTermination:
                    type: boolean
                  deviceName:
                    type: string
                  iops:
                    format: int64
                    type: integer
                  snapshotID:
                    type: string
                  volumeSize:
                    format: int64
                    type: integer
                  volumeType:
                    type: string
                required:
                - deviceName
                type: object
              type: array
            ebsOptimized:
              type: boolean
            ec2InstanceID:
              type: string
            ecsClusterArn:
              type: string
            elasticIP:
              type: string
            ephemeralBlockDevice:
              items:
                properties:
                  deviceName:
                    type: string
                  virtualName:
                    type: string
                required:
                - deviceName
                - virtualName
                type: object
              type: array
            hostname:
              type: string
            id:
              type: string
            infrastructureClass:
              type: string
            installUpdatesOnBoot:
              type: boolean
            instanceProfileArn:
              type: string
            instanceType:
              type: string
            lastServiceErrorID:
              type: string
            layerIDS:
              items:
                type: string
              type: array
            os:
              type: string
            platform:
              type: string
            privateDNS:
              type: string
            privateIP:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            publicDNS:
              type: string
            publicIP:
              type: string
            registeredBy:
              type: string
            reportedAgentVersion:
              type: string
            reportedOsFamily:
              type: string
            reportedOsName:
              type: string
            reportedOsVersion:
              type: string
            rootBlockDevice:
              items:
                properties:
                  deleteOnTermination:
                    type: boolean
                  iops:
                    format: int64
                    type: integer
                  volumeSize:
                    format: int64
                    type: integer
                  volumeType:
                    type: string
                type: object
              type: array
            rootDeviceType:
              type: string
            rootDeviceVolumeID:
              type: string
            securityGroupIDS:
              items:
                type: string
              type: array
            sshHostDsaKeyFingerprint:
              type: string
            sshHostRsaKeyFingerprint:
              type: string
            sshKeyName:
              type: string
            stackID:
              type: string
            state:
              type: string
            status:
              type: string
            subnetID:
              type: string
            tenancy:
              type: string
            virtualizationType:
              type: string
          required:
          - layerIDS
          - providerRef
          - stackID
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                agentVersion:
                  type: string
                amiID:
                  type: string
                architecture:
                  type: string
                autoScalingType:
                  type: string
                availabilityZone:
                  type: string
                createdAt:
                  type: string
                deleteEbs:
                  type: boolean
                deleteEip:
                  type: boolean
                ebsBlockDevice:
                  items:
                    properties:
                      deleteOnTermination:
                        type: boolean
                      deviceName:
                        type: string
                      iops:
                        format: int64
                        type: integer
                      snapshotID:
                        type: string
                      volumeSize:
                        format: int64
                        type: integer
                      volumeType:
                        type: string
                    required:
                    - deviceName
                    type: object
                  type: array
                ebsOptimized:
                  type: boolean
                ec2InstanceID:
                  type: string
                ecsClusterArn:
                  type: string
                elasticIP:
                  type: string
                ephemeralBlockDevice:
                  items:
                    properties:
                      deviceName:
                        type: string
                      virtualName:
                        type: string
                    required:
                    - deviceName
                    - virtualName
                    type: object
                  type: array
                hostname:
                  type: string
                id:
                  type: string
                infrastructureClass:
                  type: string
                installUpdatesOnBoot:
                  type: boolean
                instanceProfileArn:
                  type: string
                instanceType:
                  type: string
                lastServiceErrorID:
                  type: string
                layerIDS:
                  items:
                    type: string
                  type: array
                os:
                  type: string
                platform:
                  type: string
                privateDNS:
                  type: string
                privateIP:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                publicDNS:
                  type: string
                publicIP:
                  type: string
                registeredBy:
                  type: string
                reportedAgentVersion:
                  type: string
                reportedOsFamily:
                  type: string
                reportedOsName:
                  type: string
                reportedOsVersion:
                  type: string
                rootBlockDevice:
                  items:
                    properties:
                      deleteOnTermination:
                        type: boolean
                      iops:
                        format: int64
                        type: integer
                      volumeSize:
                        format: int64
                        type: integer
                      volumeType:
                        type: string
                    type: object
                  type: array
                rootDeviceType:
                  type: string
                rootDeviceVolumeID:
                  type: string
                securityGroupIDS:
                  items:
                    type: string
                  type: array
                sshHostDsaKeyFingerprint:
                  type: string
                sshHostRsaKeyFingerprint:
                  type: string
                sshKeyName:
                  type: string
                stackID:
                  type: string
                state:
                  type: string
                status:
                  type: string
                subnetID:
                  type: string
                tenancy:
                  type: string
                virtualizationType:
                  type: string
              required:
              - layerIDS
              - providerRef
              - stackID
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
