apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: dlmlifecyclepolicies.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: DlmLifecyclePolicy
    listKind: DlmLifecyclePolicyList
    plural: dlmlifecyclepolicies
    singular: dlmlifecyclepolicy
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              type: string
            executionRoleArn:
              type: string
            id:
              type: string
            policyDetails:
              items:
                properties:
                  resourceTypes:
                    items:
                      type: string
                    type: array
                  schedule:
                    items:
                      properties:
                        copyTags:
                          type: boolean
                        createRule:
                          items:
                            properties:
                              interval:
                                format: int64
                                type: integer
                              intervalUnit:
                                type: string
                              times:
                                items:
                                  type: string
                                maxItems: 1
                                type: array
                            required:
                            - interval
                            type: object
                          maxItems: 1
                          type: array
                        name:
                          type: string
                        retainRule:
                          items:
                            properties:
                              count:
                                format: int64
                                type: integer
                            required:
                            - count
                            type: object
                          maxItems: 1
                          type: array
                        tagsToAdd:
                          additionalProperties:
                            type: string
                          type: object
                      required:
                      - createRule
                      - name
                      - retainRule
                      type: object
                    type: array
                  targetTags:
                    additionalProperties:
                      type: string
                    type: object
                required:
                - resourceTypes
                - schedule
                - targetTags
                type: object
              maxItems: 1
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            state:
              type: string
          required:
          - description
          - executionRoleArn
          - policyDetails
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                description:
                  type: string
                executionRoleArn:
                  type: string
                id:
                  type: string
                policyDetails:
                  items:
                    properties:
                      resourceTypes:
                        items:
                          type: string
                        type: array
                      schedule:
                        items:
                          properties:
                            copyTags:
                              type: boolean
                            createRule:
                              items:
                                properties:
                                  interval:
                                    format: int64
                                    type: integer
                                  intervalUnit:
                                    type: string
                                  times:
                                    items:
                                      type: string
                                    maxItems: 1
                                    type: array
                                required:
                                - interval
                                type: object
                              maxItems: 1
                              type: array
                            name:
                              type: string
                            retainRule:
                              items:
                                properties:
                                  count:
                                    format: int64
                                    type: integer
                                required:
                                - count
                                type: object
                              maxItems: 1
                              type: array
                            tagsToAdd:
                              additionalProperties:
                                type: string
                              type: object
                          required:
                          - createRule
                          - name
                          - retainRule
                          type: object
                        type: array
                      targetTags:
                        additionalProperties:
                          type: string
                        type: object
                    required:
                    - resourceTypes
                    - schedule
                    - targetTags
                    type: object
                  maxItems: 1
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                state:
                  type: string
              required:
              - description
              - executionRoleArn
              - policyDetails
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
