apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: directoryservicedirectories.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: DirectoryServiceDirectory
    listKind: DirectoryServiceDirectoryList
    plural: directoryservicedirectories
    singular: directoryservicedirectory
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            accessURL:
              type: string
            alias:
              type: string
            connectSettings:
              items:
                properties:
                  customerDNSIPS:
                    items:
                      type: string
                    type: array
                  customerUsername:
                    type: string
                  subnetIDS:
                    items:
                      type: string
                    type: array
                  vpcID:
                    type: string
                required:
                - customerDNSIPS
                - customerUsername
                - subnetIDS
                - vpcID
                type: object
              maxItems: 1
              type: array
            description:
              type: string
            dnsIPAddresses:
              items:
                type: string
              type: array
            edition:
              type: string
            enableSso:
              type: boolean
            id:
              type: string
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            securityGroupID:
              type: string
            shortName:
              type: string
            size:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            type:
              type: string
            vpcSettings:
              items:
                properties:
                  subnetIDS:
                    items:
                      type: string
                    type: array
                  vpcID:
                    type: string
                required:
                - subnetIDS
                - vpcID
                type: object
              maxItems: 1
              type: array
          required:
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                accessURL:
                  type: string
                alias:
                  type: string
                connectSettings:
                  items:
                    properties:
                      customerDNSIPS:
                        items:
                          type: string
                        type: array
                      customerUsername:
                        type: string
                      subnetIDS:
                        items:
                          type: string
                        type: array
                      vpcID:
                        type: string
                    required:
                    - customerDNSIPS
                    - customerUsername
                    - subnetIDS
                    - vpcID
                    type: object
                  maxItems: 1
                  type: array
                description:
                  type: string
                dnsIPAddresses:
                  items:
                    type: string
                  type: array
                edition:
                  type: string
                enableSso:
                  type: boolean
                id:
                  type: string
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                securityGroupID:
                  type: string
                shortName:
                  type: string
                size:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                type:
                  type: string
                vpcSettings:
                  items:
                    properties:
                      subnetIDS:
                        items:
                          type: string
                        type: array
                      vpcID:
                        type: string
                    required:
                    - subnetIDS
                    - vpcID
                    type: object
                  maxItems: 1
                  type: array
              required:
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
