apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: ecstaskdefinitions.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: EcsTaskDefinition
    listKind: EcsTaskDefinitionList
    plural: ecstaskdefinitions
    singular: ecstaskdefinition
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            arn:
              type: string
            containerDefinitions:
              type: string
            cpu:
              type: string
            executionRoleArn:
              type: string
            family:
              type: string
            id:
              type: string
            ipcMode:
              type: string
            memory:
              type: string
            networkMode:
              type: string
            pidMode:
              type: string
            placementConstraints:
              items:
                properties:
                  expression:
                    type: string
                  type:
                    type: string
                required:
                - type
                type: object
              maxItems: 10
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            requiresCompatibilities:
              items:
                type: string
              type: array
            revision:
              format: int64
              type: integer
            tags:
              additionalProperties:
                type: string
              type: object
            taskRoleArn:
              type: string
            volume:
              items:
                properties:
                  dockerVolumeConfiguration:
                    items:
                      properties:
                        autoprovision:
                          type: boolean
                        driver:
                          type: string
                        driverOpts:
                          additionalProperties:
                            type: string
                          type: object
                        labels:
                          additionalProperties:
                            type: string
                          type: object
                        scope:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  hostPath:
                    type: string
                  name:
                    type: string
                required:
                - name
                type: object
              type: array
          required:
          - containerDefinitions
          - family
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                arn:
                  type: string
                containerDefinitions:
                  type: string
                cpu:
                  type: string
                executionRoleArn:
                  type: string
                family:
                  type: string
                id:
                  type: string
                ipcMode:
                  type: string
                memory:
                  type: string
                networkMode:
                  type: string
                pidMode:
                  type: string
                placementConstraints:
                  items:
                    properties:
                      expression:
                        type: string
                      type:
                        type: string
                    required:
                    - type
                    type: object
                  maxItems: 10
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                requiresCompatibilities:
                  items:
                    type: string
                  type: array
                revision:
                  format: int64
                  type: integer
                tags:
                  additionalProperties:
                    type: string
                  type: object
                taskRoleArn:
                  type: string
                volume:
                  items:
                    properties:
                      dockerVolumeConfiguration:
                        items:
                          properties:
                            autoprovision:
                              type: boolean
                            driver:
                              type: string
                            driverOpts:
                              additionalProperties:
                                type: string
                              type: object
                            labels:
                              additionalProperties:
                                type: string
                              type: object
                            scope:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      hostPath:
                        type: string
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  type: array
              required:
              - containerDefinitions
              - family
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
