apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: instances.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: Instance
    listKind: InstanceList
    plural: instances
    singular: instance
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            ami:
              type: string
            arn:
              type: string
            associatePublicIPAddress:
              type: boolean
            availabilityZone:
              type: string
            cpuCoreCount:
              format: int64
              type: integer
            cpuThreadsPerCore:
              format: int64
              type: integer
            creditSpecification:
              items:
                properties:
                  cpuCredits:
                    type: string
                type: object
              maxItems: 1
              type: array
            disableAPITermination:
              type: boolean
            ebsBlockDevice:
              items:
                properties:
                  deleteOnTermination:
                    type: boolean
                  deviceName:
                    type: string
                  encrypted:
                    type: boolean
                  iops:
                    format: int64
                    type: integer
                  kmsKeyID:
                    type: string
                  snapshotID:
                    type: string
                  volumeID:
                    type: string
                  volumeSize:
                    format: int64
                    type: integer
                  volumeType:
                    type: string
                required:
                - deviceName
                type: object
              type: array
            ebsOptimized:
              type: boolean
            ephemeralBlockDevice:
              items:
                properties:
                  deviceName:
                    type: string
                  noDevice:
                    type: boolean
                  virtualName:
                    type: string
                required:
                - deviceName
                type: object
              type: array
            getPasswordData:
              type: boolean
            hostID:
              type: string
            iamInstanceProfile:
              type: string
            id:
              type: string
            instanceInitiatedShutdownBehavior:
              type: string
            instanceState:
              type: string
            instanceType:
              type: string
            ipv6AddressCount:
              format: int64
              type: integer
            ipv6Addresses:
              items:
                type: string
              type: array
            keyName:
              type: string
            monitoring:
              type: boolean
            networkInterface:
              items:
                properties:
                  deleteOnTermination:
                    type: boolean
                  deviceIndex:
                    format: int64
                    type: integer
                  networkInterfaceID:
                    type: string
                required:
                - deviceIndex
                - networkInterfaceID
                type: object
              type: array
            passwordData:
              type: string
            placementGroup:
              type: string
            primaryNetworkInterfaceID:
              type: string
            privateDNS:
              type: string
            privateIP:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            publicDNS:
              type: string
            publicIP:
              type: string
            rootBlockDevice:
              items:
                properties:
                  deleteOnTermination:
                    type: boolean
                  encrypted:
                    type: boolean
                  iops:
                    format: int64
                    type: integer
                  kmsKeyID:
                    type: string
                  volumeID:
                    type: string
                  volumeSize:
                    format: int64
                    type: integer
                  volumeType:
                    type: string
                type: object
              maxItems: 1
              type: array
            securityGroups:
              items:
                type: string
              type: array
            sourceDestCheck:
              type: boolean
            subnetID:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            tenancy:
              type: string
            userData:
              type: string
            userDataBase64:
              type: string
            volumeTags:
              additionalProperties:
                type: string
              type: object
            vpcSecurityGroupIDS:
              items:
                type: string
              type: array
          required:
          - ami
          - instanceType
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                ami:
                  type: string
                arn:
                  type: string
                associatePublicIPAddress:
                  type: boolean
                availabilityZone:
                  type: string
                cpuCoreCount:
                  format: int64
                  type: integer
                cpuThreadsPerCore:
                  format: int64
                  type: integer
                creditSpecification:
                  items:
                    properties:
                      cpuCredits:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                disableAPITermination:
                  type: boolean
                ebsBlockDevice:
                  items:
                    properties:
                      deleteOnTermination:
                        type: boolean
                      deviceName:
                        type: string
                      encrypted:
                        type: boolean
                      iops:
                        format: int64
                        type: integer
                      kmsKeyID:
                        type: string
                      snapshotID:
                        type: string
                      volumeID:
                        type: string
                      volumeSize:
                        format: int64
                        type: integer
                      volumeType:
                        type: string
                    required:
                    - deviceName
                    type: object
                  type: array
                ebsOptimized:
                  type: boolean
                ephemeralBlockDevice:
                  items:
                    properties:
                      deviceName:
                        type: string
                      noDevice:
                        type: boolean
                      virtualName:
                        type: string
                    required:
                    - deviceName
                    type: object
                  type: array
                getPasswordData:
                  type: boolean
                hostID:
                  type: string
                iamInstanceProfile:
                  type: string
                id:
                  type: string
                instanceInitiatedShutdownBehavior:
                  type: string
                instanceState:
                  type: string
                instanceType:
                  type: string
                ipv6AddressCount:
                  format: int64
                  type: integer
                ipv6Addresses:
                  items:
                    type: string
                  type: array
                keyName:
                  type: string
                monitoring:
                  type: boolean
                networkInterface:
                  items:
                    properties:
                      deleteOnTermination:
                        type: boolean
                      deviceIndex:
                        format: int64
                        type: integer
                      networkInterfaceID:
                        type: string
                    required:
                    - deviceIndex
                    - networkInterfaceID
                    type: object
                  type: array
                passwordData:
                  type: string
                placementGroup:
                  type: string
                primaryNetworkInterfaceID:
                  type: string
                privateDNS:
                  type: string
                privateIP:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                publicDNS:
                  type: string
                publicIP:
                  type: string
                rootBlockDevice:
                  items:
                    properties:
                      deleteOnTermination:
                        type: boolean
                      encrypted:
                        type: boolean
                      iops:
                        format: int64
                        type: integer
                      kmsKeyID:
                        type: string
                      volumeID:
                        type: string
                      volumeSize:
                        format: int64
                        type: integer
                      volumeType:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                securityGroups:
                  items:
                    type: string
                  type: array
                sourceDestCheck:
                  type: boolean
                subnetID:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                tenancy:
                  type: string
                userData:
                  type: string
                userDataBase64:
                  type: string
                volumeTags:
                  additionalProperties:
                    type: string
                  type: object
                vpcSecurityGroupIDS:
                  items:
                    type: string
                  type: array
              required:
              - ami
              - instanceType
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
