apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: autoscalingpolicies.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: AutoscalingPolicy
    listKind: AutoscalingPolicyList
    plural: autoscalingpolicies
    singular: autoscalingpolicy
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            adjustmentType:
              type: string
            arn:
              type: string
            autoscalingGroupName:
              type: string
            cooldown:
              format: int64
              type: integer
            estimatedInstanceWarmup:
              format: int64
              type: integer
            id:
              type: string
            metricAggregationType:
              type: string
            minAdjustmentMagnitude:
              format: int64
              type: integer
            name:
              type: string
            policyType:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            scalingAdjustment:
              format: int64
              type: integer
            stepAdjustment:
              items:
                properties:
                  metricIntervalLowerBound:
                    type: string
                  metricIntervalUpperBound:
                    type: string
                  scalingAdjustment:
                    format: int64
                    type: integer
                required:
                - scalingAdjustment
                type: object
              type: array
            targetTrackingConfiguration:
              items:
                properties:
                  customizedMetricSpecification:
                    items:
                      properties:
                        metricDimension:
                          items:
                            properties:
                              name:
                                type: string
                              value:
                                type: string
                            required:
                            - name
                            - value
                            type: object
                          type: array
                        metricName:
                          type: string
                        namespace:
                          type: string
                        statistic:
                          type: string
                        unit:
                          type: string
                      required:
                      - metricName
                      - namespace
                      - statistic
                      type: object
                    maxItems: 1
                    type: array
                  disableScaleIn:
                    type: boolean
                  predefinedMetricSpecification:
                    items:
                      properties:
                        predefinedMetricType:
                          type: string
                        resourceLabel:
                          type: string
                      required:
                      - predefinedMetricType
                      type: object
                    maxItems: 1
                    type: array
                  targetValue:
                    format: float
                    type: number
                required:
                - targetValue
                type: object
              maxItems: 1
              type: array
          required:
          - autoscalingGroupName
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                adjustmentType:
                  type: string
                arn:
                  type: string
                autoscalingGroupName:
                  type: string
                cooldown:
                  format: int64
                  type: integer
                estimatedInstanceWarmup:
                  format: int64
                  type: integer
                id:
                  type: string
                metricAggregationType:
                  type: string
                minAdjustmentMagnitude:
                  format: int64
                  type: integer
                name:
                  type: string
                policyType:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                scalingAdjustment:
                  format: int64
                  type: integer
                stepAdjustment:
                  items:
                    properties:
                      metricIntervalLowerBound:
                        type: string
                      metricIntervalUpperBound:
                        type: string
                      scalingAdjustment:
                        format: int64
                        type: integer
                    required:
                    - scalingAdjustment
                    type: object
                  type: array
                targetTrackingConfiguration:
                  items:
                    properties:
                      customizedMetricSpecification:
                        items:
                          properties:
                            metricDimension:
                              items:
                                properties:
                                  name:
                                    type: string
                                  value:
                                    type: string
                                required:
                                - name
                                - value
                                type: object
                              type: array
                            metricName:
                              type: string
                            namespace:
                              type: string
                            statistic:
                              type: string
                            unit:
                              type: string
                          required:
                          - metricName
                          - namespace
                          - statistic
                          type: object
                        maxItems: 1
                        type: array
                      disableScaleIn:
                        type: boolean
                      predefinedMetricSpecification:
                        items:
                          properties:
                            predefinedMetricType:
                              type: string
                            resourceLabel:
                              type: string
                          required:
                          - predefinedMetricType
                          type: object
                        maxItems: 1
                        type: array
                      targetValue:
                        format: float
                        type: number
                    required:
                    - targetValue
                    type: object
                  maxItems: 1
                  type: array
              required:
              - autoscalingGroupName
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
