apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: gluecrawlers.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: GlueCrawler
    listKind: GlueCrawlerList
    plural: gluecrawlers
    singular: gluecrawler
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            arn:
              type: string
            catalogTarget:
              items:
                properties:
                  databaseName:
                    type: string
                  tables:
                    items:
                      type: string
                    type: array
                required:
                - databaseName
                - tables
                type: object
              minItems: 1
              type: array
            classifiers:
              items:
                type: string
              type: array
            configuration:
              type: string
            databaseName:
              type: string
            description:
              type: string
            dynamodbTarget:
              items:
                properties:
                  path:
                    type: string
                required:
                - path
                type: object
              minItems: 1
              type: array
            id:
              type: string
            jdbcTarget:
              items:
                properties:
                  connectionName:
                    type: string
                  exclusions:
                    items:
                      type: string
                    type: array
                  path:
                    type: string
                required:
                - connectionName
                - path
                type: object
              minItems: 1
              type: array
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            role:
              type: string
            s3Target:
              items:
                properties:
                  exclusions:
                    items:
                      type: string
                    type: array
                  path:
                    type: string
                required:
                - path
                type: object
              minItems: 1
              type: array
            schedule:
              type: string
            schemaChangePolicy:
              items:
                properties:
                  deleteBehavior:
                    type: string
                  updateBehavior:
                    type: string
                type: object
              maxItems: 1
              type: array
            securityConfiguration:
              type: string
            tablePrefix:
              type: string
          required:
          - databaseName
          - name
          - providerRef
          - role
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                arn:
                  type: string
                catalogTarget:
                  items:
                    properties:
                      databaseName:
                        type: string
                      tables:
                        items:
                          type: string
                        type: array
                    required:
                    - databaseName
                    - tables
                    type: object
                  minItems: 1
                  type: array
                classifiers:
                  items:
                    type: string
                  type: array
                configuration:
                  type: string
                databaseName:
                  type: string
                description:
                  type: string
                dynamodbTarget:
                  items:
                    properties:
                      path:
                        type: string
                    required:
                    - path
                    type: object
                  minItems: 1
                  type: array
                id:
                  type: string
                jdbcTarget:
                  items:
                    properties:
                      connectionName:
                        type: string
                      exclusions:
                        items:
                          type: string
                        type: array
                      path:
                        type: string
                    required:
                    - connectionName
                    - path
                    type: object
                  minItems: 1
                  type: array
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                role:
                  type: string
                s3Target:
                  items:
                    properties:
                      exclusions:
                        items:
                          type: string
                        type: array
                      path:
                        type: string
                    required:
                    - path
                    type: object
                  minItems: 1
                  type: array
                schedule:
                  type: string
                schemaChangePolicy:
                  items:
                    properties:
                      deleteBehavior:
                        type: string
                      updateBehavior:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                securityConfiguration:
                  type: string
                tablePrefix:
                  type: string
              required:
              - databaseName
              - name
              - providerRef
              - role
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
