apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: dmsreplicationinstances.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: DmsReplicationInstance
    listKind: DmsReplicationInstanceList
    plural: dmsreplicationinstances
    singular: dmsreplicationinstance
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            allocatedStorage:
              format: int64
              type: integer
            applyImmediately:
              type: boolean
            autoMinorVersionUpgrade:
              type: boolean
            availabilityZone:
              type: string
            engineVersion:
              type: string
            id:
              type: string
            kmsKeyArn:
              type: string
            multiAz:
              type: boolean
            preferredMaintenanceWindow:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            publiclyAccessible:
              type: boolean
            replicationInstanceArn:
              type: string
            replicationInstanceClass:
              type: string
            replicationInstanceID:
              type: string
            replicationInstancePrivateIPS:
              items:
                type: string
              type: array
            replicationInstancePublicIPS:
              items:
                type: string
              type: array
            replicationSubnetGroupID:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            vpcSecurityGroupIDS:
              items:
                type: string
              type: array
          required:
          - providerRef
          - replicationInstanceClass
          - replicationInstanceID
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                allocatedStorage:
                  format: int64
                  type: integer
                applyImmediately:
                  type: boolean
                autoMinorVersionUpgrade:
                  type: boolean
                availabilityZone:
                  type: string
                engineVersion:
                  type: string
                id:
                  type: string
                kmsKeyArn:
                  type: string
                multiAz:
                  type: boolean
                preferredMaintenanceWindow:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                publiclyAccessible:
                  type: boolean
                replicationInstanceArn:
                  type: string
                replicationInstanceClass:
                  type: string
                replicationInstanceID:
                  type: string
                replicationInstancePrivateIPS:
                  items:
                    type: string
                  type: array
                replicationInstancePublicIPS:
                  items:
                    type: string
                  type: array
                replicationSubnetGroupID:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                vpcSecurityGroupIDS:
                  items:
                    type: string
                  type: array
              required:
              - providerRef
              - replicationInstanceClass
              - replicationInstanceID
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
