apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: codebuildprojects.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: CodebuildProject
    listKind: CodebuildProjectList
    plural: codebuildprojects
    singular: codebuildproject
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            arn:
              type: string
            artifacts:
              items:
                properties:
                  encryptionDisabled:
                    type: boolean
                  location:
                    type: string
                  name:
                    type: string
                  namespaceType:
                    type: string
                  packaging:
                    type: string
                  path:
                    type: string
                  type:
                    type: string
                required:
                - type
                type: object
              maxItems: 1
              type: array
            badgeEnabled:
              type: boolean
            badgeURL:
              type: string
            buildTimeout:
              format: int64
              type: integer
            cache:
              items:
                properties:
                  location:
                    type: string
                  type:
                    type: string
                type: object
              maxItems: 1
              type: array
            description:
              type: string
            encryptionKey:
              type: string
            environment:
              items:
                properties:
                  certificate:
                    type: string
                  computeType:
                    type: string
                  environmentVariable:
                    items:
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                        value:
                          type: string
                      required:
                      - name
                      - value
                      type: object
                    type: array
                  image:
                    type: string
                  imagePullCredentialsType:
                    type: string
                  privilegedMode:
                    type: boolean
                  type:
                    type: string
                required:
                - computeType
                - image
                - type
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            secondaryArtifacts:
              items:
                properties:
                  artifactIdentifier:
                    type: string
                  encryptionDisabled:
                    type: boolean
                  location:
                    type: string
                  name:
                    type: string
                  namespaceType:
                    type: string
                  packaging:
                    type: string
                  path:
                    type: string
                  type:
                    type: string
                required:
                - artifactIdentifier
                - type
                type: object
              type: array
            secondarySources:
              items:
                properties:
                  auth:
                    items:
                      properties:
                        type:
                          type: string
                      required:
                      - type
                      type: object
                    type: array
                  buildspec:
                    type: string
                  gitCloneDepth:
                    format: int64
                    type: integer
                  insecureSSL:
                    type: boolean
                  location:
                    type: string
                  reportBuildStatus:
                    type: boolean
                  sourceIdentifier:
                    type: string
                  type:
                    type: string
                required:
                - sourceIdentifier
                - type
                type: object
              type: array
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            serviceRole:
              type: string
            source:
              items:
                properties:
                  auth:
                    items:
                      properties:
                        type:
                          type: string
                      required:
                      - type
                      type: object
                    type: array
                  buildspec:
                    type: string
                  gitCloneDepth:
                    format: int64
                    type: integer
                  insecureSSL:
                    type: boolean
                  location:
                    type: string
                  reportBuildStatus:
                    type: boolean
                  type:
                    type: string
                required:
                - type
                type: object
              maxItems: 1
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
            vpcConfig:
              items:
                properties:
                  securityGroupIDS:
                    items:
                      type: string
                    maxItems: 5
                    type: array
                  subnets:
                    items:
                      type: string
                    maxItems: 16
                    type: array
                  vpcID:
                    type: string
                required:
                - securityGroupIDS
                - subnets
                - vpcID
                type: object
              maxItems: 1
              type: array
          required:
          - artifacts
          - environment
          - name
          - providerRef
          - serviceRole
          - source
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                arn:
                  type: string
                artifacts:
                  items:
                    properties:
                      encryptionDisabled:
                        type: boolean
                      location:
                        type: string
                      name:
                        type: string
                      namespaceType:
                        type: string
                      packaging:
                        type: string
                      path:
                        type: string
                      type:
                        type: string
                    required:
                    - type
                    type: object
                  maxItems: 1
                  type: array
                badgeEnabled:
                  type: boolean
                badgeURL:
                  type: string
                buildTimeout:
                  format: int64
                  type: integer
                cache:
                  items:
                    properties:
                      location:
                        type: string
                      type:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                description:
                  type: string
                encryptionKey:
                  type: string
                environment:
                  items:
                    properties:
                      certificate:
                        type: string
                      computeType:
                        type: string
                      environmentVariable:
                        items:
                          properties:
                            name:
                              type: string
                            type:
                              type: string
                            value:
                              type: string
                          required:
                          - name
                          - value
                          type: object
                        type: array
                      image:
                        type: string
                      imagePullCredentialsType:
                        type: string
                      privilegedMode:
                        type: boolean
                      type:
                        type: string
                    required:
                    - computeType
                    - image
                    - type
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                secondaryArtifacts:
                  items:
                    properties:
                      artifactIdentifier:
                        type: string
                      encryptionDisabled:
                        type: boolean
                      location:
                        type: string
                      name:
                        type: string
                      namespaceType:
                        type: string
                      packaging:
                        type: string
                      path:
                        type: string
                      type:
                        type: string
                    required:
                    - artifactIdentifier
                    - type
                    type: object
                  type: array
                secondarySources:
                  items:
                    properties:
                      auth:
                        items:
                          properties:
                            type:
                              type: string
                          required:
                          - type
                          type: object
                        type: array
                      buildspec:
                        type: string
                      gitCloneDepth:
                        format: int64
                        type: integer
                      insecureSSL:
                        type: boolean
                      location:
                        type: string
                      reportBuildStatus:
                        type: boolean
                      sourceIdentifier:
                        type: string
                      type:
                        type: string
                    required:
                    - sourceIdentifier
                    - type
                    type: object
                  type: array
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                serviceRole:
                  type: string
                source:
                  items:
                    properties:
                      auth:
                        items:
                          properties:
                            type:
                              type: string
                          required:
                          - type
                          type: object
                        type: array
                      buildspec:
                        type: string
                      gitCloneDepth:
                        format: int64
                        type: integer
                      insecureSSL:
                        type: boolean
                      location:
                        type: string
                      reportBuildStatus:
                        type: boolean
                      type:
                        type: string
                    required:
                    - type
                    type: object
                  maxItems: 1
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
                vpcConfig:
                  items:
                    properties:
                      securityGroupIDS:
                        items:
                          type: string
                        maxItems: 5
                        type: array
                      subnets:
                        items:
                          type: string
                        maxItems: 16
                        type: array
                      vpcID:
                        type: string
                    required:
                    - securityGroupIDS
                    - subnets
                    - vpcID
                    type: object
                  maxItems: 1
                  type: array
              required:
              - artifacts
              - environment
              - name
              - providerRef
              - serviceRole
              - source
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
