apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: ssmmaintenancewindowtasks.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: SsmMaintenanceWindowTask
    listKind: SsmMaintenanceWindowTaskList
    plural: ssmmaintenancewindowtasks
    singular: ssmmaintenancewindowtask
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              type: string
            id:
              type: string
            loggingInfo:
              description: Deprecated
              items:
                properties:
                  s3BucketName:
                    type: string
                  s3BucketPrefix:
                    type: string
                  s3Region:
                    type: string
                required:
                - s3BucketName
                - s3Region
                type: object
              maxItems: 1
              type: array
            maxConcurrency:
              type: string
            maxErrors:
              type: string
            name:
              type: string
            priority:
              format: int64
              type: integer
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            serviceRoleArn:
              type: string
            targets:
              items:
                properties:
                  key:
                    type: string
                  values:
                    items:
                      type: string
                    type: array
                required:
                - key
                - values
                type: object
              type: array
            taskArn:
              type: string
            taskInvocationParameters:
              items:
                properties:
                  automationParameters:
                    items:
                      properties:
                        documentVersion:
                          type: string
                        parameter:
                          items:
                            properties:
                              name:
                                type: string
                              values:
                                items:
                                  type: string
                                type: array
                            required:
                            - name
                            - values
                            type: object
                          type: array
                      type: object
                    maxItems: 1
                    type: array
                  lambdaParameters:
                    items:
                      properties:
                        clientContext:
                          type: string
                        qualifier:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  runCommandParameters:
                    items:
                      properties:
                        comment:
                          type: string
                        documentHash:
                          type: string
                        documentHashType:
                          type: string
                        notificationConfig:
                          items:
                            properties:
                              notificationArn:
                                type: string
                              notificationEvents:
                                items:
                                  type: string
                                type: array
                              notificationType:
                                type: string
                            type: object
                          maxItems: 1
                          type: array
                        outputS3Bucket:
                          type: string
                        outputS3KeyPrefix:
                          type: string
                        parameter:
                          items:
                            properties:
                              name:
                                type: string
                              values:
                                items:
                                  type: string
                                type: array
                            required:
                            - name
                            - values
                            type: object
                          type: array
                        serviceRoleArn:
                          type: string
                        timeoutSeconds:
                          format: int64
                          type: integer
                      type: object
                    maxItems: 1
                    type: array
                  stepFunctionsParameters:
                    items:
                      properties:
                        name:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                type: object
              maxItems: 1
              type: array
            taskParameters:
              description: Deprecated
              items:
                properties:
                  name:
                    type: string
                  values:
                    items:
                      type: string
                    type: array
                required:
                - name
                - values
                type: object
              type: array
            taskType:
              type: string
            windowID:
              type: string
          required:
          - maxConcurrency
          - maxErrors
          - providerRef
          - serviceRoleArn
          - targets
          - taskArn
          - taskType
          - windowID
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                description:
                  type: string
                id:
                  type: string
                loggingInfo:
                  description: Deprecated
                  items:
                    properties:
                      s3BucketName:
                        type: string
                      s3BucketPrefix:
                        type: string
                      s3Region:
                        type: string
                    required:
                    - s3BucketName
                    - s3Region
                    type: object
                  maxItems: 1
                  type: array
                maxConcurrency:
                  type: string
                maxErrors:
                  type: string
                name:
                  type: string
                priority:
                  format: int64
                  type: integer
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                serviceRoleArn:
                  type: string
                targets:
                  items:
                    properties:
                      key:
                        type: string
                      values:
                        items:
                          type: string
                        type: array
                    required:
                    - key
                    - values
                    type: object
                  type: array
                taskArn:
                  type: string
                taskInvocationParameters:
                  items:
                    properties:
                      automationParameters:
                        items:
                          properties:
                            documentVersion:
                              type: string
                            parameter:
                              items:
                                properties:
                                  name:
                                    type: string
                                  values:
                                    items:
                                      type: string
                                    type: array
                                required:
                                - name
                                - values
                                type: object
                              type: array
                          type: object
                        maxItems: 1
                        type: array
                      lambdaParameters:
                        items:
                          properties:
                            clientContext:
                              type: string
                            qualifier:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      runCommandParameters:
                        items:
                          properties:
                            comment:
                              type: string
                            documentHash:
                              type: string
                            documentHashType:
                              type: string
                            notificationConfig:
                              items:
                                properties:
                                  notificationArn:
                                    type: string
                                  notificationEvents:
                                    items:
                                      type: string
                                    type: array
                                  notificationType:
                                    type: string
                                type: object
                              maxItems: 1
                              type: array
                            outputS3Bucket:
                              type: string
                            outputS3KeyPrefix:
                              type: string
                            parameter:
                              items:
                                properties:
                                  name:
                                    type: string
                                  values:
                                    items:
                                      type: string
                                    type: array
                                required:
                                - name
                                - values
                                type: object
                              type: array
                            serviceRoleArn:
                              type: string
                            timeoutSeconds:
                              format: int64
                              type: integer
                          type: object
                        maxItems: 1
                        type: array
                      stepFunctionsParameters:
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                    type: object
                  maxItems: 1
                  type: array
                taskParameters:
                  description: Deprecated
                  items:
                    properties:
                      name:
                        type: string
                      values:
                        items:
                          type: string
                        type: array
                    required:
                    - name
                    - values
                    type: object
                  type: array
                taskType:
                  type: string
                windowID:
                  type: string
              required:
              - maxConcurrency
              - maxErrors
              - providerRef
              - serviceRoleArn
              - targets
              - taskArn
              - taskType
              - windowID
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
