apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: dmsendpoints.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: DmsEndpoint
    listKind: DmsEndpointList
    plural: dmsendpoints
    singular: dmsendpoint
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            certificateArn:
              type: string
            databaseName:
              type: string
            endpointArn:
              type: string
            endpointID:
              type: string
            endpointType:
              type: string
            engineName:
              type: string
            extraConnectionAttributes:
              type: string
            id:
              type: string
            kmsKeyArn:
              type: string
            mongodbSettings:
              items:
                properties:
                  authMechanism:
                    type: string
                  authSource:
                    type: string
                  authType:
                    type: string
                  docsToInvestigate:
                    type: string
                  extractDocID:
                    type: string
                  nestingLevel:
                    type: string
                type: object
              maxItems: 1
              type: array
            port:
              format: int64
              type: integer
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            s3Settings:
              items:
                properties:
                  bucketFolder:
                    type: string
                  bucketName:
                    type: string
                  compressionType:
                    type: string
                  csvDelimiter:
                    type: string
                  csvRowDelimiter:
                    type: string
                  externalTableDefinition:
                    type: string
                  serviceAccessRoleArn:
                    type: string
                type: object
              maxItems: 1
              type: array
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            serverName:
              type: string
            serviceAccessRole:
              type: string
            sslMode:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            username:
              type: string
          required:
          - endpointID
          - endpointType
          - engineName
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                certificateArn:
                  type: string
                databaseName:
                  type: string
                endpointArn:
                  type: string
                endpointID:
                  type: string
                endpointType:
                  type: string
                engineName:
                  type: string
                extraConnectionAttributes:
                  type: string
                id:
                  type: string
                kmsKeyArn:
                  type: string
                mongodbSettings:
                  items:
                    properties:
                      authMechanism:
                        type: string
                      authSource:
                        type: string
                      authType:
                        type: string
                      docsToInvestigate:
                        type: string
                      extractDocID:
                        type: string
                      nestingLevel:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                port:
                  format: int64
                  type: integer
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                s3Settings:
                  items:
                    properties:
                      bucketFolder:
                        type: string
                      bucketName:
                        type: string
                      compressionType:
                        type: string
                      csvDelimiter:
                        type: string
                      csvRowDelimiter:
                        type: string
                      externalTableDefinition:
                        type: string
                      serviceAccessRoleArn:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                serverName:
                  type: string
                serviceAccessRole:
                  type: string
                sslMode:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                username:
                  type: string
              required:
              - endpointID
              - endpointType
              - engineName
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
