apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: lambdafunctions.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: LambdaFunction
    listKind: LambdaFunctionList
    plural: lambdafunctions
    singular: lambdafunction
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            arn:
              type: string
            deadLetterConfig:
              items:
                properties:
                  targetArn:
                    type: string
                required:
                - targetArn
                type: object
              maxItems: 1
              type: array
            description:
              type: string
            environment:
              items:
                properties:
                  variables:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              maxItems: 1
              type: array
            filename:
              type: string
            functionName:
              type: string
            handler:
              type: string
            id:
              type: string
            invokeArn:
              type: string
            kmsKeyArn:
              type: string
            lastModified:
              type: string
            layers:
              items:
                type: string
              maxItems: 5
              type: array
            memorySize:
              format: int64
              type: integer
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            publish:
              type: boolean
            qualifiedArn:
              type: string
            reservedConcurrentExecutions:
              format: int64
              type: integer
            role:
              type: string
            runtime:
              type: string
            s3Bucket:
              type: string
            s3Key:
              type: string
            s3ObjectVersion:
              type: string
            sourceCodeHash:
              type: string
            sourceCodeSize:
              format: int64
              type: integer
            tags:
              additionalProperties:
                type: string
              type: object
            timeout:
              format: int64
              type: integer
            tracingConfig:
              items:
                properties:
                  mode:
                    type: string
                required:
                - mode
                type: object
              maxItems: 1
              type: array
            version:
              type: string
            vpcConfig:
              items:
                properties:
                  securityGroupIDS:
                    items:
                      type: string
                    type: array
                  subnetIDS:
                    items:
                      type: string
                    type: array
                  vpcID:
                    type: string
                required:
                - securityGroupIDS
                - subnetIDS
                type: object
              maxItems: 1
              type: array
          required:
          - functionName
          - handler
          - providerRef
          - role
          - runtime
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                arn:
                  type: string
                deadLetterConfig:
                  items:
                    properties:
                      targetArn:
                        type: string
                    required:
                    - targetArn
                    type: object
                  maxItems: 1
                  type: array
                description:
                  type: string
                environment:
                  items:
                    properties:
                      variables:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  maxItems: 1
                  type: array
                filename:
                  type: string
                functionName:
                  type: string
                handler:
                  type: string
                id:
                  type: string
                invokeArn:
                  type: string
                kmsKeyArn:
                  type: string
                lastModified:
                  type: string
                layers:
                  items:
                    type: string
                  maxItems: 5
                  type: array
                memorySize:
                  format: int64
                  type: integer
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                publish:
                  type: boolean
                qualifiedArn:
                  type: string
                reservedConcurrentExecutions:
                  format: int64
                  type: integer
                role:
                  type: string
                runtime:
                  type: string
                s3Bucket:
                  type: string
                s3Key:
                  type: string
                s3ObjectVersion:
                  type: string
                sourceCodeHash:
                  type: string
                sourceCodeSize:
                  format: int64
                  type: integer
                tags:
                  additionalProperties:
                    type: string
                  type: object
                timeout:
                  format: int64
                  type: integer
                tracingConfig:
                  items:
                    properties:
                      mode:
                        type: string
                    required:
                    - mode
                    type: object
                  maxItems: 1
                  type: array
                version:
                  type: string
                vpcConfig:
                  items:
                    properties:
                      securityGroupIDS:
                        items:
                          type: string
                        type: array
                      subnetIDS:
                        items:
                          type: string
                        type: array
                      vpcID:
                        type: string
                    required:
                    - securityGroupIDS
                    - subnetIDS
                    type: object
                  maxItems: 1
                  type: array
              required:
              - functionName
              - handler
              - providerRef
              - role
              - runtime
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
