apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: elasticachereplicationgroups.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: ElasticacheReplicationGroup
    listKind: ElasticacheReplicationGroupList
    plural: elasticachereplicationgroups
    singular: elasticachereplicationgroup
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            applyImmediately:
              type: boolean
            atRestEncryptionEnabled:
              type: boolean
            autoMinorVersionUpgrade:
              type: boolean
            automaticFailoverEnabled:
              type: boolean
            availabilityZones:
              items:
                type: string
              type: array
            clusterMode:
              items:
                properties:
                  numNodeGroups:
                    format: int64
                    type: integer
                  replicasPerNodeGroup:
                    format: int64
                    type: integer
                required:
                - numNodeGroups
                - replicasPerNodeGroup
                type: object
              maxItems: 1
              type: array
            configurationEndpointAddress:
              type: string
            engine:
              type: string
            engineVersion:
              type: string
            id:
              type: string
            maintenanceWindow:
              type: string
            memberClusters:
              items:
                type: string
              type: array
            nodeType:
              type: string
            notificationTopicArn:
              type: string
            numberCacheClusters:
              format: int64
              type: integer
            parameterGroupName:
              type: string
            port:
              format: int64
              type: integer
            primaryEndpointAddress:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            replicationGroupDescription:
              type: string
            replicationGroupID:
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            securityGroupIDS:
              items:
                type: string
              type: array
            securityGroupNames:
              items:
                type: string
              type: array
            snapshotArns:
              items:
                type: string
              type: array
            snapshotName:
              type: string
            snapshotRetentionLimit:
              format: int64
              type: integer
            snapshotWindow:
              type: string
            subnetGroupName:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            transitEncryptionEnabled:
              type: boolean
          required:
          - providerRef
          - replicationGroupDescription
          - replicationGroupID
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                applyImmediately:
                  type: boolean
                atRestEncryptionEnabled:
                  type: boolean
                autoMinorVersionUpgrade:
                  type: boolean
                automaticFailoverEnabled:
                  type: boolean
                availabilityZones:
                  items:
                    type: string
                  type: array
                clusterMode:
                  items:
                    properties:
                      numNodeGroups:
                        format: int64
                        type: integer
                      replicasPerNodeGroup:
                        format: int64
                        type: integer
                    required:
                    - numNodeGroups
                    - replicasPerNodeGroup
                    type: object
                  maxItems: 1
                  type: array
                configurationEndpointAddress:
                  type: string
                engine:
                  type: string
                engineVersion:
                  type: string
                id:
                  type: string
                maintenanceWindow:
                  type: string
                memberClusters:
                  items:
                    type: string
                  type: array
                nodeType:
                  type: string
                notificationTopicArn:
                  type: string
                numberCacheClusters:
                  format: int64
                  type: integer
                parameterGroupName:
                  type: string
                port:
                  format: int64
                  type: integer
                primaryEndpointAddress:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                replicationGroupDescription:
                  type: string
                replicationGroupID:
                  type: string
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                securityGroupIDS:
                  items:
                    type: string
                  type: array
                securityGroupNames:
                  items:
                    type: string
                  type: array
                snapshotArns:
                  items:
                    type: string
                  type: array
                snapshotName:
                  type: string
                snapshotRetentionLimit:
                  format: int64
                  type: integer
                snapshotWindow:
                  type: string
                subnetGroupName:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                transitEncryptionEnabled:
                  type: boolean
              required:
              - providerRef
              - replicationGroupDescription
              - replicationGroupID
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
