apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: opsworksstacks.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: OpsworksStack
    listKind: OpsworksStackList
    plural: opsworksstacks
    singular: opsworksstack
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            agentVersion:
              type: string
            arn:
              type: string
            berkshelfVersion:
              type: string
            color:
              type: string
            configurationManagerName:
              type: string
            configurationManagerVersion:
              type: string
            customCookbooksSource:
              items:
                properties:
                  revision:
                    type: string
                  sshKey:
                    type: string
                  type:
                    type: string
                  url:
                    type: string
                  username:
                    type: string
                required:
                - type
                - url
                type: object
              type: array
            customJSON:
              type: string
            defaultAvailabilityZone:
              type: string
            defaultInstanceProfileArn:
              type: string
            defaultOs:
              type: string
            defaultRootDeviceType:
              type: string
            defaultSSHKeyName:
              type: string
            defaultSubnetID:
              type: string
            hostnameTheme:
              type: string
            id:
              type: string
            manageBerkshelf:
              type: boolean
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            serviceRoleArn:
              type: string
            stackEndpoint:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            useCustomCookbooks:
              type: boolean
            useOpsworksSecurityGroups:
              type: boolean
            vpcID:
              type: string
          required:
          - defaultInstanceProfileArn
          - name
          - providerRef
          - region
          - serviceRoleArn
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                agentVersion:
                  type: string
                arn:
                  type: string
                berkshelfVersion:
                  type: string
                color:
                  type: string
                configurationManagerName:
                  type: string
                configurationManagerVersion:
                  type: string
                customCookbooksSource:
                  items:
                    properties:
                      revision:
                        type: string
                      sshKey:
                        type: string
                      type:
                        type: string
                      url:
                        type: string
                      username:
                        type: string
                    required:
                    - type
                    - url
                    type: object
                  type: array
                customJSON:
                  type: string
                defaultAvailabilityZone:
                  type: string
                defaultInstanceProfileArn:
                  type: string
                defaultOs:
                  type: string
                defaultRootDeviceType:
                  type: string
                defaultSSHKeyName:
                  type: string
                defaultSubnetID:
                  type: string
                hostnameTheme:
                  type: string
                id:
                  type: string
                manageBerkshelf:
                  type: boolean
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                region:
                  type: string
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                serviceRoleArn:
                  type: string
                stackEndpoint:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                useCustomCookbooks:
                  type: boolean
                useOpsworksSecurityGroups:
                  type: boolean
                vpcID:
                  type: string
              required:
              - defaultInstanceProfileArn
              - name
              - providerRef
              - region
              - serviceRoleArn
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
