apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: cloudwatcheventtargets.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: CloudwatchEventTarget
    listKind: CloudwatchEventTargetList
    plural: cloudwatcheventtargets
    singular: cloudwatcheventtarget
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            arn:
              type: string
            batchTarget:
              items:
                properties:
                  arraySize:
                    format: int64
                    type: integer
                  jobAttempts:
                    format: int64
                    type: integer
                  jobDefinition:
                    type: string
                  jobName:
                    type: string
                required:
                - jobDefinition
                - jobName
                type: object
              maxItems: 1
              type: array
            ecsTarget:
              items:
                properties:
                  group:
                    type: string
                  launchType:
                    type: string
                  networkConfiguration:
                    items:
                      properties:
                        assignPublicIP:
                          type: boolean
                        securityGroups:
                          items:
                            type: string
                          type: array
                        subnets:
                          items:
                            type: string
                          type: array
                      required:
                      - subnets
                      type: object
                    maxItems: 1
                    type: array
                  platformVersion:
                    type: string
                  taskCount:
                    format: int64
                    type: integer
                  taskDefinitionArn:
                    type: string
                required:
                - taskDefinitionArn
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            input:
              type: string
            inputPath:
              type: string
            inputTransformer:
              items:
                properties:
                  inputPaths:
                    additionalProperties:
                      type: string
                    type: object
                  inputTemplate:
                    type: string
                required:
                - inputTemplate
                type: object
              maxItems: 1
              type: array
            kinesisTarget:
              items:
                properties:
                  partitionKeyPath:
                    type: string
                type: object
              maxItems: 1
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            roleArn:
              type: string
            rule:
              type: string
            runCommandTargets:
              items:
                properties:
                  key:
                    type: string
                  values:
                    items:
                      type: string
                    type: array
                required:
                - key
                - values
                type: object
              maxItems: 5
              type: array
            sqsTarget:
              items:
                properties:
                  messageGroupID:
                    type: string
                type: object
              maxItems: 1
              type: array
            targetID:
              type: string
          required:
          - arn
          - providerRef
          - rule
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                arn:
                  type: string
                batchTarget:
                  items:
                    properties:
                      arraySize:
                        format: int64
                        type: integer
                      jobAttempts:
                        format: int64
                        type: integer
                      jobDefinition:
                        type: string
                      jobName:
                        type: string
                    required:
                    - jobDefinition
                    - jobName
                    type: object
                  maxItems: 1
                  type: array
                ecsTarget:
                  items:
                    properties:
                      group:
                        type: string
                      launchType:
                        type: string
                      networkConfiguration:
                        items:
                          properties:
                            assignPublicIP:
                              type: boolean
                            securityGroups:
                              items:
                                type: string
                              type: array
                            subnets:
                              items:
                                type: string
                              type: array
                          required:
                          - subnets
                          type: object
                        maxItems: 1
                        type: array
                      platformVersion:
                        type: string
                      taskCount:
                        format: int64
                        type: integer
                      taskDefinitionArn:
                        type: string
                    required:
                    - taskDefinitionArn
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                input:
                  type: string
                inputPath:
                  type: string
                inputTransformer:
                  items:
                    properties:
                      inputPaths:
                        additionalProperties:
                          type: string
                        type: object
                      inputTemplate:
                        type: string
                    required:
                    - inputTemplate
                    type: object
                  maxItems: 1
                  type: array
                kinesisTarget:
                  items:
                    properties:
                      partitionKeyPath:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                roleArn:
                  type: string
                rule:
                  type: string
                runCommandTargets:
                  items:
                    properties:
                      key:
                        type: string
                      values:
                        items:
                          type: string
                        type: array
                    required:
                    - key
                    - values
                    type: object
                  maxItems: 5
                  type: array
                sqsTarget:
                  items:
                    properties:
                      messageGroupID:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                targetID:
                  type: string
              required:
              - arn
              - providerRef
              - rule
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
