apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: mqbrokers.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: MqBroker
    listKind: MqBrokerList
    plural: mqbrokers
    singular: mqbroker
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            applyImmediately:
              type: boolean
            arn:
              type: string
            autoMinorVersionUpgrade:
              type: boolean
            brokerName:
              type: string
            configuration:
              items:
                properties:
                  ID:
                    type: string
                  revision:
                    format: int64
                    type: integer
                type: object
              maxItems: 1
              type: array
            deploymentMode:
              type: string
            engineType:
              type: string
            engineVersion:
              type: string
            hostInstanceType:
              type: string
            id:
              type: string
            instances:
              items:
                properties:
                  consoleURL:
                    type: string
                  endpoints:
                    items:
                      type: string
                    type: array
                  ipAddress:
                    type: string
                type: object
              type: array
            logs:
              items:
                properties:
                  audit:
                    type: boolean
                  general:
                    type: boolean
                type: object
              maxItems: 1
              type: array
            maintenanceWindowStartTime:
              items:
                properties:
                  dayOfWeek:
                    type: string
                  timeOfDay:
                    type: string
                  timeZone:
                    type: string
                required:
                - dayOfWeek
                - timeOfDay
                - timeZone
                type: object
              maxItems: 1
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            publiclyAccessible:
              type: boolean
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            securityGroups:
              items:
                type: string
              type: array
            subnetIDS:
              items:
                type: string
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
            user:
              items:
                properties:
                  consoleAccess:
                    type: boolean
                  groups:
                    items:
                      type: string
                    type: array
                  username:
                    type: string
                required:
                - username
                type: object
              type: array
          required:
          - brokerName
          - engineType
          - engineVersion
          - hostInstanceType
          - providerRef
          - securityGroups
          - user
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                applyImmediately:
                  type: boolean
                arn:
                  type: string
                autoMinorVersionUpgrade:
                  type: boolean
                brokerName:
                  type: string
                configuration:
                  items:
                    properties:
                      ID:
                        type: string
                      revision:
                        format: int64
                        type: integer
                    type: object
                  maxItems: 1
                  type: array
                deploymentMode:
                  type: string
                engineType:
                  type: string
                engineVersion:
                  type: string
                hostInstanceType:
                  type: string
                id:
                  type: string
                instances:
                  items:
                    properties:
                      consoleURL:
                        type: string
                      endpoints:
                        items:
                          type: string
                        type: array
                      ipAddress:
                        type: string
                    type: object
                  type: array
                logs:
                  items:
                    properties:
                      audit:
                        type: boolean
                      general:
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
                maintenanceWindowStartTime:
                  items:
                    properties:
                      dayOfWeek:
                        type: string
                      timeOfDay:
                        type: string
                      timeZone:
                        type: string
                    required:
                    - dayOfWeek
                    - timeOfDay
                    - timeZone
                    type: object
                  maxItems: 1
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                publiclyAccessible:
                  type: boolean
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                securityGroups:
                  items:
                    type: string
                  type: array
                subnetIDS:
                  items:
                    type: string
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
                user:
                  items:
                    properties:
                      consoleAccess:
                        type: boolean
                      groups:
                        items:
                          type: string
                        type: array
                      username:
                        type: string
                    required:
                    - username
                    type: object
                  type: array
              required:
              - brokerName
              - engineType
              - engineVersion
              - hostInstanceType
              - providerRef
              - securityGroups
              - user
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
