apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: codedeploydeploymentgroups.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: CodedeployDeploymentGroup
    listKind: CodedeployDeploymentGroupList
    plural: codedeploydeploymentgroups
    singular: codedeploydeploymentgroup
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            alarmConfiguration:
              items:
                properties:
                  alarms:
                    items:
                      type: string
                    maxItems: 10
                    type: array
                  enabled:
                    type: boolean
                  ignorePollAlarmFailure:
                    type: boolean
                type: object
              maxItems: 1
              type: array
            appName:
              type: string
            autoRollbackConfiguration:
              items:
                properties:
                  enabled:
                    type: boolean
                  events:
                    items:
                      type: string
                    type: array
                type: object
              maxItems: 1
              type: array
            autoscalingGroups:
              items:
                type: string
              type: array
            blueGreenDeploymentConfig:
              items:
                properties:
                  deploymentReadyOption:
                    items:
                      properties:
                        actionOnTimeout:
                          type: string
                        waitTimeInMinutes:
                          format: int64
                          type: integer
                      type: object
                    maxItems: 1
                    type: array
                  greenFleetProvisioningOption:
                    items:
                      properties:
                        action:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  terminateBlueInstancesOnDeploymentSuccess:
                    items:
                      properties:
                        action:
                          type: string
                        terminationWaitTimeInMinutes:
                          format: int64
                          type: integer
                      type: object
                    maxItems: 1
                    type: array
                type: object
              maxItems: 1
              type: array
            deploymentConfigName:
              type: string
            deploymentGroupName:
              type: string
            deploymentStyle:
              items:
                properties:
                  deploymentOption:
                    type: string
                  deploymentType:
                    type: string
                type: object
              maxItems: 1
              type: array
            ec2TagFilter:
              items:
                properties:
                  key:
                    type: string
                  type:
                    type: string
                  value:
                    type: string
                type: object
              type: array
            ec2TagSet:
              items:
                properties:
                  ec2TagFilter:
                    items:
                      properties:
                        key:
                          type: string
                        type:
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                type: object
              type: array
            ecsService:
              items:
                properties:
                  clusterName:
                    type: string
                  serviceName:
                    type: string
                required:
                - clusterName
                - serviceName
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            loadBalancerInfo:
              items:
                properties:
                  elbInfo:
                    items:
                      properties:
                        name:
                          type: string
                      type: object
                    type: array
                  targetGroupInfo:
                    items:
                      properties:
                        name:
                          type: string
                      type: object
                    type: array
                  targetGroupPairInfo:
                    items:
                      properties:
                        prodTrafficRoute:
                          items:
                            properties:
                              listenerArns:
                                items:
                                  type: string
                                type: array
                            required:
                            - listenerArns
                            type: object
                          maxItems: 1
                          minItems: 1
                          type: array
                        targetGroup:
                          items:
                            properties:
                              name:
                                type: string
                            required:
                            - name
                            type: object
                          maxItems: 2
                          minItems: 1
                          type: array
                        testTrafficRoute:
                          items:
                            properties:
                              listenerArns:
                                items:
                                  type: string
                                type: array
                            required:
                            - listenerArns
                            type: object
                          maxItems: 1
                          type: array
                      required:
                      - prodTrafficRoute
                      - targetGroup
                      type: object
                    maxItems: 1
                    type: array
                type: object
              maxItems: 1
              type: array
            onPremisesInstanceTagFilter:
              items:
                properties:
                  key:
                    type: string
                  type:
                    type: string
                  value:
                    type: string
                type: object
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            serviceRoleArn:
              type: string
            triggerConfiguration:
              items:
                properties:
                  triggerEvents:
                    items:
                      type: string
                    type: array
                  triggerName:
                    type: string
                  triggerTargetArn:
                    type: string
                required:
                - triggerEvents
                - triggerName
                - triggerTargetArn
                type: object
              type: array
          required:
          - appName
          - deploymentGroupName
          - providerRef
          - serviceRoleArn
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                alarmConfiguration:
                  items:
                    properties:
                      alarms:
                        items:
                          type: string
                        maxItems: 10
                        type: array
                      enabled:
                        type: boolean
                      ignorePollAlarmFailure:
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
                appName:
                  type: string
                autoRollbackConfiguration:
                  items:
                    properties:
                      enabled:
                        type: boolean
                      events:
                        items:
                          type: string
                        type: array
                    type: object
                  maxItems: 1
                  type: array
                autoscalingGroups:
                  items:
                    type: string
                  type: array
                blueGreenDeploymentConfig:
                  items:
                    properties:
                      deploymentReadyOption:
                        items:
                          properties:
                            actionOnTimeout:
                              type: string
                            waitTimeInMinutes:
                              format: int64
                              type: integer
                          type: object
                        maxItems: 1
                        type: array
                      greenFleetProvisioningOption:
                        items:
                          properties:
                            action:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      terminateBlueInstancesOnDeploymentSuccess:
                        items:
                          properties:
                            action:
                              type: string
                            terminationWaitTimeInMinutes:
                              format: int64
                              type: integer
                          type: object
                        maxItems: 1
                        type: array
                    type: object
                  maxItems: 1
                  type: array
                deploymentConfigName:
                  type: string
                deploymentGroupName:
                  type: string
                deploymentStyle:
                  items:
                    properties:
                      deploymentOption:
                        type: string
                      deploymentType:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                ec2TagFilter:
                  items:
                    properties:
                      key:
                        type: string
                      type:
                        type: string
                      value:
                        type: string
                    type: object
                  type: array
                ec2TagSet:
                  items:
                    properties:
                      ec2TagFilter:
                        items:
                          properties:
                            key:
                              type: string
                            type:
                              type: string
                            value:
                              type: string
                          type: object
                        type: array
                    type: object
                  type: array
                ecsService:
                  items:
                    properties:
                      clusterName:
                        type: string
                      serviceName:
                        type: string
                    required:
                    - clusterName
                    - serviceName
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                loadBalancerInfo:
                  items:
                    properties:
                      elbInfo:
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        type: array
                      targetGroupInfo:
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        type: array
                      targetGroupPairInfo:
                        items:
                          properties:
                            prodTrafficRoute:
                              items:
                                properties:
                                  listenerArns:
                                    items:
                                      type: string
                                    type: array
                                required:
                                - listenerArns
                                type: object
                              maxItems: 1
                              minItems: 1
                              type: array
                            targetGroup:
                              items:
                                properties:
                                  name:
                                    type: string
                                required:
                                - name
                                type: object
                              maxItems: 2
                              minItems: 1
                              type: array
                            testTrafficRoute:
                              items:
                                properties:
                                  listenerArns:
                                    items:
                                      type: string
                                    type: array
                                required:
                                - listenerArns
                                type: object
                              maxItems: 1
                              type: array
                          required:
                          - prodTrafficRoute
                          - targetGroup
                          type: object
                        maxItems: 1
                        type: array
                    type: object
                  maxItems: 1
                  type: array
                onPremisesInstanceTagFilter:
                  items:
                    properties:
                      key:
                        type: string
                      type:
                        type: string
                      value:
                        type: string
                    type: object
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                serviceRoleArn:
                  type: string
                triggerConfiguration:
                  items:
                    properties:
                      triggerEvents:
                        items:
                          type: string
                        type: array
                      triggerName:
                        type: string
                      triggerTargetArn:
                        type: string
                    required:
                    - triggerEvents
                    - triggerName
                    - triggerTargetArn
                    type: object
                  type: array
              required:
              - appName
              - deploymentGroupName
              - providerRef
              - serviceRoleArn
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
