apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: apimanagementbackends.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: ApiManagementBackend
    listKind: ApiManagementBackendList
    plural: apimanagementbackends
    singular: apimanagementbackend
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            apiManagementName:
              type: string
            credentials:
              items:
                properties:
                  authorization:
                    items:
                      properties:
                        parameter:
                          type: string
                        scheme:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  certificate:
                    items:
                      type: string
                    type: array
                  header:
                    additionalProperties:
                      type: string
                    type: object
                  query:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              maxItems: 1
              type: array
            description:
              type: string
            id:
              type: string
            name:
              type: string
            protocol:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            proxy:
              items:
                properties:
                  url:
                    type: string
                  username:
                    type: string
                required:
                - url
                - username
                type: object
              maxItems: 1
              type: array
            resourceGroupName:
              type: string
            resourceID:
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            serviceFabricCluster:
              items:
                properties:
                  clientCertificateThumbprint:
                    type: string
                  managementEndpoints:
                    items:
                      type: string
                    type: array
                  maxPartitionResolutionRetries:
                    format: int64
                    type: integer
                  serverCertificateThumbprints:
                    items:
                      type: string
                    type: array
                  serverX509Name:
                    items:
                      properties:
                        issuerCertificateThumbprint:
                          type: string
                        name:
                          type: string
                      required:
                      - issuerCertificateThumbprint
                      - name
                      type: object
                    type: array
                required:
                - clientCertificateThumbprint
                - managementEndpoints
                - maxPartitionResolutionRetries
                type: object
              maxItems: 1
              type: array
            title:
              type: string
            tls:
              items:
                properties:
                  validateCertificateChain:
                    type: boolean
                  validateCertificateName:
                    type: boolean
                type: object
              maxItems: 1
              type: array
            url:
              type: string
          required:
          - apiManagementName
          - name
          - protocol
          - providerRef
          - resourceGroupName
          - url
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                apiManagementName:
                  type: string
                credentials:
                  items:
                    properties:
                      authorization:
                        items:
                          properties:
                            parameter:
                              type: string
                            scheme:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      certificate:
                        items:
                          type: string
                        type: array
                      header:
                        additionalProperties:
                          type: string
                        type: object
                      query:
                        additionalProperties:
                          type: string
                        type: object
                    type: object
                  maxItems: 1
                  type: array
                description:
                  type: string
                id:
                  type: string
                name:
                  type: string
                protocol:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                proxy:
                  items:
                    properties:
                      url:
                        type: string
                      username:
                        type: string
                    required:
                    - url
                    - username
                    type: object
                  maxItems: 1
                  type: array
                resourceGroupName:
                  type: string
                resourceID:
                  type: string
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                serviceFabricCluster:
                  items:
                    properties:
                      clientCertificateThumbprint:
                        type: string
                      managementEndpoints:
                        items:
                          type: string
                        type: array
                      maxPartitionResolutionRetries:
                        format: int64
                        type: integer
                      serverCertificateThumbprints:
                        items:
                          type: string
                        type: array
                      serverX509Name:
                        items:
                          properties:
                            issuerCertificateThumbprint:
                              type: string
                            name:
                              type: string
                          required:
                          - issuerCertificateThumbprint
                          - name
                          type: object
                        type: array
                    required:
                    - clientCertificateThumbprint
                    - managementEndpoints
                    - maxPartitionResolutionRetries
                    type: object
                  maxItems: 1
                  type: array
                title:
                  type: string
                tls:
                  items:
                    properties:
                      validateCertificateChain:
                        type: boolean
                      validateCertificateName:
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
                url:
                  type: string
              required:
              - apiManagementName
              - name
              - protocol
              - providerRef
              - resourceGroupName
              - url
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
