apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: rediscaches.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: RedisCache
    listKind: RedisCacheList
    plural: rediscaches
    singular: rediscache
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            capacity:
              format: int64
              type: integer
            enableNonSSLPort:
              type: boolean
            family:
              type: string
            hostname:
              type: string
            id:
              type: string
            location:
              type: string
            minimumTLSVersion:
              type: string
            name:
              type: string
            patchSchedule:
              items:
                properties:
                  dayOfWeek:
                    type: string
                  startHourUtc:
                    format: int64
                    type: integer
                required:
                - dayOfWeek
                type: object
              type: array
            port:
              format: int64
              type: integer
            privateStaticIPAddress:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            redisConfiguration:
              items:
                properties:
                  aofBackupEnabled:
                    type: boolean
                  enableAuthentication:
                    type: boolean
                  maxclients:
                    format: int64
                    type: integer
                  maxfragmentationmemoryReserved:
                    format: int64
                    type: integer
                  maxmemoryDelta:
                    format: int64
                    type: integer
                  maxmemoryPolicy:
                    type: string
                  maxmemoryReserved:
                    format: int64
                    type: integer
                  notifyKeyspaceEvents:
                    type: string
                  rdbBackupEnabled:
                    type: boolean
                  rdbBackupFrequency:
                    format: int64
                    type: integer
                  rdbBackupMaxSnapshotCount:
                    format: int64
                    type: integer
                type: object
              maxItems: 1
              type: array
            resourceGroupName:
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            shardCount:
              format: int64
              type: integer
            skuName:
              type: string
            sslPort:
              format: int64
              type: integer
            subnetID:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            zones:
              items:
                type: string
              maxItems: 1
              type: array
          required:
          - capacity
          - family
          - location
          - name
          - providerRef
          - resourceGroupName
          - skuName
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                capacity:
                  format: int64
                  type: integer
                enableNonSSLPort:
                  type: boolean
                family:
                  type: string
                hostname:
                  type: string
                id:
                  type: string
                location:
                  type: string
                minimumTLSVersion:
                  type: string
                name:
                  type: string
                patchSchedule:
                  items:
                    properties:
                      dayOfWeek:
                        type: string
                      startHourUtc:
                        format: int64
                        type: integer
                    required:
                    - dayOfWeek
                    type: object
                  type: array
                port:
                  format: int64
                  type: integer
                privateStaticIPAddress:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                redisConfiguration:
                  items:
                    properties:
                      aofBackupEnabled:
                        type: boolean
                      enableAuthentication:
                        type: boolean
                      maxclients:
                        format: int64
                        type: integer
                      maxfragmentationmemoryReserved:
                        format: int64
                        type: integer
                      maxmemoryDelta:
                        format: int64
                        type: integer
                      maxmemoryPolicy:
                        type: string
                      maxmemoryReserved:
                        format: int64
                        type: integer
                      notifyKeyspaceEvents:
                        type: string
                      rdbBackupEnabled:
                        type: boolean
                      rdbBackupFrequency:
                        format: int64
                        type: integer
                      rdbBackupMaxSnapshotCount:
                        format: int64
                        type: integer
                    type: object
                  maxItems: 1
                  type: array
                resourceGroupName:
                  type: string
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                shardCount:
                  format: int64
                  type: integer
                skuName:
                  type: string
                sslPort:
                  format: int64
                  type: integer
                subnetID:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                zones:
                  items:
                    type: string
                  maxItems: 1
                  type: array
              required:
              - capacity
              - family
              - location
              - name
              - providerRef
              - resourceGroupName
              - skuName
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
