apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: containerservices.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: ContainerService
    listKind: ContainerServiceList
    plural: containerservices
    singular: containerservice
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            agentPoolProfile:
              items:
                properties:
                  count:
                    format: int64
                    type: integer
                  dnsPrefix:
                    type: string
                  fqdn:
                    type: string
                  name:
                    type: string
                  vmSize:
                    type: string
                required:
                - dnsPrefix
                - name
                - vmSize
                type: object
              maxItems: 1
              type: array
            diagnosticsProfile:
              items:
                properties:
                  enabled:
                    type: boolean
                  storageURI:
                    type: string
                required:
                - enabled
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            linuxProfile:
              items:
                properties:
                  adminUsername:
                    type: string
                  sshKey:
                    items:
                      properties:
                        keyData:
                          type: string
                      required:
                      - keyData
                      type: object
                    maxItems: 1
                    type: array
                required:
                - adminUsername
                - sshKey
                type: object
              maxItems: 1
              type: array
            location:
              type: string
            masterProfile:
              items:
                properties:
                  count:
                    format: int64
                    type: integer
                  dnsPrefix:
                    type: string
                  fqdn:
                    type: string
                required:
                - dnsPrefix
                type: object
              maxItems: 1
              type: array
            name:
              type: string
            orchestrationPlatform:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            resourceGroupName:
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            servicePrincipal:
              items:
                properties:
                  clientID:
                    type: string
                required:
                - clientID
                type: object
              maxItems: 1
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
          required:
          - agentPoolProfile
          - diagnosticsProfile
          - linuxProfile
          - location
          - masterProfile
          - name
          - orchestrationPlatform
          - providerRef
          - resourceGroupName
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                agentPoolProfile:
                  items:
                    properties:
                      count:
                        format: int64
                        type: integer
                      dnsPrefix:
                        type: string
                      fqdn:
                        type: string
                      name:
                        type: string
                      vmSize:
                        type: string
                    required:
                    - dnsPrefix
                    - name
                    - vmSize
                    type: object
                  maxItems: 1
                  type: array
                diagnosticsProfile:
                  items:
                    properties:
                      enabled:
                        type: boolean
                      storageURI:
                        type: string
                    required:
                    - enabled
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                linuxProfile:
                  items:
                    properties:
                      adminUsername:
                        type: string
                      sshKey:
                        items:
                          properties:
                            keyData:
                              type: string
                          required:
                          - keyData
                          type: object
                        maxItems: 1
                        type: array
                    required:
                    - adminUsername
                    - sshKey
                    type: object
                  maxItems: 1
                  type: array
                location:
                  type: string
                masterProfile:
                  items:
                    properties:
                      count:
                        format: int64
                        type: integer
                      dnsPrefix:
                        type: string
                      fqdn:
                        type: string
                    required:
                    - dnsPrefix
                    type: object
                  maxItems: 1
                  type: array
                name:
                  type: string
                orchestrationPlatform:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                resourceGroupName:
                  type: string
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                servicePrincipal:
                  items:
                    properties:
                      clientID:
                        type: string
                    required:
                    - clientID
                    type: object
                  maxItems: 1
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
              required:
              - agentPoolProfile
              - diagnosticsProfile
              - linuxProfile
              - location
              - masterProfile
              - name
              - orchestrationPlatform
              - providerRef
              - resourceGroupName
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
