apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: cdnendpoints.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: CdnEndpoint
    listKind: CdnEndpointList
    plural: cdnendpoints
    singular: cdnendpoint
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            contentTypesToCompress:
              items:
                type: string
              type: array
            geoFilter:
              items:
                properties:
                  action:
                    type: string
                  countryCodes:
                    items:
                      type: string
                    type: array
                  relativePath:
                    type: string
                required:
                - action
                - countryCodes
                - relativePath
                type: object
              type: array
            hostName:
              type: string
            id:
              type: string
            isCompressionEnabled:
              type: boolean
            isHTTPAllowed:
              type: boolean
            isHTTPSAllowed:
              type: boolean
            location:
              type: string
            name:
              type: string
            optimizationType:
              type: string
            origin:
              items:
                properties:
                  hostName:
                    type: string
                  httpPort:
                    format: int64
                    type: integer
                  httpsPort:
                    format: int64
                    type: integer
                  name:
                    type: string
                required:
                - hostName
                - name
                type: object
              type: array
            originHostHeader:
              type: string
            originPath:
              type: string
            probePath:
              type: string
            profileName:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            querystringCachingBehaviour:
              type: string
            resourceGroupName:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
          required:
          - location
          - name
          - origin
          - profileName
          - providerRef
          - resourceGroupName
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                contentTypesToCompress:
                  items:
                    type: string
                  type: array
                geoFilter:
                  items:
                    properties:
                      action:
                        type: string
                      countryCodes:
                        items:
                          type: string
                        type: array
                      relativePath:
                        type: string
                    required:
                    - action
                    - countryCodes
                    - relativePath
                    type: object
                  type: array
                hostName:
                  type: string
                id:
                  type: string
                isCompressionEnabled:
                  type: boolean
                isHTTPAllowed:
                  type: boolean
                isHTTPSAllowed:
                  type: boolean
                location:
                  type: string
                name:
                  type: string
                optimizationType:
                  type: string
                origin:
                  items:
                    properties:
                      hostName:
                        type: string
                      httpPort:
                        format: int64
                        type: integer
                      httpsPort:
                        format: int64
                        type: integer
                      name:
                        type: string
                    required:
                    - hostName
                    - name
                    type: object
                  type: array
                originHostHeader:
                  type: string
                originPath:
                  type: string
                probePath:
                  type: string
                profileName:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                querystringCachingBehaviour:
                  type: string
                resourceGroupName:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
              required:
              - location
              - name
              - origin
              - profileName
              - providerRef
              - resourceGroupName
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
