apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: storagemanagementpolicies.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: StorageManagementPolicy
    listKind: StorageManagementPolicyList
    plural: storagemanagementpolicies
    singular: storagemanagementpolicy
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            id:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            rule:
              items:
                properties:
                  actions:
                    items:
                      properties:
                        baseBlob:
                          items:
                            properties:
                              deleteAfterDaysSinceModificationGreaterThan:
                                format: int64
                                type: integer
                              tierToArchiveAfterDaysSinceModificationGreaterThan:
                                format: int64
                                type: integer
                              tierToCoolAfterDaysSinceModificationGreaterThan:
                                format: int64
                                type: integer
                            type: object
                          maxItems: 1
                          type: array
                        snapshot:
                          items:
                            properties:
                              deleteAfterDaysSinceCreationGreaterThan:
                                format: int64
                                type: integer
                            type: object
                          maxItems: 1
                          type: array
                      type: object
                    maxItems: 1
                    type: array
                  enabled:
                    type: boolean
                  filters:
                    items:
                      properties:
                        blobTypes:
                          items:
                            type: string
                          type: array
                        prefixMatch:
                          items:
                            type: string
                          type: array
                      type: object
                    maxItems: 1
                    type: array
                  name:
                    type: string
                required:
                - actions
                - enabled
                - name
                type: object
              minItems: 1
              type: array
            storageAccountID:
              type: string
          required:
          - providerRef
          - storageAccountID
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                id:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                rule:
                  items:
                    properties:
                      actions:
                        items:
                          properties:
                            baseBlob:
                              items:
                                properties:
                                  deleteAfterDaysSinceModificationGreaterThan:
                                    format: int64
                                    type: integer
                                  tierToArchiveAfterDaysSinceModificationGreaterThan:
                                    format: int64
                                    type: integer
                                  tierToCoolAfterDaysSinceModificationGreaterThan:
                                    format: int64
                                    type: integer
                                type: object
                              maxItems: 1
                              type: array
                            snapshot:
                              items:
                                properties:
                                  deleteAfterDaysSinceCreationGreaterThan:
                                    format: int64
                                    type: integer
                                type: object
                              maxItems: 1
                              type: array
                          type: object
                        maxItems: 1
                        type: array
                      enabled:
                        type: boolean
                      filters:
                        items:
                          properties:
                            blobTypes:
                              items:
                                type: string
                              type: array
                            prefixMatch:
                              items:
                                type: string
                              type: array
                          type: object
                        maxItems: 1
                        type: array
                      name:
                        type: string
                    required:
                    - actions
                    - enabled
                    - name
                    type: object
                  minItems: 1
                  type: array
                storageAccountID:
                  type: string
              required:
              - providerRef
              - storageAccountID
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
