apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: recoveryservicesprotectionpolicyvms.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: RecoveryServicesProtectionPolicyVm
    listKind: RecoveryServicesProtectionPolicyVmList
    plural: recoveryservicesprotectionpolicyvms
    singular: recoveryservicesprotectionpolicyvm
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            backup:
              items:
                properties:
                  frequency:
                    type: string
                  time:
                    type: string
                  weekdays:
                    items:
                      type: string
                    type: array
                required:
                - frequency
                - time
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            recoveryVaultName:
              type: string
            resourceGroupName:
              type: string
            retentionDaily:
              items:
                properties:
                  count:
                    format: int64
                    type: integer
                required:
                - count
                type: object
              maxItems: 1
              type: array
            retentionMonthly:
              items:
                properties:
                  count:
                    format: int64
                    type: integer
                  weekdays:
                    items:
                      type: string
                    type: array
                  weeks:
                    items:
                      type: string
                    type: array
                required:
                - count
                - weekdays
                - weeks
                type: object
              maxItems: 1
              type: array
            retentionWeekly:
              items:
                properties:
                  count:
                    format: int64
                    type: integer
                  weekdays:
                    items:
                      type: string
                    type: array
                required:
                - count
                - weekdays
                type: object
              maxItems: 1
              type: array
            retentionYearly:
              items:
                properties:
                  count:
                    format: int64
                    type: integer
                  months:
                    items:
                      type: string
                    type: array
                  weekdays:
                    items:
                      type: string
                    type: array
                  weeks:
                    items:
                      type: string
                    type: array
                required:
                - count
                - months
                - weekdays
                - weeks
                type: object
              maxItems: 1
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
            timezone:
              type: string
          required:
          - backup
          - name
          - providerRef
          - recoveryVaultName
          - resourceGroupName
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                backup:
                  items:
                    properties:
                      frequency:
                        type: string
                      time:
                        type: string
                      weekdays:
                        items:
                          type: string
                        type: array
                    required:
                    - frequency
                    - time
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                recoveryVaultName:
                  type: string
                resourceGroupName:
                  type: string
                retentionDaily:
                  items:
                    properties:
                      count:
                        format: int64
                        type: integer
                    required:
                    - count
                    type: object
                  maxItems: 1
                  type: array
                retentionMonthly:
                  items:
                    properties:
                      count:
                        format: int64
                        type: integer
                      weekdays:
                        items:
                          type: string
                        type: array
                      weeks:
                        items:
                          type: string
                        type: array
                    required:
                    - count
                    - weekdays
                    - weeks
                    type: object
                  maxItems: 1
                  type: array
                retentionWeekly:
                  items:
                    properties:
                      count:
                        format: int64
                        type: integer
                      weekdays:
                        items:
                          type: string
                        type: array
                    required:
                    - count
                    - weekdays
                    type: object
                  maxItems: 1
                  type: array
                retentionYearly:
                  items:
                    properties:
                      count:
                        format: int64
                        type: integer
                      months:
                        items:
                          type: string
                        type: array
                      weekdays:
                        items:
                          type: string
                        type: array
                      weeks:
                        items:
                          type: string
                        type: array
                    required:
                    - count
                    - months
                    - weekdays
                    - weeks
                    type: object
                  maxItems: 1
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
                timezone:
                  type: string
              required:
              - backup
              - name
              - providerRef
              - recoveryVaultName
              - resourceGroupName
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
