apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: cosmosdbaccounts.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: CosmosdbAccount
    listKind: CosmosdbAccountList
    plural: cosmosdbaccounts
    singular: cosmosdbaccount
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            capabilities:
              items:
                properties:
                  name:
                    type: string
                required:
                - name
                type: object
              type: array
            consistencyPolicy:
              items:
                properties:
                  consistencyLevel:
                    type: string
                  maxIntervalInSeconds:
                    format: int64
                    type: integer
                  maxStalenessPrefix:
                    format: int64
                    type: integer
                required:
                - consistencyLevel
                type: object
              maxItems: 1
              type: array
            enableAutomaticFailover:
              type: boolean
            enableMultipleWriteLocations:
              type: boolean
            endpoint:
              type: string
            failoverPolicy:
              description: Deprecated
              items:
                properties:
                  ID:
                    type: string
                  location:
                    type: string
                  priority:
                    format: int64
                    type: integer
                required:
                - location
                - priority
                type: object
              type: array
            geoLocation:
              items:
                properties:
                  ID:
                    type: string
                  failoverPriority:
                    format: int64
                    type: integer
                  location:
                    type: string
                  prefix:
                    type: string
                required:
                - failoverPriority
                - location
                type: object
              type: array
            id:
              type: string
            ipRangeFilter:
              type: string
            isVirtualNetworkFilterEnabled:
              type: boolean
            kind:
              type: string
            location:
              type: string
            name:
              type: string
            offerType:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            readEndpoints:
              items:
                type: string
              type: array
            resourceGroupName:
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            tags:
              additionalProperties:
                type: string
              type: object
            virtualNetworkRule:
              items:
                properties:
                  ID:
                    type: string
                required:
                - ID
                type: object
              type: array
            writeEndpoints:
              items:
                type: string
              type: array
          required:
          - location
          - name
          - offerType
          - providerRef
          - resourceGroupName
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                capabilities:
                  items:
                    properties:
                      name:
                        type: string
                    required:
                    - name
                    type: object
                  type: array
                consistencyPolicy:
                  items:
                    properties:
                      consistencyLevel:
                        type: string
                      maxIntervalInSeconds:
                        format: int64
                        type: integer
                      maxStalenessPrefix:
                        format: int64
                        type: integer
                    required:
                    - consistencyLevel
                    type: object
                  maxItems: 1
                  type: array
                enableAutomaticFailover:
                  type: boolean
                enableMultipleWriteLocations:
                  type: boolean
                endpoint:
                  type: string
                failoverPolicy:
                  description: Deprecated
                  items:
                    properties:
                      ID:
                        type: string
                      location:
                        type: string
                      priority:
                        format: int64
                        type: integer
                    required:
                    - location
                    - priority
                    type: object
                  type: array
                geoLocation:
                  items:
                    properties:
                      ID:
                        type: string
                      failoverPriority:
                        format: int64
                        type: integer
                      location:
                        type: string
                      prefix:
                        type: string
                    required:
                    - failoverPriority
                    - location
                    type: object
                  type: array
                id:
                  type: string
                ipRangeFilter:
                  type: string
                isVirtualNetworkFilterEnabled:
                  type: boolean
                kind:
                  type: string
                location:
                  type: string
                name:
                  type: string
                offerType:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                readEndpoints:
                  items:
                    type: string
                  type: array
                resourceGroupName:
                  type: string
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                tags:
                  additionalProperties:
                    type: string
                  type: object
                virtualNetworkRule:
                  items:
                    properties:
                      ID:
                        type: string
                    required:
                    - ID
                    type: object
                  type: array
                writeEndpoints:
                  items:
                    type: string
                  type: array
              required:
              - location
              - name
              - offerType
              - providerRef
              - resourceGroupName
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
