apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: apimanagements.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: ApiManagement
    listKind: ApiManagementList
    plural: apimanagements
    singular: apimanagement
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            additionalLocation:
              items:
                properties:
                  gatewayRegionalURL:
                    type: string
                  location:
                    type: string
                  publicIPAddresses:
                    items:
                      type: string
                    type: array
                required:
                - location
                type: object
              maxItems: 1
              type: array
            certificate:
              items:
                properties:
                  storeName:
                    type: string
                required:
                - storeName
                type: object
              maxItems: 10
              type: array
            gatewayRegionalURL:
              type: string
            gatewayURL:
              type: string
            hostnameConfiguration:
              items:
                properties:
                  management:
                    items:
                      properties:
                        hostName:
                          type: string
                        keyVaultID:
                          type: string
                        negotiateClientCertificate:
                          type: boolean
                      required:
                      - hostName
                      type: object
                    type: array
                  portal:
                    items:
                      properties:
                        hostName:
                          type: string
                        keyVaultID:
                          type: string
                        negotiateClientCertificate:
                          type: boolean
                      required:
                      - hostName
                      type: object
                    type: array
                  proxy:
                    items:
                      properties:
                        defaultSSLBinding:
                          type: boolean
                        hostName:
                          type: string
                        keyVaultID:
                          type: string
                        negotiateClientCertificate:
                          type: boolean
                      required:
                      - hostName
                      type: object
                    type: array
                  scm:
                    items:
                      properties:
                        hostName:
                          type: string
                        keyVaultID:
                          type: string
                        negotiateClientCertificate:
                          type: boolean
                      required:
                      - hostName
                      type: object
                    type: array
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            identity:
              items:
                properties:
                  principalID:
                    type: string
                  tenantID:
                    type: string
                  type:
                    type: string
                required:
                - type
                type: object
              maxItems: 1
              type: array
            location:
              type: string
            managementAPIURL:
              type: string
            name:
              type: string
            notificationSenderEmail:
              type: string
            policy:
              items:
                properties:
                  xmlContent:
                    type: string
                  xmlLink:
                    type: string
                type: object
              maxItems: 1
              type: array
            portalURL:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            publicIPAddresses:
              items:
                type: string
              type: array
            publisherEmail:
              type: string
            publisherName:
              type: string
            resourceGroupName:
              type: string
            scmURL:
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            security:
              items:
                properties:
                  disableBackendSSL30:
                    type: boolean
                  disableBackendTLS10:
                    type: boolean
                  disableBackendTLS11:
                    type: boolean
                  disableFrontendSSL30:
                    type: boolean
                  disableFrontendTLS10:
                    type: boolean
                  disableFrontendTLS11:
                    type: boolean
                  disableTripleDESChipers:
                    description: Deprecated
                    type: boolean
                  disableTripleDESCiphers:
                    type: boolean
                type: object
              maxItems: 1
              type: array
            signIn:
              items:
                properties:
                  enabled:
                    type: boolean
                required:
                - enabled
                type: object
              maxItems: 1
              type: array
            signUp:
              items:
                properties:
                  enabled:
                    type: boolean
                  termsOfService:
                    items:
                      properties:
                        consentRequired:
                          type: boolean
                        enabled:
                          type: boolean
                        text:
                          type: string
                      required:
                      - consentRequired
                      - enabled
                      type: object
                    maxItems: 1
                    type: array
                required:
                - enabled
                - termsOfService
                type: object
              maxItems: 1
              type: array
            sku:
              items:
                properties:
                  capacity:
                    format: int64
                    type: integer
                  name:
                    type: string
                required:
                - capacity
                - name
                type: object
              maxItems: 1
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
          required:
          - location
          - name
          - providerRef
          - publisherEmail
          - publisherName
          - resourceGroupName
          - sku
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                additionalLocation:
                  items:
                    properties:
                      gatewayRegionalURL:
                        type: string
                      location:
                        type: string
                      publicIPAddresses:
                        items:
                          type: string
                        type: array
                    required:
                    - location
                    type: object
                  maxItems: 1
                  type: array
                certificate:
                  items:
                    properties:
                      storeName:
                        type: string
                    required:
                    - storeName
                    type: object
                  maxItems: 10
                  type: array
                gatewayRegionalURL:
                  type: string
                gatewayURL:
                  type: string
                hostnameConfiguration:
                  items:
                    properties:
                      management:
                        items:
                          properties:
                            hostName:
                              type: string
                            keyVaultID:
                              type: string
                            negotiateClientCertificate:
                              type: boolean
                          required:
                          - hostName
                          type: object
                        type: array
                      portal:
                        items:
                          properties:
                            hostName:
                              type: string
                            keyVaultID:
                              type: string
                            negotiateClientCertificate:
                              type: boolean
                          required:
                          - hostName
                          type: object
                        type: array
                      proxy:
                        items:
                          properties:
                            defaultSSLBinding:
                              type: boolean
                            hostName:
                              type: string
                            keyVaultID:
                              type: string
                            negotiateClientCertificate:
                              type: boolean
                          required:
                          - hostName
                          type: object
                        type: array
                      scm:
                        items:
                          properties:
                            hostName:
                              type: string
                            keyVaultID:
                              type: string
                            negotiateClientCertificate:
                              type: boolean
                          required:
                          - hostName
                          type: object
                        type: array
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                identity:
                  items:
                    properties:
                      principalID:
                        type: string
                      tenantID:
                        type: string
                      type:
                        type: string
                    required:
                    - type
                    type: object
                  maxItems: 1
                  type: array
                location:
                  type: string
                managementAPIURL:
                  type: string
                name:
                  type: string
                notificationSenderEmail:
                  type: string
                policy:
                  items:
                    properties:
                      xmlContent:
                        type: string
                      xmlLink:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                portalURL:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                publicIPAddresses:
                  items:
                    type: string
                  type: array
                publisherEmail:
                  type: string
                publisherName:
                  type: string
                resourceGroupName:
                  type: string
                scmURL:
                  type: string
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                security:
                  items:
                    properties:
                      disableBackendSSL30:
                        type: boolean
                      disableBackendTLS10:
                        type: boolean
                      disableBackendTLS11:
                        type: boolean
                      disableFrontendSSL30:
                        type: boolean
                      disableFrontendTLS10:
                        type: boolean
                      disableFrontendTLS11:
                        type: boolean
                      disableTripleDESChipers:
                        description: Deprecated
                        type: boolean
                      disableTripleDESCiphers:
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
                signIn:
                  items:
                    properties:
                      enabled:
                        type: boolean
                    required:
                    - enabled
                    type: object
                  maxItems: 1
                  type: array
                signUp:
                  items:
                    properties:
                      enabled:
                        type: boolean
                      termsOfService:
                        items:
                          properties:
                            consentRequired:
                              type: boolean
                            enabled:
                              type: boolean
                            text:
                              type: string
                          required:
                          - consentRequired
                          - enabled
                          type: object
                        maxItems: 1
                        type: array
                    required:
                    - enabled
                    - termsOfService
                    type: object
                  maxItems: 1
                  type: array
                sku:
                  items:
                    properties:
                      capacity:
                        format: int64
                        type: integer
                      name:
                        type: string
                    required:
                    - capacity
                    - name
                    type: object
                  maxItems: 1
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
              required:
              - location
              - name
              - providerRef
              - publisherEmail
              - publisherName
              - resourceGroupName
              - sku
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
