apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: sqldatabases.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: SqlDatabase
    listKind: SqlDatabaseList
    plural: sqldatabases
    singular: sqldatabase
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            collation:
              type: string
            createMode:
              type: string
            creationDate:
              type: string
            defaultSecondaryLocation:
              type: string
            edition:
              type: string
            elasticPoolName:
              type: string
            encryption:
              type: string
            id:
              type: string
            import:
              items:
                properties:
                  administratorLogin:
                    type: string
                  authenticationType:
                    type: string
                  operationMode:
                    type: string
                  storageKeyType:
                    type: string
                  storageURI:
                    type: string
                required:
                - administratorLogin
                - authenticationType
                - storageKeyType
                - storageURI
                type: object
              maxItems: 1
              type: array
            location:
              type: string
            maxSizeBytes:
              type: string
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            readScale:
              type: boolean
            requestedServiceObjectiveID:
              type: string
            requestedServiceObjectiveName:
              type: string
            resourceGroupName:
              type: string
            restorePointInTime:
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            serverName:
              type: string
            sourceDatabaseDeletionDate:
              type: string
            sourceDatabaseID:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            threatDetectionPolicy:
              items:
                properties:
                  disabledAlerts:
                    items:
                      type: string
                    type: array
                  emailAccountAdmins:
                    type: string
                  emailAddresses:
                    items:
                      type: string
                    type: array
                  retentionDays:
                    format: int64
                    type: integer
                  state:
                    type: string
                  storageEndpoint:
                    type: string
                  useServerDefault:
                    type: string
                type: object
              maxItems: 1
              type: array
          required:
          - location
          - name
          - providerRef
          - resourceGroupName
          - serverName
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                collation:
                  type: string
                createMode:
                  type: string
                creationDate:
                  type: string
                defaultSecondaryLocation:
                  type: string
                edition:
                  type: string
                elasticPoolName:
                  type: string
                encryption:
                  type: string
                id:
                  type: string
                import:
                  items:
                    properties:
                      administratorLogin:
                        type: string
                      authenticationType:
                        type: string
                      operationMode:
                        type: string
                      storageKeyType:
                        type: string
                      storageURI:
                        type: string
                    required:
                    - administratorLogin
                    - authenticationType
                    - storageKeyType
                    - storageURI
                    type: object
                  maxItems: 1
                  type: array
                location:
                  type: string
                maxSizeBytes:
                  type: string
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                readScale:
                  type: boolean
                requestedServiceObjectiveID:
                  type: string
                requestedServiceObjectiveName:
                  type: string
                resourceGroupName:
                  type: string
                restorePointInTime:
                  type: string
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                serverName:
                  type: string
                sourceDatabaseDeletionDate:
                  type: string
                sourceDatabaseID:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                threatDetectionPolicy:
                  items:
                    properties:
                      disabledAlerts:
                        items:
                          type: string
                        type: array
                      emailAccountAdmins:
                        type: string
                      emailAddresses:
                        items:
                          type: string
                        type: array
                      retentionDays:
                        format: int64
                        type: integer
                      state:
                        type: string
                      storageEndpoint:
                        type: string
                      useServerDefault:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
              required:
              - location
              - name
              - providerRef
              - resourceGroupName
              - serverName
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
