apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: batchpools.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: BatchPool
    listKind: BatchPoolList
    plural: batchpools
    singular: batchpool
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            accountName:
              type: string
            autoScale:
              items:
                properties:
                  evaluationInterval:
                    type: string
                  formula:
                    type: string
                required:
                - formula
                type: object
              maxItems: 1
              type: array
            certificate:
              items:
                properties:
                  ID:
                    type: string
                  storeLocation:
                    type: string
                  storeName:
                    type: string
                  visibility:
                    items:
                      type: string
                    type: array
                required:
                - ID
                - storeLocation
                type: object
              type: array
            containerConfiguration:
              items:
                properties:
                  containerRegistries:
                    items:
                      properties:
                        registryServer:
                          type: string
                        userName:
                          type: string
                      required:
                      - registryServer
                      - userName
                      type: object
                    type: array
                  type:
                    type: string
                type: object
              maxItems: 1
              minItems: 1
              type: array
            displayName:
              type: string
            fixedScale:
              items:
                properties:
                  resizeTimeout:
                    type: string
                  targetDedicatedNodes:
                    format: int64
                    type: integer
                  targetLowPriorityNodes:
                    format: int64
                    type: integer
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            maxTasksPerNode:
              format: int64
              type: integer
            metadata:
              additionalProperties:
                type: string
              type: object
            name:
              type: string
            networkConfiguration:
              items:
                properties:
                  endpointConfiguration:
                    items:
                      properties:
                        backendPort:
                          format: int64
                          type: integer
                        frontendPortRange:
                          type: string
                        name:
                          type: string
                        networkSecurityGroupRules:
                          items:
                            properties:
                              access:
                                type: string
                              priority:
                                format: int64
                                type: integer
                              sourceAddressPrefix:
                                type: string
                            required:
                            - access
                            - priority
                            - sourceAddressPrefix
                            type: object
                          type: array
                        protocol:
                          type: string
                      required:
                      - backendPort
                      - frontendPortRange
                      - name
                      - protocol
                      type: object
                    type: array
                  subnetID:
                    type: string
                required:
                - subnetID
                type: object
              maxItems: 1
              type: array
            nodeAgentSkuID:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            resourceGroupName:
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            startTask:
              items:
                properties:
                  commandLine:
                    type: string
                  environment:
                    additionalProperties:
                      type: string
                    type: object
                  maxTaskRetryCount:
                    format: int64
                    type: integer
                  resourceFile:
                    items:
                      properties:
                        autoStorageContainerName:
                          type: string
                        blobPrefix:
                          type: string
                        fileMode:
                          type: string
                        filePath:
                          type: string
                        httpURL:
                          type: string
                        storageContainerURL:
                          type: string
                      type: object
                    type: array
                  userIdentity:
                    items:
                      properties:
                        autoUser:
                          items:
                            properties:
                              elevationLevel:
                                type: string
                              scope:
                                type: string
                            type: object
                          maxItems: 1
                          type: array
                        userName:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  waitForSuccess:
                    type: boolean
                required:
                - commandLine
                - userIdentity
                type: object
              maxItems: 1
              type: array
            stopPendingResizeOperation:
              type: boolean
            storageImageReference:
              items:
                properties:
                  ID:
                    type: string
                  offer:
                    type: string
                  publisher:
                    type: string
                  sku:
                    type: string
                  version:
                    type: string
                type: object
              maxItems: 1
              type: array
            vmSize:
              type: string
          required:
          - accountName
          - name
          - nodeAgentSkuID
          - providerRef
          - resourceGroupName
          - storageImageReference
          - vmSize
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                accountName:
                  type: string
                autoScale:
                  items:
                    properties:
                      evaluationInterval:
                        type: string
                      formula:
                        type: string
                    required:
                    - formula
                    type: object
                  maxItems: 1
                  type: array
                certificate:
                  items:
                    properties:
                      ID:
                        type: string
                      storeLocation:
                        type: string
                      storeName:
                        type: string
                      visibility:
                        items:
                          type: string
                        type: array
                    required:
                    - ID
                    - storeLocation
                    type: object
                  type: array
                containerConfiguration:
                  items:
                    properties:
                      containerRegistries:
                        items:
                          properties:
                            registryServer:
                              type: string
                            userName:
                              type: string
                          required:
                          - registryServer
                          - userName
                          type: object
                        type: array
                      type:
                        type: string
                    type: object
                  maxItems: 1
                  minItems: 1
                  type: array
                displayName:
                  type: string
                fixedScale:
                  items:
                    properties:
                      resizeTimeout:
                        type: string
                      targetDedicatedNodes:
                        format: int64
                        type: integer
                      targetLowPriorityNodes:
                        format: int64
                        type: integer
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                maxTasksPerNode:
                  format: int64
                  type: integer
                metadata:
                  additionalProperties:
                    type: string
                  type: object
                name:
                  type: string
                networkConfiguration:
                  items:
                    properties:
                      endpointConfiguration:
                        items:
                          properties:
                            backendPort:
                              format: int64
                              type: integer
                            frontendPortRange:
                              type: string
                            name:
                              type: string
                            networkSecurityGroupRules:
                              items:
                                properties:
                                  access:
                                    type: string
                                  priority:
                                    format: int64
                                    type: integer
                                  sourceAddressPrefix:
                                    type: string
                                required:
                                - access
                                - priority
                                - sourceAddressPrefix
                                type: object
                              type: array
                            protocol:
                              type: string
                          required:
                          - backendPort
                          - frontendPortRange
                          - name
                          - protocol
                          type: object
                        type: array
                      subnetID:
                        type: string
                    required:
                    - subnetID
                    type: object
                  maxItems: 1
                  type: array
                nodeAgentSkuID:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                resourceGroupName:
                  type: string
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                startTask:
                  items:
                    properties:
                      commandLine:
                        type: string
                      environment:
                        additionalProperties:
                          type: string
                        type: object
                      maxTaskRetryCount:
                        format: int64
                        type: integer
                      resourceFile:
                        items:
                          properties:
                            autoStorageContainerName:
                              type: string
                            blobPrefix:
                              type: string
                            fileMode:
                              type: string
                            filePath:
                              type: string
                            httpURL:
                              type: string
                            storageContainerURL:
                              type: string
                          type: object
                        type: array
                      userIdentity:
                        items:
                          properties:
                            autoUser:
                              items:
                                properties:
                                  elevationLevel:
                                    type: string
                                  scope:
                                    type: string
                                type: object
                              maxItems: 1
                              type: array
                            userName:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      waitForSuccess:
                        type: boolean
                    required:
                    - commandLine
                    - userIdentity
                    type: object
                  maxItems: 1
                  type: array
                stopPendingResizeOperation:
                  type: boolean
                storageImageReference:
                  items:
                    properties:
                      ID:
                        type: string
                      offer:
                        type: string
                      publisher:
                        type: string
                      sku:
                        type: string
                      version:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                vmSize:
                  type: string
              required:
              - accountName
              - name
              - nodeAgentSkuID
              - providerRef
              - resourceGroupName
              - storageImageReference
              - vmSize
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
