apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: mssqlelasticpools.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: MssqlElasticpool
    listKind: MssqlElasticpoolList
    plural: mssqlelasticpools
    singular: mssqlelasticpool
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            elasticPoolProperties:
              description: Deprecated
              items:
                properties:
                  creationDate:
                    description: Deprecated
                    type: string
                  licenseType:
                    description: Deprecated
                    type: string
                  maxSizeBytes:
                    description: Deprecated
                    format: int64
                    type: integer
                  state:
                    description: Deprecated
                    type: string
                  zoneRedundant:
                    description: Deprecated
                    type: boolean
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            location:
              type: string
            maxSizeBytes:
              format: int64
              type: integer
            maxSizeGb:
              format: float
              type: number
            name:
              type: string
            perDatabaseSettings:
              items:
                properties:
                  maxCapacity:
                    format: float
                    type: number
                  minCapacity:
                    format: float
                    type: number
                required:
                - maxCapacity
                - minCapacity
                type: object
              maxItems: 1
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            resourceGroupName:
              type: string
            serverName:
              type: string
            sku:
              items:
                properties:
                  capacity:
                    format: int64
                    type: integer
                  family:
                    type: string
                  name:
                    type: string
                  tier:
                    type: string
                required:
                - capacity
                - name
                - tier
                type: object
              maxItems: 1
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
            zoneRedundant:
              type: boolean
          required:
          - location
          - name
          - perDatabaseSettings
          - providerRef
          - resourceGroupName
          - serverName
          - sku
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                elasticPoolProperties:
                  description: Deprecated
                  items:
                    properties:
                      creationDate:
                        description: Deprecated
                        type: string
                      licenseType:
                        description: Deprecated
                        type: string
                      maxSizeBytes:
                        description: Deprecated
                        format: int64
                        type: integer
                      state:
                        description: Deprecated
                        type: string
                      zoneRedundant:
                        description: Deprecated
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                location:
                  type: string
                maxSizeBytes:
                  format: int64
                  type: integer
                maxSizeGb:
                  format: float
                  type: number
                name:
                  type: string
                perDatabaseSettings:
                  items:
                    properties:
                      maxCapacity:
                        format: float
                        type: number
                      minCapacity:
                        format: float
                        type: number
                    required:
                    - maxCapacity
                    - minCapacity
                    type: object
                  maxItems: 1
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                resourceGroupName:
                  type: string
                serverName:
                  type: string
                sku:
                  items:
                    properties:
                      capacity:
                        format: int64
                        type: integer
                      family:
                        type: string
                      name:
                        type: string
                      tier:
                        type: string
                    required:
                    - capacity
                    - name
                    - tier
                    type: object
                  maxItems: 1
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
                zoneRedundant:
                  type: boolean
              required:
              - location
              - name
              - perDatabaseSettings
              - providerRef
              - resourceGroupName
              - serverName
              - sku
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
