apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: manageddisks.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: ManagedDisk
    listKind: ManagedDiskList
    plural: manageddisks
    singular: manageddisk
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            createOption:
              type: string
            diskEncryptionSetID:
              type: string
            diskIopsReadWrite:
              format: int64
              type: integer
            diskMbpsReadWrite:
              format: int64
              type: integer
            diskSizeGb:
              format: int64
              type: integer
            encryptionSettings:
              items:
                properties:
                  diskEncryptionKey:
                    items:
                      properties:
                        secretURL:
                          type: string
                        sourceVaultID:
                          type: string
                      required:
                      - secretURL
                      - sourceVaultID
                      type: object
                    maxItems: 1
                    type: array
                  enabled:
                    type: boolean
                  keyEncryptionKey:
                    items:
                      properties:
                        keyURL:
                          type: string
                        sourceVaultID:
                          type: string
                      required:
                      - keyURL
                      - sourceVaultID
                      type: object
                    maxItems: 1
                    type: array
                required:
                - enabled
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            imageReferenceID:
              type: string
            location:
              type: string
            name:
              type: string
            osType:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            resourceGroupName:
              type: string
            sourceResourceID:
              type: string
            sourceURI:
              type: string
            storageAccountID:
              type: string
            storageAccountType:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            zones:
              items:
                type: string
              maxItems: 1
              type: array
          required:
          - createOption
          - location
          - name
          - providerRef
          - resourceGroupName
          - storageAccountType
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                createOption:
                  type: string
                diskEncryptionSetID:
                  type: string
                diskIopsReadWrite:
                  format: int64
                  type: integer
                diskMbpsReadWrite:
                  format: int64
                  type: integer
                diskSizeGb:
                  format: int64
                  type: integer
                encryptionSettings:
                  items:
                    properties:
                      diskEncryptionKey:
                        items:
                          properties:
                            secretURL:
                              type: string
                            sourceVaultID:
                              type: string
                          required:
                          - secretURL
                          - sourceVaultID
                          type: object
                        maxItems: 1
                        type: array
                      enabled:
                        type: boolean
                      keyEncryptionKey:
                        items:
                          properties:
                            keyURL:
                              type: string
                            sourceVaultID:
                              type: string
                          required:
                          - keyURL
                          - sourceVaultID
                          type: object
                        maxItems: 1
                        type: array
                    required:
                    - enabled
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                imageReferenceID:
                  type: string
                location:
                  type: string
                name:
                  type: string
                osType:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                resourceGroupName:
                  type: string
                sourceResourceID:
                  type: string
                sourceURI:
                  type: string
                storageAccountID:
                  type: string
                storageAccountType:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                zones:
                  items:
                    type: string
                  maxItems: 1
                  type: array
              required:
              - createOption
              - location
              - name
              - providerRef
              - resourceGroupName
              - storageAccountType
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
