apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: keyvaultcertificates.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: KeyVaultCertificate
    listKind: KeyVaultCertificateList
    plural: keyvaultcertificates
    singular: keyvaultcertificate
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            certificate:
              items:
                type: object
              maxItems: 1
              type: array
            certificateData:
              type: string
            certificatePolicy:
              items:
                properties:
                  issuerParameters:
                    items:
                      properties:
                        name:
                          type: string
                      required:
                      - name
                      type: object
                    maxItems: 1
                    type: array
                  keyProperties:
                    items:
                      properties:
                        exportable:
                          type: boolean
                        keySize:
                          format: int64
                          type: integer
                        keyType:
                          type: string
                        reuseKey:
                          type: boolean
                      required:
                      - exportable
                      - keySize
                      - keyType
                      - reuseKey
                      type: object
                    maxItems: 1
                    type: array
                  lifetimeAction:
                    items:
                      properties:
                        action:
                          items:
                            properties:
                              actionType:
                                type: string
                            required:
                            - actionType
                            type: object
                          maxItems: 1
                          type: array
                        trigger:
                          items:
                            properties:
                              daysBeforeExpiry:
                                format: int64
                                type: integer
                              lifetimePercentage:
                                format: int64
                                type: integer
                            type: object
                          maxItems: 1
                          type: array
                      required:
                      - action
                      - trigger
                      type: object
                    type: array
                  secretProperties:
                    items:
                      properties:
                        contentType:
                          type: string
                      required:
                      - contentType
                      type: object
                    maxItems: 1
                    type: array
                  x509CertificateProperties:
                    items:
                      properties:
                        extendedKeyUsage:
                          items:
                            type: string
                          type: array
                        keyUsage:
                          items:
                            type: string
                          type: array
                        subject:
                          type: string
                        subjectAlternativeNames:
                          items:
                            properties:
                              dnsNames:
                                items:
                                  type: string
                                type: array
                              emails:
                                items:
                                  type: string
                                type: array
                              upns:
                                items:
                                  type: string
                                type: array
                            type: object
                          maxItems: 1
                          type: array
                        validityInMonths:
                          format: int64
                          type: integer
                      required:
                      - keyUsage
                      - subject
                      - validityInMonths
                      type: object
                    maxItems: 1
                    type: array
                required:
                - issuerParameters
                - keyProperties
                - secretProperties
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            keyVaultID:
              type: string
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            secretID:
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            tags:
              additionalProperties:
                type: string
              type: object
            thumbprint:
              type: string
            vaultURI:
              description: Deprecated
              type: string
            version:
              type: string
          required:
          - certificatePolicy
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                certificate:
                  items:
                    type: object
                  maxItems: 1
                  type: array
                certificateData:
                  type: string
                certificatePolicy:
                  items:
                    properties:
                      issuerParameters:
                        items:
                          properties:
                            name:
                              type: string
                          required:
                          - name
                          type: object
                        maxItems: 1
                        type: array
                      keyProperties:
                        items:
                          properties:
                            exportable:
                              type: boolean
                            keySize:
                              format: int64
                              type: integer
                            keyType:
                              type: string
                            reuseKey:
                              type: boolean
                          required:
                          - exportable
                          - keySize
                          - keyType
                          - reuseKey
                          type: object
                        maxItems: 1
                        type: array
                      lifetimeAction:
                        items:
                          properties:
                            action:
                              items:
                                properties:
                                  actionType:
                                    type: string
                                required:
                                - actionType
                                type: object
                              maxItems: 1
                              type: array
                            trigger:
                              items:
                                properties:
                                  daysBeforeExpiry:
                                    format: int64
                                    type: integer
                                  lifetimePercentage:
                                    format: int64
                                    type: integer
                                type: object
                              maxItems: 1
                              type: array
                          required:
                          - action
                          - trigger
                          type: object
                        type: array
                      secretProperties:
                        items:
                          properties:
                            contentType:
                              type: string
                          required:
                          - contentType
                          type: object
                        maxItems: 1
                        type: array
                      x509CertificateProperties:
                        items:
                          properties:
                            extendedKeyUsage:
                              items:
                                type: string
                              type: array
                            keyUsage:
                              items:
                                type: string
                              type: array
                            subject:
                              type: string
                            subjectAlternativeNames:
                              items:
                                properties:
                                  dnsNames:
                                    items:
                                      type: string
                                    type: array
                                  emails:
                                    items:
                                      type: string
                                    type: array
                                  upns:
                                    items:
                                      type: string
                                    type: array
                                type: object
                              maxItems: 1
                              type: array
                            validityInMonths:
                              format: int64
                              type: integer
                          required:
                          - keyUsage
                          - subject
                          - validityInMonths
                          type: object
                        maxItems: 1
                        type: array
                    required:
                    - issuerParameters
                    - keyProperties
                    - secretProperties
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                keyVaultID:
                  type: string
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                secretID:
                  type: string
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                tags:
                  additionalProperties:
                    type: string
                  type: object
                thumbprint:
                  type: string
                vaultURI:
                  description: Deprecated
                  type: string
                version:
                  type: string
              required:
              - certificatePolicy
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
