apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: iothubs.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: Iothub
    listKind: IothubList
    plural: iothubs
    singular: iothub
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            endpoint:
              items:
                properties:
                  batchFrequencyInSeconds:
                    format: int64
                    type: integer
                  containerName:
                    type: string
                  encoding:
                    type: string
                  fileNameFormat:
                    type: string
                  maxChunkSizeInBytes:
                    format: int64
                    type: integer
                  name:
                    type: string
                  type:
                    type: string
                required:
                - name
                - type
                type: object
              type: array
            eventHubEventsEndpoint:
              type: string
            eventHubEventsPath:
              type: string
            eventHubOperationsEndpoint:
              type: string
            eventHubOperationsPath:
              type: string
            eventHubPartitionCount:
              format: int64
              type: integer
            eventHubRetentionInDays:
              format: int64
              type: integer
            fallbackRoute:
              items:
                properties:
                  condition:
                    type: string
                  enabled:
                    type: boolean
                  endpointNames:
                    items:
                      type: string
                    type: array
                  source:
                    type: string
                type: object
              maxItems: 1
              type: array
            fileUpload:
              items:
                properties:
                  containerName:
                    type: string
                  defaultTtl:
                    type: string
                  lockDuration:
                    type: string
                  maxDeliveryCount:
                    format: int64
                    type: integer
                  notifications:
                    type: boolean
                  sasTtl:
                    type: string
                required:
                - containerName
                type: object
              maxItems: 1
              type: array
            hostname:
              type: string
            id:
              type: string
            ipFilterRule:
              items:
                properties:
                  action:
                    type: string
                  ipMask:
                    type: string
                  name:
                    type: string
                required:
                - action
                - ipMask
                - name
                type: object
              type: array
            location:
              type: string
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            resourceGroupName:
              type: string
            route:
              items:
                properties:
                  condition:
                    type: string
                  enabled:
                    type: boolean
                  endpointNames:
                    items:
                      type: string
                    type: array
                  name:
                    type: string
                  source:
                    type: string
                required:
                - enabled
                - endpointNames
                - name
                - source
                type: object
              type: array
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            sharedAccessPolicy:
              items:
                properties:
                  keyName:
                    type: string
                  permissions:
                    type: string
                type: object
              type: array
            sku:
              items:
                properties:
                  capacity:
                    format: int64
                    type: integer
                  name:
                    type: string
                  tier:
                    description: Deprecated
                    type: string
                required:
                - capacity
                - name
                type: object
              maxItems: 1
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
            type:
              type: string
          required:
          - location
          - name
          - providerRef
          - resourceGroupName
          - sku
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                endpoint:
                  items:
                    properties:
                      batchFrequencyInSeconds:
                        format: int64
                        type: integer
                      containerName:
                        type: string
                      encoding:
                        type: string
                      fileNameFormat:
                        type: string
                      maxChunkSizeInBytes:
                        format: int64
                        type: integer
                      name:
                        type: string
                      type:
                        type: string
                    required:
                    - name
                    - type
                    type: object
                  type: array
                eventHubEventsEndpoint:
                  type: string
                eventHubEventsPath:
                  type: string
                eventHubOperationsEndpoint:
                  type: string
                eventHubOperationsPath:
                  type: string
                eventHubPartitionCount:
                  format: int64
                  type: integer
                eventHubRetentionInDays:
                  format: int64
                  type: integer
                fallbackRoute:
                  items:
                    properties:
                      condition:
                        type: string
                      enabled:
                        type: boolean
                      endpointNames:
                        items:
                          type: string
                        type: array
                      source:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                fileUpload:
                  items:
                    properties:
                      containerName:
                        type: string
                      defaultTtl:
                        type: string
                      lockDuration:
                        type: string
                      maxDeliveryCount:
                        format: int64
                        type: integer
                      notifications:
                        type: boolean
                      sasTtl:
                        type: string
                    required:
                    - containerName
                    type: object
                  maxItems: 1
                  type: array
                hostname:
                  type: string
                id:
                  type: string
                ipFilterRule:
                  items:
                    properties:
                      action:
                        type: string
                      ipMask:
                        type: string
                      name:
                        type: string
                    required:
                    - action
                    - ipMask
                    - name
                    type: object
                  type: array
                location:
                  type: string
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                resourceGroupName:
                  type: string
                route:
                  items:
                    properties:
                      condition:
                        type: string
                      enabled:
                        type: boolean
                      endpointNames:
                        items:
                          type: string
                        type: array
                      name:
                        type: string
                      source:
                        type: string
                    required:
                    - enabled
                    - endpointNames
                    - name
                    - source
                    type: object
                  type: array
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                sharedAccessPolicy:
                  items:
                    properties:
                      keyName:
                        type: string
                      permissions:
                        type: string
                    type: object
                  type: array
                sku:
                  items:
                    properties:
                      capacity:
                        format: int64
                        type: integer
                      name:
                        type: string
                      tier:
                        description: Deprecated
                        type: string
                    required:
                    - capacity
                    - name
                    type: object
                  maxItems: 1
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
                type:
                  type: string
              required:
              - location
              - name
              - providerRef
              - resourceGroupName
              - sku
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
