apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: databaseclusters.digitalocean.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: digitalocean.kubeform.com
  names:
    kind: DatabaseCluster
    listKind: DatabaseClusterList
    plural: databaseclusters
    singular: databasecluster
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            database:
              type: string
            engine:
              type: string
            evictionPolicy:
              type: string
            host:
              type: string
            id:
              type: string
            maintenanceWindow:
              items:
                properties:
                  day:
                    type: string
                  hour:
                    type: string
                required:
                - day
                - hour
                type: object
              minItems: 1
              type: array
            name:
              type: string
            nodeCount:
              format: int64
              type: integer
            port:
              format: int64
              type: integer
            privateHost:
              type: string
            privateNetworkUUID:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            size:
              type: string
            sqlMode:
              type: string
            tags:
              items:
                type: string
              type: array
            urn:
              type: string
            user:
              type: string
            version:
              type: string
          required:
          - engine
          - name
          - nodeCount
          - providerRef
          - region
          - size
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                database:
                  type: string
                engine:
                  type: string
                evictionPolicy:
                  type: string
                host:
                  type: string
                id:
                  type: string
                maintenanceWindow:
                  items:
                    properties:
                      day:
                        type: string
                      hour:
                        type: string
                    required:
                    - day
                    - hour
                    type: object
                  minItems: 1
                  type: array
                name:
                  type: string
                nodeCount:
                  format: int64
                  type: integer
                port:
                  format: int64
                  type: integer
                privateHost:
                  type: string
                privateNetworkUUID:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                region:
                  type: string
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                size:
                  type: string
                sqlMode:
                  type: string
                tags:
                  items:
                    type: string
                  type: array
                urn:
                  type: string
                user:
                  type: string
                version:
                  type: string
              required:
              - engine
              - name
              - nodeCount
              - providerRef
              - region
              - size
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
