apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: droplets.digitalocean.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: digitalocean.kubeform.com
  names:
    kind: Droplet
    listKind: DropletList
    plural: droplets
    singular: droplet
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            backups:
              type: boolean
            createdAt:
              type: string
            disk:
              format: int64
              type: integer
            id:
              type: string
            image:
              type: string
            ipv4Address:
              type: string
            ipv4AddressPrivate:
              type: string
            ipv6:
              type: boolean
            ipv6Address:
              type: string
            locked:
              type: boolean
            memory:
              format: int64
              type: integer
            monitoring:
              type: boolean
            name:
              type: string
            priceHourly:
              format: float
              type: number
            priceMonthly:
              format: float
              type: number
            privateNetworking:
              type: boolean
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              type: string
            resizeDisk:
              type: boolean
            size:
              type: string
            sshKeys:
              items:
                type: string
              type: array
            status:
              type: string
            tags:
              items:
                type: string
              type: array
            urn:
              type: string
            userData:
              type: string
            vcpus:
              format: int64
              type: integer
            volumeIDS:
              items:
                type: string
              type: array
            vpcUUID:
              type: string
          required:
          - image
          - name
          - providerRef
          - region
          - size
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                backups:
                  type: boolean
                createdAt:
                  type: string
                disk:
                  format: int64
                  type: integer
                id:
                  type: string
                image:
                  type: string
                ipv4Address:
                  type: string
                ipv4AddressPrivate:
                  type: string
                ipv6:
                  type: boolean
                ipv6Address:
                  type: string
                locked:
                  type: boolean
                memory:
                  format: int64
                  type: integer
                monitoring:
                  type: boolean
                name:
                  type: string
                priceHourly:
                  format: float
                  type: number
                priceMonthly:
                  format: float
                  type: number
                privateNetworking:
                  type: boolean
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                region:
                  type: string
                resizeDisk:
                  type: boolean
                size:
                  type: string
                sshKeys:
                  items:
                    type: string
                  type: array
                status:
                  type: string
                tags:
                  items:
                    type: string
                  type: array
                urn:
                  type: string
                userData:
                  type: string
                vcpus:
                  format: int64
                  type: integer
                volumeIDS:
                  items:
                    type: string
                  type: array
                vpcUUID:
                  type: string
              required:
              - image
              - name
              - providerRef
              - region
              - size
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
