apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: storagebuckets.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: StorageBucket
    listKind: StorageBucketList
    plural: storagebuckets
    singular: storagebucket
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            cors:
              items:
                properties:
                  maxAgeSeconds:
                    format: int64
                    type: integer
                  method:
                    items:
                      type: string
                    type: array
                  origin:
                    items:
                      type: string
                    type: array
                  responseHeader:
                    items:
                      type: string
                    type: array
                type: object
              type: array
            encryption:
              items:
                properties:
                  defaultKmsKeyName:
                    type: string
                required:
                - defaultKmsKeyName
                type: object
              maxItems: 1
              type: array
            forceDestroy:
              type: boolean
            id:
              type: string
            labels:
              additionalProperties:
                type: string
              type: object
            lifecycleRule:
              items:
                properties:
                  action:
                    items:
                      properties:
                        storageClass:
                          type: string
                        type:
                          type: string
                      required:
                      - type
                      type: object
                    maxItems: 1
                    minItems: 1
                    type: array
                  condition:
                    items:
                      properties:
                        age:
                          format: int64
                          type: integer
                        createdBefore:
                          type: string
                        isLive:
                          type: boolean
                        matchesStorageClass:
                          items:
                            type: string
                          minItems: 1
                          type: array
                        numNewerVersions:
                          format: int64
                          type: integer
                      type: object
                    maxItems: 1
                    minItems: 1
                    type: array
                required:
                - action
                - condition
                type: object
              maxItems: 100
              type: array
            location:
              type: string
            logging:
              items:
                properties:
                  logBucket:
                    type: string
                  logObjectPrefix:
                    type: string
                required:
                - logBucket
                type: object
              maxItems: 1
              type: array
            name:
              type: string
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            selfLink:
              type: string
            storageClass:
              type: string
            url:
              type: string
            versioning:
              items:
                properties:
                  enabled:
                    type: boolean
                type: object
              maxItems: 1
              type: array
            website:
              items:
                properties:
                  mainPageSuffix:
                    type: string
                  notFoundPage:
                    type: string
                type: object
              type: array
          required:
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                cors:
                  items:
                    properties:
                      maxAgeSeconds:
                        format: int64
                        type: integer
                      method:
                        items:
                          type: string
                        type: array
                      origin:
                        items:
                          type: string
                        type: array
                      responseHeader:
                        items:
                          type: string
                        type: array
                    type: object
                  type: array
                encryption:
                  items:
                    properties:
                      defaultKmsKeyName:
                        type: string
                    required:
                    - defaultKmsKeyName
                    type: object
                  maxItems: 1
                  type: array
                forceDestroy:
                  type: boolean
                id:
                  type: string
                labels:
                  additionalProperties:
                    type: string
                  type: object
                lifecycleRule:
                  items:
                    properties:
                      action:
                        items:
                          properties:
                            storageClass:
                              type: string
                            type:
                              type: string
                          required:
                          - type
                          type: object
                        maxItems: 1
                        minItems: 1
                        type: array
                      condition:
                        items:
                          properties:
                            age:
                              format: int64
                              type: integer
                            createdBefore:
                              type: string
                            isLive:
                              type: boolean
                            matchesStorageClass:
                              items:
                                type: string
                              minItems: 1
                              type: array
                            numNewerVersions:
                              format: int64
                              type: integer
                          type: object
                        maxItems: 1
                        minItems: 1
                        type: array
                    required:
                    - action
                    - condition
                    type: object
                  maxItems: 100
                  type: array
                location:
                  type: string
                logging:
                  items:
                    properties:
                      logBucket:
                        type: string
                      logObjectPrefix:
                        type: string
                    required:
                    - logBucket
                    type: object
                  maxItems: 1
                  type: array
                name:
                  type: string
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                selfLink:
                  type: string
                storageClass:
                  type: string
                url:
                  type: string
                versioning:
                  items:
                    properties:
                      enabled:
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
                website:
                  items:
                    properties:
                      mainPageSuffix:
                        type: string
                      notFoundPage:
                        type: string
                    type: object
                  type: array
              required:
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
