apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: dataprocclusters.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: DataprocCluster
    listKind: DataprocClusterList
    plural: dataprocclusters
    singular: dataproccluster
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterConfig:
              items:
                properties:
                  bucket:
                    type: string
                  deleteAutogenBucket:
                    description: Deprecated
                    type: boolean
                  gceClusterConfig:
                    items:
                      properties:
                        internalIPOnly:
                          type: boolean
                        metadata:
                          additionalProperties:
                            type: string
                          type: object
                        network:
                          type: string
                        serviceAccount:
                          type: string
                        serviceAccountScopes:
                          items:
                            type: string
                          type: array
                        subnetwork:
                          type: string
                        tags:
                          items:
                            type: string
                          type: array
                        zone:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  initializationAction:
                    items:
                      properties:
                        script:
                          type: string
                        timeoutSec:
                          format: int64
                          type: integer
                      required:
                      - script
                      type: object
                    type: array
                  masterConfig:
                    items:
                      properties:
                        diskConfig:
                          items:
                            properties:
                              bootDiskSizeGb:
                                format: int64
                                type: integer
                              bootDiskType:
                                type: string
                              numLocalSsds:
                                format: int64
                                type: integer
                            type: object
                          maxItems: 1
                          type: array
                        instanceNames:
                          items:
                            type: string
                          type: array
                        machineType:
                          type: string
                        numInstances:
                          format: int64
                          type: integer
                      type: object
                    maxItems: 1
                    type: array
                  preemptibleWorkerConfig:
                    items:
                      properties:
                        diskConfig:
                          items:
                            properties:
                              bootDiskSizeGb:
                                format: int64
                                type: integer
                            type: object
                          maxItems: 1
                          type: array
                        instanceNames:
                          items:
                            type: string
                          type: array
                        numInstances:
                          format: int64
                          type: integer
                      type: object
                    maxItems: 1
                    type: array
                  softwareConfig:
                    items:
                      properties:
                        imageVersion:
                          type: string
                        overrideProperties:
                          additionalProperties:
                            type: string
                          type: object
                        properties:
                          additionalProperties:
                            type: string
                          type: object
                      type: object
                    maxItems: 1
                    type: array
                  stagingBucket:
                    type: string
                  workerConfig:
                    items:
                      properties:
                        diskConfig:
                          items:
                            properties:
                              bootDiskSizeGb:
                                format: int64
                                type: integer
                              bootDiskType:
                                type: string
                              numLocalSsds:
                                format: int64
                                type: integer
                            type: object
                          maxItems: 1
                          type: array
                        instanceNames:
                          items:
                            type: string
                          type: array
                        machineType:
                          type: string
                        numInstances:
                          format: int64
                          type: integer
                      type: object
                    maxItems: 1
                    type: array
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            labels:
              additionalProperties:
                type: string
              type: object
            name:
              type: string
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              type: string
          required:
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                clusterConfig:
                  items:
                    properties:
                      bucket:
                        type: string
                      deleteAutogenBucket:
                        description: Deprecated
                        type: boolean
                      gceClusterConfig:
                        items:
                          properties:
                            internalIPOnly:
                              type: boolean
                            metadata:
                              additionalProperties:
                                type: string
                              type: object
                            network:
                              type: string
                            serviceAccount:
                              type: string
                            serviceAccountScopes:
                              items:
                                type: string
                              type: array
                            subnetwork:
                              type: string
                            tags:
                              items:
                                type: string
                              type: array
                            zone:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      initializationAction:
                        items:
                          properties:
                            script:
                              type: string
                            timeoutSec:
                              format: int64
                              type: integer
                          required:
                          - script
                          type: object
                        type: array
                      masterConfig:
                        items:
                          properties:
                            diskConfig:
                              items:
                                properties:
                                  bootDiskSizeGb:
                                    format: int64
                                    type: integer
                                  bootDiskType:
                                    type: string
                                  numLocalSsds:
                                    format: int64
                                    type: integer
                                type: object
                              maxItems: 1
                              type: array
                            instanceNames:
                              items:
                                type: string
                              type: array
                            machineType:
                              type: string
                            numInstances:
                              format: int64
                              type: integer
                          type: object
                        maxItems: 1
                        type: array
                      preemptibleWorkerConfig:
                        items:
                          properties:
                            diskConfig:
                              items:
                                properties:
                                  bootDiskSizeGb:
                                    format: int64
                                    type: integer
                                type: object
                              maxItems: 1
                              type: array
                            instanceNames:
                              items:
                                type: string
                              type: array
                            numInstances:
                              format: int64
                              type: integer
                          type: object
                        maxItems: 1
                        type: array
                      softwareConfig:
                        items:
                          properties:
                            imageVersion:
                              type: string
                            overrideProperties:
                              additionalProperties:
                                type: string
                              type: object
                            properties:
                              additionalProperties:
                                type: string
                              type: object
                          type: object
                        maxItems: 1
                        type: array
                      stagingBucket:
                        type: string
                      workerConfig:
                        items:
                          properties:
                            diskConfig:
                              items:
                                properties:
                                  bootDiskSizeGb:
                                    format: int64
                                    type: integer
                                  bootDiskType:
                                    type: string
                                  numLocalSsds:
                                    format: int64
                                    type: integer
                                type: object
                              maxItems: 1
                              type: array
                            instanceNames:
                              items:
                                type: string
                              type: array
                            machineType:
                              type: string
                            numInstances:
                              format: int64
                              type: integer
                          type: object
                        maxItems: 1
                        type: array
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                labels:
                  additionalProperties:
                    type: string
                  type: object
                name:
                  type: string
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                region:
                  type: string
              required:
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
