apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: appenginestandardappversions.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: AppEngineStandardAppVersion
    listKind: AppEngineStandardAppVersionList
    plural: appenginestandardappversions
    singular: appenginestandardappversion
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            deployment:
              items:
                properties:
                  files:
                    items:
                      properties:
                        name:
                          type: string
                        sha1Sum:
                          type: string
                        sourceURL:
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                  zip:
                    items:
                      properties:
                        filesCount:
                          format: int64
                          type: integer
                        sourceURL:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                type: object
              maxItems: 1
              type: array
            entrypoint:
              items:
                properties:
                  shell:
                    type: string
                type: object
              maxItems: 1
              type: array
            envVariables:
              additionalProperties:
                type: string
              type: object
            handlers:
              items:
                properties:
                  authFailAction:
                    type: string
                  login:
                    type: string
                  redirectHTTPResponseCode:
                    type: string
                  script:
                    items:
                      properties:
                        scriptPath:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  securityLevel:
                    type: string
                  staticFiles:
                    items:
                      properties:
                        applicationReadable:
                          type: boolean
                        expiration:
                          type: string
                        httpHeaders:
                          additionalProperties:
                            type: string
                          type: object
                        mimeType:
                          type: string
                        path:
                          type: string
                        requireMatchingFile:
                          type: boolean
                        uploadPathRegex:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  urlRegex:
                    type: string
                type: object
              type: array
            id:
              type: string
            libraries:
              items:
                properties:
                  name:
                    type: string
                  version:
                    type: string
                type: object
              type: array
            name:
              type: string
            noopOnDestroy:
              type: boolean
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            runtime:
              type: string
            runtimeAPIVersion:
              type: string
            service:
              type: string
            threadsafe:
              type: boolean
            versionID:
              type: string
          required:
          - providerRef
          - runtime
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                deployment:
                  items:
                    properties:
                      files:
                        items:
                          properties:
                            name:
                              type: string
                            sha1Sum:
                              type: string
                            sourceURL:
                              type: string
                          required:
                          - name
                          type: object
                        type: array
                      zip:
                        items:
                          properties:
                            filesCount:
                              format: int64
                              type: integer
                            sourceURL:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                    type: object
                  maxItems: 1
                  type: array
                entrypoint:
                  items:
                    properties:
                      shell:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                envVariables:
                  additionalProperties:
                    type: string
                  type: object
                handlers:
                  items:
                    properties:
                      authFailAction:
                        type: string
                      login:
                        type: string
                      redirectHTTPResponseCode:
                        type: string
                      script:
                        items:
                          properties:
                            scriptPath:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      securityLevel:
                        type: string
                      staticFiles:
                        items:
                          properties:
                            applicationReadable:
                              type: boolean
                            expiration:
                              type: string
                            httpHeaders:
                              additionalProperties:
                                type: string
                              type: object
                            mimeType:
                              type: string
                            path:
                              type: string
                            requireMatchingFile:
                              type: boolean
                            uploadPathRegex:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      urlRegex:
                        type: string
                    type: object
                  type: array
                id:
                  type: string
                libraries:
                  items:
                    properties:
                      name:
                        type: string
                      version:
                        type: string
                    type: object
                  type: array
                name:
                  type: string
                noopOnDestroy:
                  type: boolean
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                runtime:
                  type: string
                runtimeAPIVersion:
                  type: string
                service:
                  type: string
                threadsafe:
                  type: boolean
                versionID:
                  type: string
              required:
              - providerRef
              - runtime
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
