apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: folderorganizationpolicies.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: FolderOrganizationPolicy
    listKind: FolderOrganizationPolicyList
    plural: folderorganizationpolicies
    singular: folderorganizationpolicy
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            booleanPolicy:
              items:
                properties:
                  enforced:
                    type: boolean
                required:
                - enforced
                type: object
              maxItems: 1
              type: array
            constraint:
              type: string
            etag:
              type: string
            folder:
              type: string
            id:
              type: string
            listPolicy:
              items:
                properties:
                  allow:
                    items:
                      properties:
                        all:
                          type: boolean
                        values:
                          items:
                            type: string
                          type: array
                      type: object
                    maxItems: 1
                    type: array
                  deny:
                    items:
                      properties:
                        all:
                          type: boolean
                        values:
                          items:
                            type: string
                          type: array
                      type: object
                    maxItems: 1
                    type: array
                  inheritFromParent:
                    type: boolean
                  suggestedValue:
                    type: string
                type: object
              maxItems: 1
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            restorePolicy:
              items:
                properties:
                  default:
                    type: boolean
                required:
                - default
                type: object
              maxItems: 1
              type: array
            updateTime:
              type: string
            version:
              format: int64
              type: integer
          required:
          - constraint
          - folder
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                booleanPolicy:
                  items:
                    properties:
                      enforced:
                        type: boolean
                    required:
                    - enforced
                    type: object
                  maxItems: 1
                  type: array
                constraint:
                  type: string
                etag:
                  type: string
                folder:
                  type: string
                id:
                  type: string
                listPolicy:
                  items:
                    properties:
                      allow:
                        items:
                          properties:
                            all:
                              type: boolean
                            values:
                              items:
                                type: string
                              type: array
                          type: object
                        maxItems: 1
                        type: array
                      deny:
                        items:
                          properties:
                            all:
                              type: boolean
                            values:
                              items:
                                type: string
                              type: array
                          type: object
                        maxItems: 1
                        type: array
                      inheritFromParent:
                        type: boolean
                      suggestedValue:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                restorePolicy:
                  items:
                    properties:
                      default:
                        type: boolean
                    required:
                    - default
                    type: object
                  maxItems: 1
                  type: array
                updateTime:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - constraint
              - folder
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
