apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: computebackendservices.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: ComputeBackendService
    listKind: ComputeBackendServiceList
    plural: computebackendservices
    singular: computebackendservice
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            backend:
              items:
                properties:
                  balancingMode:
                    type: string
                  capacityScaler:
                    format: float
                    type: number
                  description:
                    type: string
                  group:
                    type: string
                  maxConnections:
                    format: int64
                    type: integer
                  maxConnectionsPerInstance:
                    format: int64
                    type: integer
                  maxRate:
                    format: int64
                    type: integer
                  maxRatePerInstance:
                    format: float
                    type: number
                  maxUtilization:
                    format: float
                    type: number
                type: object
              type: array
            cdnPolicy:
              items:
                properties:
                  cacheKeyPolicy:
                    items:
                      properties:
                        includeHost:
                          type: boolean
                        includeProtocol:
                          type: boolean
                        includeQueryString:
                          type: boolean
                        queryStringBlacklist:
                          items:
                            type: string
                          type: array
                        queryStringWhitelist:
                          items:
                            type: string
                          type: array
                      type: object
                    maxItems: 1
                    type: array
                type: object
              maxItems: 1
              type: array
            connectionDrainingTimeoutSec:
              format: int64
              type: integer
            customRequestHeaders:
              description: Deprecated
              items:
                type: string
              type: array
            description:
              type: string
            enableCdn:
              type: boolean
            fingerprint:
              type: string
            healthChecks:
              items:
                type: string
              maxItems: 1
              minItems: 1
              type: array
            iap:
              items:
                properties:
                  oauth2ClientID:
                    type: string
                required:
                - oauth2ClientID
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            name:
              type: string
            portName:
              type: string
            project:
              type: string
            protocol:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            securityPolicy:
              type: string
            selfLink:
              type: string
            sessionAffinity:
              type: string
            timeoutSec:
              format: int64
              type: integer
          required:
          - healthChecks
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                backend:
                  items:
                    properties:
                      balancingMode:
                        type: string
                      capacityScaler:
                        format: float
                        type: number
                      description:
                        type: string
                      group:
                        type: string
                      maxConnections:
                        format: int64
                        type: integer
                      maxConnectionsPerInstance:
                        format: int64
                        type: integer
                      maxRate:
                        format: int64
                        type: integer
                      maxRatePerInstance:
                        format: float
                        type: number
                      maxUtilization:
                        format: float
                        type: number
                    type: object
                  type: array
                cdnPolicy:
                  items:
                    properties:
                      cacheKeyPolicy:
                        items:
                          properties:
                            includeHost:
                              type: boolean
                            includeProtocol:
                              type: boolean
                            includeQueryString:
                              type: boolean
                            queryStringBlacklist:
                              items:
                                type: string
                              type: array
                            queryStringWhitelist:
                              items:
                                type: string
                              type: array
                          type: object
                        maxItems: 1
                        type: array
                    type: object
                  maxItems: 1
                  type: array
                connectionDrainingTimeoutSec:
                  format: int64
                  type: integer
                customRequestHeaders:
                  description: Deprecated
                  items:
                    type: string
                  type: array
                description:
                  type: string
                enableCdn:
                  type: boolean
                fingerprint:
                  type: string
                healthChecks:
                  items:
                    type: string
                  maxItems: 1
                  minItems: 1
                  type: array
                iap:
                  items:
                    properties:
                      oauth2ClientID:
                        type: string
                    required:
                    - oauth2ClientID
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                name:
                  type: string
                portName:
                  type: string
                project:
                  type: string
                protocol:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                securityPolicy:
                  type: string
                selfLink:
                  type: string
                sessionAffinity:
                  type: string
                timeoutSec:
                  format: int64
                  type: integer
              required:
              - healthChecks
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
