apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: loggingmetrics.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: LoggingMetric
    listKind: LoggingMetricList
    plural: loggingmetrics
    singular: loggingmetric
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            bucketOptions:
              items:
                properties:
                  explicitBuckets:
                    items:
                      properties:
                        bounds:
                          items:
                            format: float
                            type: number
                          type: array
                      type: object
                    maxItems: 1
                    type: array
                  exponentialBuckets:
                    items:
                      properties:
                        growthFactor:
                          format: int64
                          type: integer
                        numFiniteBuckets:
                          format: int64
                          type: integer
                        scale:
                          format: float
                          type: number
                      type: object
                    maxItems: 1
                    type: array
                  linearBuckets:
                    items:
                      properties:
                        numFiniteBuckets:
                          format: int64
                          type: integer
                        offset:
                          format: float
                          type: number
                        width:
                          format: int64
                          type: integer
                      type: object
                    maxItems: 1
                    type: array
                type: object
              maxItems: 1
              type: array
            description:
              type: string
            filter:
              type: string
            id:
              type: string
            labelExtractors:
              additionalProperties:
                type: string
              type: object
            metricDescriptor:
              items:
                properties:
                  labels:
                    items:
                      properties:
                        description:
                          type: string
                        key:
                          type: string
                        valueType:
                          type: string
                      required:
                      - key
                      type: object
                    type: array
                  metricKind:
                    type: string
                  unit:
                    type: string
                  valueType:
                    type: string
                required:
                - metricKind
                - valueType
                type: object
              maxItems: 1
              type: array
            name:
              type: string
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            valueExtractor:
              type: string
          required:
          - filter
          - metricDescriptor
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                bucketOptions:
                  items:
                    properties:
                      explicitBuckets:
                        items:
                          properties:
                            bounds:
                              items:
                                format: float
                                type: number
                              type: array
                          type: object
                        maxItems: 1
                        type: array
                      exponentialBuckets:
                        items:
                          properties:
                            growthFactor:
                              format: int64
                              type: integer
                            numFiniteBuckets:
                              format: int64
                              type: integer
                            scale:
                              format: float
                              type: number
                          type: object
                        maxItems: 1
                        type: array
                      linearBuckets:
                        items:
                          properties:
                            numFiniteBuckets:
                              format: int64
                              type: integer
                            offset:
                              format: float
                              type: number
                            width:
                              format: int64
                              type: integer
                          type: object
                        maxItems: 1
                        type: array
                    type: object
                  maxItems: 1
                  type: array
                description:
                  type: string
                filter:
                  type: string
                id:
                  type: string
                labelExtractors:
                  additionalProperties:
                    type: string
                  type: object
                metricDescriptor:
                  items:
                    properties:
                      labels:
                        items:
                          properties:
                            description:
                              type: string
                            key:
                              type: string
                            valueType:
                              type: string
                          required:
                          - key
                          type: object
                        type: array
                      metricKind:
                        type: string
                      unit:
                        type: string
                      valueType:
                        type: string
                    required:
                    - metricKind
                    - valueType
                    type: object
                  maxItems: 1
                  type: array
                name:
                  type: string
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                valueExtractor:
                  type: string
              required:
              - filter
              - metricDescriptor
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
