apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: computeresourcepolicies.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: ComputeResourcePolicy
    listKind: ComputeResourcePolicyList
    plural: computeresourcepolicies
    singular: computeresourcepolicy
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            id:
              type: string
            name:
              type: string
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              type: string
            selfLink:
              type: string
            snapshotSchedulePolicy:
              items:
                properties:
                  retentionPolicy:
                    items:
                      properties:
                        maxRetentionDays:
                          format: int64
                          type: integer
                        onSourceDiskDelete:
                          type: string
                      required:
                      - maxRetentionDays
                      type: object
                    maxItems: 1
                    type: array
                  schedule:
                    items:
                      properties:
                        dailySchedule:
                          items:
                            properties:
                              daysInCycle:
                                format: int64
                                type: integer
                              startTime:
                                type: string
                            required:
                            - daysInCycle
                            - startTime
                            type: object
                          maxItems: 1
                          type: array
                        hourlySchedule:
                          items:
                            properties:
                              hoursInCycle:
                                format: int64
                                type: integer
                              startTime:
                                type: string
                            required:
                            - hoursInCycle
                            - startTime
                            type: object
                          maxItems: 1
                          type: array
                        weeklySchedule:
                          items:
                            properties:
                              dayOfWeeks:
                                items:
                                  properties:
                                    day:
                                      type: string
                                    startTime:
                                      type: string
                                  required:
                                  - day
                                  - startTime
                                  type: object
                                maxItems: 7
                                minItems: 1
                                type: array
                            required:
                            - dayOfWeeks
                            type: object
                          maxItems: 1
                          type: array
                      type: object
                    maxItems: 1
                    type: array
                  snapshotProperties:
                    items:
                      properties:
                        guestFlush:
                          type: boolean
                        labels:
                          additionalProperties:
                            type: string
                          type: object
                        storageLocations:
                          items:
                            type: string
                          maxItems: 1
                          type: array
                      type: object
                    maxItems: 1
                    type: array
                required:
                - schedule
                type: object
              maxItems: 1
              type: array
          required:
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                id:
                  type: string
                name:
                  type: string
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                region:
                  type: string
                selfLink:
                  type: string
                snapshotSchedulePolicy:
                  items:
                    properties:
                      retentionPolicy:
                        items:
                          properties:
                            maxRetentionDays:
                              format: int64
                              type: integer
                            onSourceDiskDelete:
                              type: string
                          required:
                          - maxRetentionDays
                          type: object
                        maxItems: 1
                        type: array
                      schedule:
                        items:
                          properties:
                            dailySchedule:
                              items:
                                properties:
                                  daysInCycle:
                                    format: int64
                                    type: integer
                                  startTime:
                                    type: string
                                required:
                                - daysInCycle
                                - startTime
                                type: object
                              maxItems: 1
                              type: array
                            hourlySchedule:
                              items:
                                properties:
                                  hoursInCycle:
                                    format: int64
                                    type: integer
                                  startTime:
                                    type: string
                                required:
                                - hoursInCycle
                                - startTime
                                type: object
                              maxItems: 1
                              type: array
                            weeklySchedule:
                              items:
                                properties:
                                  dayOfWeeks:
                                    items:
                                      properties:
                                        day:
                                          type: string
                                        startTime:
                                          type: string
                                      required:
                                      - day
                                      - startTime
                                      type: object
                                    maxItems: 7
                                    minItems: 1
                                    type: array
                                required:
                                - dayOfWeeks
                                type: object
                              maxItems: 1
                              type: array
                          type: object
                        maxItems: 1
                        type: array
                      snapshotProperties:
                        items:
                          properties:
                            guestFlush:
                              type: boolean
                            labels:
                              additionalProperties:
                                type: string
                              type: object
                            storageLocations:
                              items:
                                type: string
                              maxItems: 1
                              type: array
                          type: object
                        maxItems: 1
                        type: array
                    required:
                    - schedule
                    type: object
                  maxItems: 1
                  type: array
              required:
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
