apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: endpointsservices.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: EndpointsService
    listKind: EndpointsServiceList
    plural: endpointsservices
    singular: endpointsservice
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            apis:
              items:
                properties:
                  methods:
                    items:
                      properties:
                        name:
                          type: string
                        requestType:
                          type: string
                        responseType:
                          type: string
                        syntax:
                          type: string
                      type: object
                    type: array
                  name:
                    type: string
                  syntax:
                    type: string
                  version:
                    type: string
                type: object
              type: array
            configID:
              type: string
            dnsAddress:
              type: string
            endpoints:
              items:
                properties:
                  address:
                    type: string
                  name:
                    type: string
                type: object
              type: array
            grpcConfig:
              type: string
            id:
              type: string
            openapiConfig:
              type: string
            project:
              type: string
            protocOutput:
              description: Deprecated
              type: string
            protocOutputBase64:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            serviceName:
              type: string
          required:
          - providerRef
          - serviceName
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                apis:
                  items:
                    properties:
                      methods:
                        items:
                          properties:
                            name:
                              type: string
                            requestType:
                              type: string
                            responseType:
                              type: string
                            syntax:
                              type: string
                          type: object
                        type: array
                      name:
                        type: string
                      syntax:
                        type: string
                      version:
                        type: string
                    type: object
                  type: array
                configID:
                  type: string
                dnsAddress:
                  type: string
                endpoints:
                  items:
                    properties:
                      address:
                        type: string
                      name:
                        type: string
                    type: object
                  type: array
                grpcConfig:
                  type: string
                id:
                  type: string
                openapiConfig:
                  type: string
                project:
                  type: string
                protocOutput:
                  description: Deprecated
                  type: string
                protocOutputBase64:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                serviceName:
                  type: string
              required:
              - providerRef
              - serviceName
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
