apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: computeinterconnectattachments.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: ComputeInterconnectAttachment
    listKind: ComputeInterconnectAttachmentList
    plural: computeinterconnectattachments
    singular: computeinterconnectattachment
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            adminEnabled:
              type: boolean
            bandwidth:
              type: string
            candidateSubnets:
              items:
                type: string
              type: array
            cloudRouterIPAddress:
              type: string
            creationTimestamp:
              type: string
            customerRouterIPAddress:
              type: string
            description:
              type: string
            edgeAvailabilityDomain:
              type: string
            googleReferenceID:
              type: string
            id:
              type: string
            interconnect:
              type: string
            name:
              type: string
            pairingKey:
              type: string
            partnerAsn:
              type: string
            privateInterconnectInfo:
              items:
                properties:
                  tag8021q:
                    format: int64
                    type: integer
                type: object
              maxItems: 1
              type: array
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              type: string
            router:
              type: string
            selfLink:
              type: string
            state:
              type: string
            type:
              type: string
            vlanTag8021q:
              format: int64
              type: integer
          required:
          - name
          - providerRef
          - router
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                adminEnabled:
                  type: boolean
                bandwidth:
                  type: string
                candidateSubnets:
                  items:
                    type: string
                  type: array
                cloudRouterIPAddress:
                  type: string
                creationTimestamp:
                  type: string
                customerRouterIPAddress:
                  type: string
                description:
                  type: string
                edgeAvailabilityDomain:
                  type: string
                googleReferenceID:
                  type: string
                id:
                  type: string
                interconnect:
                  type: string
                name:
                  type: string
                pairingKey:
                  type: string
                partnerAsn:
                  type: string
                privateInterconnectInfo:
                  items:
                    properties:
                      tag8021q:
                        format: int64
                        type: integer
                    type: object
                  maxItems: 1
                  type: array
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                region:
                  type: string
                router:
                  type: string
                selfLink:
                  type: string
                state:
                  type: string
                type:
                  type: string
                vlanTag8021q:
                  format: int64
                  type: integer
              required:
              - name
              - providerRef
              - router
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
