apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: computeregioninstancegroupmanagers.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: ComputeRegionInstanceGroupManager
    listKind: ComputeRegionInstanceGroupManagerList
    plural: computeregioninstancegroupmanagers
    singular: computeregioninstancegroupmanager
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            autoHealingPolicies:
              description: Deprecated
              items:
                properties:
                  healthCheck:
                    type: string
                  initialDelaySec:
                    format: int64
                    type: integer
                required:
                - healthCheck
                - initialDelaySec
                type: object
              maxItems: 1
              type: array
            baseInstanceName:
              type: string
            description:
              type: string
            distributionPolicyZones:
              items:
                type: string
              type: array
            fingerprint:
              type: string
            id:
              type: string
            instanceGroup:
              type: string
            instanceTemplate:
              type: string
            name:
              type: string
            namedPort:
              items:
                properties:
                  name:
                    type: string
                  port:
                    format: int64
                    type: integer
                required:
                - name
                - port
                type: object
              type: array
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              type: string
            rollingUpdatePolicy:
              description: Deprecated
              items:
                properties:
                  maxSurgeFixed:
                    format: int64
                    type: integer
                  maxSurgePercent:
                    format: int64
                    type: integer
                  maxUnavailableFixed:
                    format: int64
                    type: integer
                  maxUnavailablePercent:
                    format: int64
                    type: integer
                  minReadySec:
                    format: int64
                    type: integer
                  minimalAction:
                    type: string
                  type:
                    type: string
                required:
                - minimalAction
                - type
                type: object
              maxItems: 1
              type: array
            selfLink:
              type: string
            targetPools:
              items:
                type: string
              type: array
            targetSize:
              format: int64
              type: integer
            updateStrategy:
              description: Deprecated
              type: string
            version:
              description: Deprecated
              items:
                properties:
                  instanceTemplate:
                    type: string
                  name:
                    type: string
                  targetSize:
                    items:
                      properties:
                        fixed:
                          format: int64
                          type: integer
                        percent:
                          format: int64
                          type: integer
                      type: object
                    maxItems: 1
                    type: array
                required:
                - instanceTemplate
                - name
                type: object
              type: array
            waitForInstances:
              type: boolean
          required:
          - baseInstanceName
          - name
          - providerRef
          - region
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                autoHealingPolicies:
                  description: Deprecated
                  items:
                    properties:
                      healthCheck:
                        type: string
                      initialDelaySec:
                        format: int64
                        type: integer
                    required:
                    - healthCheck
                    - initialDelaySec
                    type: object
                  maxItems: 1
                  type: array
                baseInstanceName:
                  type: string
                description:
                  type: string
                distributionPolicyZones:
                  items:
                    type: string
                  type: array
                fingerprint:
                  type: string
                id:
                  type: string
                instanceGroup:
                  type: string
                instanceTemplate:
                  type: string
                name:
                  type: string
                namedPort:
                  items:
                    properties:
                      name:
                        type: string
                      port:
                        format: int64
                        type: integer
                    required:
                    - name
                    - port
                    type: object
                  type: array
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                region:
                  type: string
                rollingUpdatePolicy:
                  description: Deprecated
                  items:
                    properties:
                      maxSurgeFixed:
                        format: int64
                        type: integer
                      maxSurgePercent:
                        format: int64
                        type: integer
                      maxUnavailableFixed:
                        format: int64
                        type: integer
                      maxUnavailablePercent:
                        format: int64
                        type: integer
                      minReadySec:
                        format: int64
                        type: integer
                      minimalAction:
                        type: string
                      type:
                        type: string
                    required:
                    - minimalAction
                    - type
                    type: object
                  maxItems: 1
                  type: array
                selfLink:
                  type: string
                targetPools:
                  items:
                    type: string
                  type: array
                targetSize:
                  format: int64
                  type: integer
                updateStrategy:
                  description: Deprecated
                  type: string
                version:
                  description: Deprecated
                  items:
                    properties:
                      instanceTemplate:
                        type: string
                      name:
                        type: string
                      targetSize:
                        items:
                          properties:
                            fixed:
                              format: int64
                              type: integer
                            percent:
                              format: int64
                              type: integer
                          type: object
                        maxItems: 1
                        type: array
                    required:
                    - instanceTemplate
                    - name
                    type: object
                  type: array
                waitForInstances:
                  type: boolean
              required:
              - baseInstanceName
              - name
              - providerRef
              - region
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
