apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: nodebalancers.linode.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: linode.kubeform.com
  names:
    kind: Nodebalancer
    listKind: NodebalancerList
    plural: nodebalancers
    singular: nodebalancer
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clientConnThrottle:
              description: Throttle connections per second (0-20). Set to 0 (zero)
                to disable throttling.
              format: int64
              type: integer
            created:
              type: string
            hostname:
              description: This NodeBalancer's hostname, ending with .nodebalancer.linode.com
              type: string
            id:
              type: string
            ipv4:
              description: The Public IPv4 Address of this NodeBalancer
              type: string
            ipv6:
              description: The Public IPv6 Address of this NodeBalancer
              type: string
            label:
              description: The label of the Linode NodeBalancer.
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              description: The region where this NodeBalancer will be deployed.
              type: string
            tags:
              description: An array of tags applied to this object. Tags are for organizational
                purposes only.
              items:
                type: string
              type: array
            transfer:
              additionalProperties:
                properties:
                  in:
                    description: The total transfer, in MB, used by this NodeBalancer
                      this month
                    format: float
                    type: number
                  out:
                    description: The total inbound transfer, in MB, used for this
                      NodeBalancer this month
                    format: float
                    type: number
                  total:
                    description: The total outbound transfer, in MB, used for this
                      NodeBalancer this month
                    format: float
                    type: number
                type: object
              type: object
            updated:
              type: string
          required:
          - providerRef
          - region
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                clientConnThrottle:
                  description: Throttle connections per second (0-20). Set to 0 (zero)
                    to disable throttling.
                  format: int64
                  type: integer
                created:
                  type: string
                hostname:
                  description: This NodeBalancer's hostname, ending with .nodebalancer.linode.com
                  type: string
                id:
                  type: string
                ipv4:
                  description: The Public IPv4 Address of this NodeBalancer
                  type: string
                ipv6:
                  description: The Public IPv6 Address of this NodeBalancer
                  type: string
                label:
                  description: The label of the Linode NodeBalancer.
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                region:
                  description: The region where this NodeBalancer will be deployed.
                  type: string
                tags:
                  description: An array of tags applied to this object. Tags are for
                    organizational purposes only.
                  items:
                    type: string
                  type: array
                transfer:
                  additionalProperties:
                    properties:
                      in:
                        description: The total transfer, in MB, used by this NodeBalancer
                          this month
                        format: float
                        type: number
                      out:
                        description: The total inbound transfer, in MB, used for this
                          NodeBalancer this month
                        format: float
                        type: number
                      total:
                        description: The total outbound transfer, in MB, used for
                          this NodeBalancer this month
                        format: float
                        type: number
                    type: object
                  type: object
                updated:
                  type: string
              required:
              - providerRef
              - region
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
