apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: images.linode.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: linode.kubeform.com
  names:
    kind: Image
    listKind: ImageList
    plural: images
    singular: image
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            created:
              description: When this Image was created.
              type: string
            createdBy:
              description: The name of the User who created this Image.
              type: string
            deprecated:
              description: Whether or not this Image is deprecated. Will only be True
                for deprecated public Images.
              type: boolean
            description:
              description: A detailed description of this Image.
              type: string
            diskID:
              description: The ID of the Linode Disk that this Image will be created
                from.
              format: int64
              type: integer
            expiry:
              description: Only Images created automatically (from a deleted Linode;
                type=automatic) will expire.
              type: string
            id:
              type: string
            isPublic:
              description: True if the Image is public.
              type: boolean
            label:
              description: A short description of the Image. Labels cannot contain
                special characters.
              type: string
            linodeID:
              description: The ID of the Linode that this Image will be created from.
              format: int64
              type: integer
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            size:
              description: The minimum size this Image needs to deploy. Size is in
                MB.
              format: int64
              type: integer
            type:
              description: How the Image was created. 'Manual' Images can be created
                at any time. 'Automatic' images are created automatically from a deleted
                Linode.
              type: string
            vendor:
              description: The upstream distribution vendor. Nil for private Images.
              type: string
          required:
          - diskID
          - label
          - linodeID
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                created:
                  description: When this Image was created.
                  type: string
                createdBy:
                  description: The name of the User who created this Image.
                  type: string
                deprecated:
                  description: Whether or not this Image is deprecated. Will only
                    be True for deprecated public Images.
                  type: boolean
                description:
                  description: A detailed description of this Image.
                  type: string
                diskID:
                  description: The ID of the Linode Disk that this Image will be created
                    from.
                  format: int64
                  type: integer
                expiry:
                  description: Only Images created automatically (from a deleted Linode;
                    type=automatic) will expire.
                  type: string
                id:
                  type: string
                isPublic:
                  description: True if the Image is public.
                  type: boolean
                label:
                  description: A short description of the Image. Labels cannot contain
                    special characters.
                  type: string
                linodeID:
                  description: The ID of the Linode that this Image will be created
                    from.
                  format: int64
                  type: integer
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                size:
                  description: The minimum size this Image needs to deploy. Size is
                    in MB.
                  format: int64
                  type: integer
                type:
                  description: How the Image was created. 'Manual' Images can be created
                    at any time. 'Automatic' images are created automatically from
                    a deleted Linode.
                  type: string
                vendor:
                  description: The upstream distribution vendor. Nil for private Images.
                  type: string
              required:
              - diskID
              - label
              - linodeID
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
