apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app: kubeform
  name: domainrecords.linode.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: linode.kubeform.com
  names:
    kind: DomainRecord
    listKind: DomainRecordList
    plural: domainrecords
    singular: domainrecord
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            domainID:
              description: The ID of the Domain to access.
              format: int64
              type: integer
            id:
              type: string
            name:
              description: The name of this Record. This field's actual usage depends
                on the type of record this represents. For A and AAAA records, this
                is the subdomain being associated with an IP address.
              type: string
            port:
              description: The port this Record points to.
              format: int64
              type: integer
            priority:
              description: The priority of the target host. Lower values are preferred.
              format: int64
              type: integer
            protocol:
              description: The protocol this Record's service communicates with. Only
                valid for SRV records.
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            recordType:
              description: The type of Record this is in the DNS system. For example,
                A records associate a domain name with an IPv4 address, and AAAA records
                associate a domain name with an IPv6 address.
              type: string
            service:
              description: The service this Record identified. Only valid for SRV
                records.
              type: string
            tag:
              description: The tag portion of a CAA record. It is invalid to set this
                on other record types.
              type: string
            target:
              description: The target for this Record. This field's actual usage depends
                on the type of record this represents. For A and AAAA records, this
                is the address the named Domain should resolve to.
              type: string
            ttlSec:
              description: '''Time to Live'' - the amount of time in seconds that
                this Domain''s records may be cached by resolvers or other domain
                servers. Valid values are 0, 300, 3600, 7200, 14400, 28800, 57600,
                86400, 172800, 345600, 604800, 1209600, and 2419200 - any other value
                will be rounded to the nearest valid value.'
              format: int64
              type: integer
            weight:
              description: The relative weight of this Record. Higher values are preferred.
              format: int64
              type: integer
          required:
          - domainID
          - name
          - providerRef
          - recordType
          - target
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                domainID:
                  description: The ID of the Domain to access.
                  format: int64
                  type: integer
                id:
                  type: string
                name:
                  description: The name of this Record. This field's actual usage
                    depends on the type of record this represents. For A and AAAA
                    records, this is the subdomain being associated with an IP address.
                  type: string
                port:
                  description: The port this Record points to.
                  format: int64
                  type: integer
                priority:
                  description: The priority of the target host. Lower values are preferred.
                  format: int64
                  type: integer
                protocol:
                  description: The protocol this Record's service communicates with.
                    Only valid for SRV records.
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                recordType:
                  description: The type of Record this is in the DNS system. For example,
                    A records associate a domain name with an IPv4 address, and AAAA
                    records associate a domain name with an IPv6 address.
                  type: string
                service:
                  description: The service this Record identified. Only valid for
                    SRV records.
                  type: string
                tag:
                  description: The tag portion of a CAA record. It is invalid to set
                    this on other record types.
                  type: string
                target:
                  description: The target for this Record. This field's actual usage
                    depends on the type of record this represents. For A and AAAA
                    records, this is the address the named Domain should resolve to.
                  type: string
                ttlSec:
                  description: '''Time to Live'' - the amount of time in seconds that
                    this Domain''s records may be cached by resolvers or other domain
                    servers. Valid values are 0, 300, 3600, 7200, 14400, 28800, 57600,
                    86400, 172800, 345600, 604800, 1209600, and 2419200 - any other
                    value will be rounded to the nearest valid value.'
                  format: int64
                  type: integer
                weight:
                  description: The relative weight of this Record. Higher values are
                    preferred.
                  format: int64
                  type: integer
              required:
              - domainID
              - name
              - providerRef
              - recordType
              - target
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
