apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: appmeshvirtualnodes.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: AppmeshVirtualNode
    listKind: AppmeshVirtualNodeList
    plural: appmeshvirtualnodes
    singular: appmeshvirtualnode
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            arn:
              type: string
            createdDate:
              type: string
            id:
              type: string
            lastUpdatedDate:
              type: string
            meshName:
              type: string
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            spec:
              items:
                properties:
                  backend:
                    items:
                      properties:
                        virtualService:
                          items:
                            properties:
                              virtualServiceName:
                                type: string
                            required:
                            - virtualServiceName
                            type: object
                          maxItems: 1
                          type: array
                      type: object
                    maxItems: 25
                    type: array
                  listener:
                    items:
                      properties:
                        healthCheck:
                          items:
                            properties:
                              healthyThreshold:
                                format: int64
                                type: integer
                              intervalMillis:
                                format: int64
                                type: integer
                              path:
                                type: string
                              port:
                                format: int64
                                type: integer
                              protocol:
                                type: string
                              timeoutMillis:
                                format: int64
                                type: integer
                              unhealthyThreshold:
                                format: int64
                                type: integer
                            required:
                            - healthyThreshold
                            - intervalMillis
                            - protocol
                            - timeoutMillis
                            - unhealthyThreshold
                            type: object
                          maxItems: 1
                          type: array
                        portMapping:
                          items:
                            properties:
                              port:
                                format: int64
                                type: integer
                              protocol:
                                type: string
                            required:
                            - port
                            - protocol
                            type: object
                          maxItems: 1
                          minItems: 1
                          type: array
                      required:
                      - portMapping
                      type: object
                    maxItems: 1
                    type: array
                  logging:
                    items:
                      properties:
                        accessLog:
                          items:
                            properties:
                              file:
                                items:
                                  properties:
                                    path:
                                      type: string
                                  required:
                                  - path
                                  type: object
                                maxItems: 1
                                type: array
                            type: object
                          maxItems: 1
                          type: array
                      type: object
                    maxItems: 1
                    type: array
                  serviceDiscovery:
                    items:
                      properties:
                        awsCloudMap:
                          items:
                            properties:
                              attributes:
                                additionalProperties:
                                  type: string
                                type: object
                              namespaceName:
                                type: string
                              serviceName:
                                type: string
                            required:
                            - namespaceName
                            - serviceName
                            type: object
                          maxItems: 1
                          type: array
                        dns:
                          items:
                            properties:
                              hostname:
                                type: string
                            required:
                            - hostname
                            type: object
                          maxItems: 1
                          type: array
                      type: object
                    maxItems: 1
                    type: array
                type: object
              maxItems: 1
              minItems: 1
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
          required:
          - meshName
          - name
          - providerRef
          - spec
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                arn:
                  type: string
                createdDate:
                  type: string
                id:
                  type: string
                lastUpdatedDate:
                  type: string
                meshName:
                  type: string
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                spec:
                  items:
                    properties:
                      backend:
                        items:
                          properties:
                            virtualService:
                              items:
                                properties:
                                  virtualServiceName:
                                    type: string
                                required:
                                - virtualServiceName
                                type: object
                              maxItems: 1
                              type: array
                          type: object
                        maxItems: 25
                        type: array
                      listener:
                        items:
                          properties:
                            healthCheck:
                              items:
                                properties:
                                  healthyThreshold:
                                    format: int64
                                    type: integer
                                  intervalMillis:
                                    format: int64
                                    type: integer
                                  path:
                                    type: string
                                  port:
                                    format: int64
                                    type: integer
                                  protocol:
                                    type: string
                                  timeoutMillis:
                                    format: int64
                                    type: integer
                                  unhealthyThreshold:
                                    format: int64
                                    type: integer
                                required:
                                - healthyThreshold
                                - intervalMillis
                                - protocol
                                - timeoutMillis
                                - unhealthyThreshold
                                type: object
                              maxItems: 1
                              type: array
                            portMapping:
                              items:
                                properties:
                                  port:
                                    format: int64
                                    type: integer
                                  protocol:
                                    type: string
                                required:
                                - port
                                - protocol
                                type: object
                              maxItems: 1
                              minItems: 1
                              type: array
                          required:
                          - portMapping
                          type: object
                        maxItems: 1
                        type: array
                      logging:
                        items:
                          properties:
                            accessLog:
                              items:
                                properties:
                                  file:
                                    items:
                                      properties:
                                        path:
                                          type: string
                                      required:
                                      - path
                                      type: object
                                    maxItems: 1
                                    type: array
                                type: object
                              maxItems: 1
                              type: array
                          type: object
                        maxItems: 1
                        type: array
                      serviceDiscovery:
                        items:
                          properties:
                            awsCloudMap:
                              items:
                                properties:
                                  attributes:
                                    additionalProperties:
                                      type: string
                                    type: object
                                  namespaceName:
                                    type: string
                                  serviceName:
                                    type: string
                                required:
                                - namespaceName
                                - serviceName
                                type: object
                              maxItems: 1
                              type: array
                            dns:
                              items:
                                properties:
                                  hostname:
                                    type: string
                                required:
                                - hostname
                                type: object
                              maxItems: 1
                              type: array
                          type: object
                        maxItems: 1
                        type: array
                    type: object
                  maxItems: 1
                  minItems: 1
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
              required:
              - meshName
              - name
              - providerRef
              - spec
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
