apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: s3bucketinventories.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: S3BucketInventory
    listKind: S3BucketInventoryList
    plural: s3bucketinventories
    singular: s3bucketinventory
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            bucket:
              type: string
            destination:
              items:
                properties:
                  bucket:
                    items:
                      properties:
                        accountID:
                          type: string
                        bucketArn:
                          type: string
                        encryption:
                          items:
                            properties:
                              sseKms:
                                items:
                                  properties:
                                    keyID:
                                      type: string
                                  required:
                                  - keyID
                                  type: object
                                maxItems: 1
                                type: array
                              sseS3:
                                items:
                                  type: object
                                maxItems: 1
                                type: array
                            type: object
                          maxItems: 1
                          type: array
                        format:
                          type: string
                        prefix:
                          type: string
                      required:
                      - bucketArn
                      - format
                      type: object
                    maxItems: 1
                    minItems: 1
                    type: array
                required:
                - bucket
                type: object
              maxItems: 1
              minItems: 1
              type: array
            enabled:
              type: boolean
            filter:
              items:
                properties:
                  prefix:
                    type: string
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            includedObjectVersions:
              type: string
            name:
              type: string
            optionalFields:
              items:
                type: string
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            remoteBackend:
              description: Backend specifies the configuration of the terraform backend
              properties:
                ref:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                type:
                  type: string
              type: object
            schedule:
              items:
                properties:
                  frequency:
                    type: string
                required:
                - frequency
                type: object
              maxItems: 1
              minItems: 1
              type: array
          required:
          - bucket
          - destination
          - includedObjectVersions
          - name
          - providerRef
          - schedule
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                bucket:
                  type: string
                destination:
                  items:
                    properties:
                      bucket:
                        items:
                          properties:
                            accountID:
                              type: string
                            bucketArn:
                              type: string
                            encryption:
                              items:
                                properties:
                                  sseKms:
                                    items:
                                      properties:
                                        keyID:
                                          type: string
                                      required:
                                      - keyID
                                      type: object
                                    maxItems: 1
                                    type: array
                                  sseS3:
                                    items:
                                      type: object
                                    maxItems: 1
                                    type: array
                                type: object
                              maxItems: 1
                              type: array
                            format:
                              type: string
                            prefix:
                              type: string
                          required:
                          - bucketArn
                          - format
                          type: object
                        maxItems: 1
                        minItems: 1
                        type: array
                    required:
                    - bucket
                    type: object
                  maxItems: 1
                  minItems: 1
                  type: array
                enabled:
                  type: boolean
                filter:
                  items:
                    properties:
                      prefix:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                includedObjectVersions:
                  type: string
                name:
                  type: string
                optionalFields:
                  items:
                    type: string
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                remoteBackend:
                  description: Backend specifies the configuration of the terraform
                    backend
                  properties:
                    ref:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    type:
                      type: string
                  type: object
                schedule:
                  items:
                    properties:
                      frequency:
                        type: string
                    required:
                    - frequency
                    type: object
                  maxItems: 1
                  minItems: 1
                  type: array
              required:
              - bucket
              - destination
              - includedObjectVersions
              - name
              - providerRef
              - schedule
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
