apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: cloudwatchmetricalarms.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: CloudwatchMetricAlarm
    listKind: CloudwatchMetricAlarmList
    plural: cloudwatchmetricalarms
    singular: cloudwatchmetricalarm
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            actionsEnabled:
              type: boolean
            alarmActions:
              items:
                type: string
              type: array
            alarmDescription:
              type: string
            alarmName:
              type: string
            arn:
              type: string
            comparisonOperator:
              type: string
            datapointsToAlarm:
              format: int64
              type: integer
            dimensions:
              additionalProperties:
                type: string
              type: object
            evaluateLowSampleCountPercentiles:
              type: string
            evaluationPeriods:
              format: int64
              type: integer
            extendedStatistic:
              type: string
            id:
              type: string
            insufficientDataActions:
              items:
                type: string
              type: array
            metricName:
              type: string
            metricQuery:
              items:
                properties:
                  ID:
                    type: string
                  expression:
                    type: string
                  label:
                    type: string
                  metric:
                    items:
                      properties:
                        dimensions:
                          additionalProperties:
                            type: string
                          type: object
                        metricName:
                          type: string
                        namespace:
                          type: string
                        period:
                          format: int64
                          type: integer
                        stat:
                          type: string
                        unit:
                          type: string
                      required:
                      - metricName
                      - period
                      - stat
                      type: object
                    maxItems: 1
                    type: array
                  returnData:
                    type: boolean
                required:
                - ID
                type: object
              type: array
            namespace:
              type: string
            okActions:
              items:
                type: string
              type: array
            period:
              format: int64
              type: integer
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            remoteBackend:
              description: Backend specifies the configuration of the terraform backend
              properties:
                ref:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                type:
                  type: string
              type: object
            statistic:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            threshold:
              format: float
              type: number
            treatMissingData:
              type: string
            unit:
              type: string
          required:
          - alarmName
          - comparisonOperator
          - evaluationPeriods
          - providerRef
          - threshold
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                actionsEnabled:
                  type: boolean
                alarmActions:
                  items:
                    type: string
                  type: array
                alarmDescription:
                  type: string
                alarmName:
                  type: string
                arn:
                  type: string
                comparisonOperator:
                  type: string
                datapointsToAlarm:
                  format: int64
                  type: integer
                dimensions:
                  additionalProperties:
                    type: string
                  type: object
                evaluateLowSampleCountPercentiles:
                  type: string
                evaluationPeriods:
                  format: int64
                  type: integer
                extendedStatistic:
                  type: string
                id:
                  type: string
                insufficientDataActions:
                  items:
                    type: string
                  type: array
                metricName:
                  type: string
                metricQuery:
                  items:
                    properties:
                      ID:
                        type: string
                      expression:
                        type: string
                      label:
                        type: string
                      metric:
                        items:
                          properties:
                            dimensions:
                              additionalProperties:
                                type: string
                              type: object
                            metricName:
                              type: string
                            namespace:
                              type: string
                            period:
                              format: int64
                              type: integer
                            stat:
                              type: string
                            unit:
                              type: string
                          required:
                          - metricName
                          - period
                          - stat
                          type: object
                        maxItems: 1
                        type: array
                      returnData:
                        type: boolean
                    required:
                    - ID
                    type: object
                  type: array
                namespace:
                  type: string
                okActions:
                  items:
                    type: string
                  type: array
                period:
                  format: int64
                  type: integer
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                remoteBackend:
                  description: Backend specifies the configuration of the terraform
                    backend
                  properties:
                    ref:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    type:
                      type: string
                  type: object
                statistic:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                threshold:
                  format: float
                  type: number
                treatMissingData:
                  type: string
                unit:
                  type: string
              required:
              - alarmName
              - comparisonOperator
              - evaluationPeriods
              - providerRef
              - threshold
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
