apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: elastictranscoderpresets.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: ElastictranscoderPreset
    listKind: ElastictranscoderPresetList
    plural: elastictranscoderpresets
    singular: elastictranscoderpreset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            arn:
              type: string
            audio:
              items:
                properties:
                  audioPackingMode:
                    type: string
                  bitRate:
                    type: string
                  channels:
                    type: string
                  codec:
                    type: string
                  sampleRate:
                    type: string
                type: object
              maxItems: 1
              type: array
            audioCodecOptions:
              items:
                properties:
                  bitDepth:
                    type: string
                  bitOrder:
                    type: string
                  profile:
                    type: string
                  signed:
                    type: string
                type: object
              maxItems: 1
              type: array
            container:
              type: string
            description:
              type: string
            id:
              type: string
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            thumbnails:
              items:
                properties:
                  aspectRatio:
                    type: string
                  format:
                    type: string
                  interval:
                    type: string
                  maxHeight:
                    type: string
                  maxWidth:
                    type: string
                  paddingPolicy:
                    type: string
                  resolution:
                    type: string
                  sizingPolicy:
                    type: string
                type: object
              maxItems: 1
              type: array
            type:
              type: string
            video:
              items:
                properties:
                  aspectRatio:
                    type: string
                  bitRate:
                    type: string
                  codec:
                    type: string
                  displayAspectRatio:
                    type: string
                  fixedGop:
                    type: string
                  frameRate:
                    type: string
                  keyframesMaxDist:
                    type: string
                  maxFrameRate:
                    type: string
                  maxHeight:
                    type: string
                  maxWidth:
                    type: string
                  paddingPolicy:
                    type: string
                  resolution:
                    type: string
                  sizingPolicy:
                    type: string
                type: object
              maxItems: 1
              type: array
            videoCodecOptions:
              additionalProperties:
                type: string
              type: object
            videoWatermarks:
              items:
                properties:
                  ID:
                    type: string
                  horizontalAlign:
                    type: string
                  horizontalOffset:
                    type: string
                  maxHeight:
                    type: string
                  maxWidth:
                    type: string
                  opacity:
                    type: string
                  sizingPolicy:
                    type: string
                  target:
                    type: string
                  verticalAlign:
                    type: string
                  verticalOffset:
                    type: string
                type: object
              type: array
          required:
          - container
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                arn:
                  type: string
                audio:
                  items:
                    properties:
                      audioPackingMode:
                        type: string
                      bitRate:
                        type: string
                      channels:
                        type: string
                      codec:
                        type: string
                      sampleRate:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                audioCodecOptions:
                  items:
                    properties:
                      bitDepth:
                        type: string
                      bitOrder:
                        type: string
                      profile:
                        type: string
                      signed:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                container:
                  type: string
                description:
                  type: string
                id:
                  type: string
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                thumbnails:
                  items:
                    properties:
                      aspectRatio:
                        type: string
                      format:
                        type: string
                      interval:
                        type: string
                      maxHeight:
                        type: string
                      maxWidth:
                        type: string
                      paddingPolicy:
                        type: string
                      resolution:
                        type: string
                      sizingPolicy:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                type:
                  type: string
                video:
                  items:
                    properties:
                      aspectRatio:
                        type: string
                      bitRate:
                        type: string
                      codec:
                        type: string
                      displayAspectRatio:
                        type: string
                      fixedGop:
                        type: string
                      frameRate:
                        type: string
                      keyframesMaxDist:
                        type: string
                      maxFrameRate:
                        type: string
                      maxHeight:
                        type: string
                      maxWidth:
                        type: string
                      paddingPolicy:
                        type: string
                      resolution:
                        type: string
                      sizingPolicy:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                videoCodecOptions:
                  additionalProperties:
                    type: string
                  type: object
                videoWatermarks:
                  items:
                    properties:
                      ID:
                        type: string
                      horizontalAlign:
                        type: string
                      horizontalOffset:
                        type: string
                      maxHeight:
                        type: string
                      maxWidth:
                        type: string
                      opacity:
                        type: string
                      sizingPolicy:
                        type: string
                      target:
                        type: string
                      verticalAlign:
                        type: string
                      verticalOffset:
                        type: string
                    type: object
                  type: array
              required:
              - container
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
