apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: autoscalinggroups.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: AutoscalingGroup
    listKind: AutoscalingGroupList
    plural: autoscalinggroups
    singular: autoscalinggroup
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            arn:
              type: string
            availabilityZones:
              items:
                type: string
              type: array
            defaultCooldown:
              format: int64
              type: integer
            desiredCapacity:
              format: int64
              type: integer
            enabledMetrics:
              items:
                type: string
              type: array
            forceDelete:
              type: boolean
            healthCheckGracePeriod:
              format: int64
              type: integer
            healthCheckType:
              type: string
            id:
              type: string
            initialLifecycleHook:
              items:
                properties:
                  defaultResult:
                    type: string
                  heartbeatTimeout:
                    format: int64
                    type: integer
                  lifecycleTransition:
                    type: string
                  name:
                    type: string
                  notificationMetadata:
                    type: string
                  notificationTargetArn:
                    type: string
                  roleArn:
                    type: string
                required:
                - lifecycleTransition
                - name
                type: object
              type: array
            launchConfiguration:
              type: string
            launchTemplate:
              items:
                properties:
                  ID:
                    type: string
                  name:
                    type: string
                  version:
                    type: string
                type: object
              maxItems: 1
              type: array
            loadBalancers:
              items:
                type: string
              type: array
            maxSize:
              format: int64
              type: integer
            metricsGranularity:
              type: string
            minElbCapacity:
              format: int64
              type: integer
            minSize:
              format: int64
              type: integer
            mixedInstancesPolicy:
              items:
                properties:
                  instancesDistribution:
                    items:
                      properties:
                        onDemandAllocationStrategy:
                          type: string
                        onDemandBaseCapacity:
                          format: int64
                          type: integer
                        onDemandPercentageAboveBaseCapacity:
                          format: int64
                          type: integer
                        spotAllocationStrategy:
                          type: string
                        spotInstancePools:
                          format: int64
                          type: integer
                        spotMaxPrice:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  launchTemplate:
                    items:
                      properties:
                        launchTemplateSpecification:
                          items:
                            properties:
                              launchTemplateID:
                                type: string
                              launchTemplateName:
                                type: string
                              version:
                                type: string
                            type: object
                          maxItems: 1
                          minItems: 1
                          type: array
                        override:
                          items:
                            properties:
                              instanceType:
                                type: string
                            type: object
                          type: array
                      required:
                      - launchTemplateSpecification
                      type: object
                    maxItems: 1
                    minItems: 1
                    type: array
                required:
                - launchTemplate
                type: object
              maxItems: 1
              type: array
            name:
              type: string
            namePrefix:
              type: string
            placementGroup:
              type: string
            protectFromScaleIn:
              type: boolean
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            serviceLinkedRoleArn:
              type: string
            suspendedProcesses:
              items:
                type: string
              type: array
            tag:
              items:
                properties:
                  key:
                    type: string
                  propagateAtLaunch:
                    type: boolean
                  value:
                    type: string
                required:
                - key
                - propagateAtLaunch
                - value
                type: object
              type: array
            targetGroupArns:
              items:
                type: string
              type: array
            terminationPolicies:
              items:
                type: string
              type: array
            vpcZoneIdentifier:
              items:
                type: string
              type: array
            waitForCapacityTimeout:
              type: string
            waitForElbCapacity:
              format: int64
              type: integer
          required:
          - maxSize
          - minSize
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                arn:
                  type: string
                availabilityZones:
                  items:
                    type: string
                  type: array
                defaultCooldown:
                  format: int64
                  type: integer
                desiredCapacity:
                  format: int64
                  type: integer
                enabledMetrics:
                  items:
                    type: string
                  type: array
                forceDelete:
                  type: boolean
                healthCheckGracePeriod:
                  format: int64
                  type: integer
                healthCheckType:
                  type: string
                id:
                  type: string
                initialLifecycleHook:
                  items:
                    properties:
                      defaultResult:
                        type: string
                      heartbeatTimeout:
                        format: int64
                        type: integer
                      lifecycleTransition:
                        type: string
                      name:
                        type: string
                      notificationMetadata:
                        type: string
                      notificationTargetArn:
                        type: string
                      roleArn:
                        type: string
                    required:
                    - lifecycleTransition
                    - name
                    type: object
                  type: array
                launchConfiguration:
                  type: string
                launchTemplate:
                  items:
                    properties:
                      ID:
                        type: string
                      name:
                        type: string
                      version:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                loadBalancers:
                  items:
                    type: string
                  type: array
                maxSize:
                  format: int64
                  type: integer
                metricsGranularity:
                  type: string
                minElbCapacity:
                  format: int64
                  type: integer
                minSize:
                  format: int64
                  type: integer
                mixedInstancesPolicy:
                  items:
                    properties:
                      instancesDistribution:
                        items:
                          properties:
                            onDemandAllocationStrategy:
                              type: string
                            onDemandBaseCapacity:
                              format: int64
                              type: integer
                            onDemandPercentageAboveBaseCapacity:
                              format: int64
                              type: integer
                            spotAllocationStrategy:
                              type: string
                            spotInstancePools:
                              format: int64
                              type: integer
                            spotMaxPrice:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      launchTemplate:
                        items:
                          properties:
                            launchTemplateSpecification:
                              items:
                                properties:
                                  launchTemplateID:
                                    type: string
                                  launchTemplateName:
                                    type: string
                                  version:
                                    type: string
                                type: object
                              maxItems: 1
                              minItems: 1
                              type: array
                            override:
                              items:
                                properties:
                                  instanceType:
                                    type: string
                                type: object
                              type: array
                          required:
                          - launchTemplateSpecification
                          type: object
                        maxItems: 1
                        minItems: 1
                        type: array
                    required:
                    - launchTemplate
                    type: object
                  maxItems: 1
                  type: array
                name:
                  type: string
                namePrefix:
                  type: string
                placementGroup:
                  type: string
                protectFromScaleIn:
                  type: boolean
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                serviceLinkedRoleArn:
                  type: string
                suspendedProcesses:
                  items:
                    type: string
                  type: array
                tag:
                  items:
                    properties:
                      key:
                        type: string
                      propagateAtLaunch:
                        type: boolean
                      value:
                        type: string
                    required:
                    - key
                    - propagateAtLaunch
                    - value
                    type: object
                  type: array
                targetGroupArns:
                  items:
                    type: string
                  type: array
                terminationPolicies:
                  items:
                    type: string
                  type: array
                vpcZoneIdentifier:
                  items:
                    type: string
                  type: array
                waitForCapacityTimeout:
                  type: string
                waitForElbCapacity:
                  format: int64
                  type: integer
              required:
              - maxSize
              - minSize
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
