apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: docdbclusters.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: DocdbCluster
    listKind: DocdbClusterList
    plural: docdbclusters
    singular: docdbcluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            applyImmediately:
              type: boolean
            arn:
              type: string
            availabilityZones:
              items:
                type: string
              type: array
            backupRetentionPeriod:
              format: int64
              type: integer
            clusterIdentifier:
              type: string
            clusterIdentifierPrefix:
              type: string
            clusterMembers:
              items:
                type: string
              type: array
            clusterResourceID:
              type: string
            dbClusterParameterGroupName:
              type: string
            dbSubnetGroupName:
              type: string
            enabledCloudwatchLogsExports:
              items:
                type: string
              type: array
            endpoint:
              type: string
            engine:
              type: string
            engineVersion:
              type: string
            finalSnapshotIdentifier:
              type: string
            hostedZoneID:
              type: string
            id:
              type: string
            kmsKeyID:
              type: string
            masterUsername:
              type: string
            port:
              format: int64
              type: integer
            preferredBackupWindow:
              type: string
            preferredMaintenanceWindow:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            readerEndpoint:
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            skipFinalSnapshot:
              type: boolean
            snapshotIdentifier:
              type: string
            storageEncrypted:
              type: boolean
            tags:
              additionalProperties:
                type: string
              type: object
            vpcSecurityGroupIDS:
              items:
                type: string
              type: array
          required:
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                applyImmediately:
                  type: boolean
                arn:
                  type: string
                availabilityZones:
                  items:
                    type: string
                  type: array
                backupRetentionPeriod:
                  format: int64
                  type: integer
                clusterIdentifier:
                  type: string
                clusterIdentifierPrefix:
                  type: string
                clusterMembers:
                  items:
                    type: string
                  type: array
                clusterResourceID:
                  type: string
                dbClusterParameterGroupName:
                  type: string
                dbSubnetGroupName:
                  type: string
                enabledCloudwatchLogsExports:
                  items:
                    type: string
                  type: array
                endpoint:
                  type: string
                engine:
                  type: string
                engineVersion:
                  type: string
                finalSnapshotIdentifier:
                  type: string
                hostedZoneID:
                  type: string
                id:
                  type: string
                kmsKeyID:
                  type: string
                masterUsername:
                  type: string
                port:
                  format: int64
                  type: integer
                preferredBackupWindow:
                  type: string
                preferredMaintenanceWindow:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                readerEndpoint:
                  type: string
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                skipFinalSnapshot:
                  type: boolean
                snapshotIdentifier:
                  type: string
                storageEncrypted:
                  type: boolean
                tags:
                  additionalProperties:
                    type: string
                  type: object
                vpcSecurityGroupIDS:
                  items:
                    type: string
                  type: array
              required:
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
