apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: route53records.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: Route53Record
    listKind: Route53RecordList
    plural: route53records
    singular: route53record
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            alias:
              items:
                properties:
                  evaluateTargetHealth:
                    type: boolean
                  name:
                    type: string
                  zoneID:
                    type: string
                required:
                - evaluateTargetHealth
                - name
                - zoneID
                type: object
              type: array
            allowOverwrite:
              type: boolean
            failoverRoutingPolicy:
              items:
                properties:
                  type:
                    type: string
                required:
                - type
                type: object
              type: array
            fqdn:
              type: string
            geolocationRoutingPolicy:
              items:
                properties:
                  continent:
                    type: string
                  country:
                    type: string
                  subdivision:
                    type: string
                type: object
              type: array
            healthCheckID:
              type: string
            id:
              type: string
            latencyRoutingPolicy:
              items:
                properties:
                  region:
                    type: string
                required:
                - region
                type: object
              type: array
            multivalueAnswerRoutingPolicy:
              type: boolean
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            records:
              items:
                type: string
              type: array
            remoteBackend:
              description: Backend specifies the configuration of the terraform backend
              properties:
                ref:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                type:
                  type: string
              type: object
            setIdentifier:
              type: string
            ttl:
              format: int64
              type: integer
            type:
              type: string
            weightedRoutingPolicy:
              items:
                properties:
                  weight:
                    format: int64
                    type: integer
                required:
                - weight
                type: object
              type: array
            zoneID:
              type: string
          required:
          - name
          - providerRef
          - type
          - zoneID
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                alias:
                  items:
                    properties:
                      evaluateTargetHealth:
                        type: boolean
                      name:
                        type: string
                      zoneID:
                        type: string
                    required:
                    - evaluateTargetHealth
                    - name
                    - zoneID
                    type: object
                  type: array
                allowOverwrite:
                  type: boolean
                failoverRoutingPolicy:
                  items:
                    properties:
                      type:
                        type: string
                    required:
                    - type
                    type: object
                  type: array
                fqdn:
                  type: string
                geolocationRoutingPolicy:
                  items:
                    properties:
                      continent:
                        type: string
                      country:
                        type: string
                      subdivision:
                        type: string
                    type: object
                  type: array
                healthCheckID:
                  type: string
                id:
                  type: string
                latencyRoutingPolicy:
                  items:
                    properties:
                      region:
                        type: string
                    required:
                    - region
                    type: object
                  type: array
                multivalueAnswerRoutingPolicy:
                  type: boolean
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                records:
                  items:
                    type: string
                  type: array
                remoteBackend:
                  description: Backend specifies the configuration of the terraform
                    backend
                  properties:
                    ref:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    type:
                      type: string
                  type: object
                setIdentifier:
                  type: string
                ttl:
                  format: int64
                  type: integer
                type:
                  type: string
                weightedRoutingPolicy:
                  items:
                    properties:
                      weight:
                        format: int64
                        type: integer
                    required:
                    - weight
                    type: object
                  type: array
                zoneID:
                  type: string
              required:
              - name
              - providerRef
              - type
              - zoneID
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
