apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: daxclusters.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: DaxCluster
    listKind: DaxClusterList
    plural: daxclusters
    singular: daxcluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            arn:
              type: string
            availabilityZones:
              items:
                type: string
              type: array
            clusterAddress:
              type: string
            clusterName:
              type: string
            configurationEndpoint:
              type: string
            description:
              type: string
            iamRoleArn:
              type: string
            id:
              type: string
            maintenanceWindow:
              type: string
            nodeType:
              type: string
            nodes:
              items:
                properties:
                  ID:
                    type: string
                  address:
                    type: string
                  availabilityZone:
                    type: string
                  port:
                    format: int64
                    type: integer
                type: object
              type: array
            notificationTopicArn:
              type: string
            parameterGroupName:
              type: string
            port:
              format: int64
              type: integer
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            remoteBackend:
              description: Backend specifies the configuration of the terraform backend
              properties:
                ref:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                type:
                  type: string
              type: object
            replicationFactor:
              format: int64
              type: integer
            securityGroupIDS:
              items:
                type: string
              type: array
            serverSideEncryption:
              items:
                properties:
                  enabled:
                    type: boolean
                type: object
              maxItems: 1
              type: array
            subnetGroupName:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
          required:
          - clusterName
          - iamRoleArn
          - nodeType
          - providerRef
          - replicationFactor
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                arn:
                  type: string
                availabilityZones:
                  items:
                    type: string
                  type: array
                clusterAddress:
                  type: string
                clusterName:
                  type: string
                configurationEndpoint:
                  type: string
                description:
                  type: string
                iamRoleArn:
                  type: string
                id:
                  type: string
                maintenanceWindow:
                  type: string
                nodeType:
                  type: string
                nodes:
                  items:
                    properties:
                      ID:
                        type: string
                      address:
                        type: string
                      availabilityZone:
                        type: string
                      port:
                        format: int64
                        type: integer
                    type: object
                  type: array
                notificationTopicArn:
                  type: string
                parameterGroupName:
                  type: string
                port:
                  format: int64
                  type: integer
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                remoteBackend:
                  description: Backend specifies the configuration of the terraform
                    backend
                  properties:
                    ref:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    type:
                      type: string
                  type: object
                replicationFactor:
                  format: int64
                  type: integer
                securityGroupIDS:
                  items:
                    type: string
                  type: array
                serverSideEncryption:
                  items:
                    properties:
                      enabled:
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
                subnetGroupName:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
              required:
              - clusterName
              - iamRoleArn
              - nodeType
              - providerRef
              - replicationFactor
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
