apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: elasticbeanstalkenvironments.aws.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: aws.kubeform.com
  names:
    kind: ElasticBeanstalkEnvironment
    listKind: ElasticBeanstalkEnvironmentList
    plural: elasticbeanstalkenvironments
    singular: elasticbeanstalkenvironment
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            allSettings:
              items:
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                  resource:
                    type: string
                  value:
                    type: string
                required:
                - name
                - namespace
                - value
                type: object
              type: array
            application:
              type: string
            arn:
              type: string
            autoscalingGroups:
              items:
                type: string
              type: array
            cname:
              type: string
            cnamePrefix:
              type: string
            description:
              type: string
            endpointURL:
              type: string
            id:
              type: string
            instances:
              items:
                type: string
              type: array
            launchConfigurations:
              items:
                type: string
              type: array
            loadBalancers:
              items:
                type: string
              type: array
            name:
              type: string
            platformArn:
              type: string
            pollInterval:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            queues:
              items:
                type: string
              type: array
            setting:
              items:
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                  resource:
                    type: string
                  value:
                    type: string
                required:
                - name
                - namespace
                - value
                type: object
              type: array
            solutionStackName:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            templateName:
              type: string
            tier:
              type: string
            triggers:
              items:
                type: string
              type: array
            versionLabel:
              type: string
            waitForReadyTimeout:
              type: string
          required:
          - application
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                allSettings:
                  items:
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      resource:
                        type: string
                      value:
                        type: string
                    required:
                    - name
                    - namespace
                    - value
                    type: object
                  type: array
                application:
                  type: string
                arn:
                  type: string
                autoscalingGroups:
                  items:
                    type: string
                  type: array
                cname:
                  type: string
                cnamePrefix:
                  type: string
                description:
                  type: string
                endpointURL:
                  type: string
                id:
                  type: string
                instances:
                  items:
                    type: string
                  type: array
                launchConfigurations:
                  items:
                    type: string
                  type: array
                loadBalancers:
                  items:
                    type: string
                  type: array
                name:
                  type: string
                platformArn:
                  type: string
                pollInterval:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                queues:
                  items:
                    type: string
                  type: array
                setting:
                  items:
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      resource:
                        type: string
                      value:
                        type: string
                    required:
                    - name
                    - namespace
                    - value
                    type: object
                  type: array
                solutionStackName:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                templateName:
                  type: string
                tier:
                  type: string
                triggers:
                  items:
                    type: string
                  type: array
                versionLabel:
                  type: string
                waitForReadyTimeout:
                  type: string
              required:
              - application
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
