apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: apimanagementapioperations.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: ApiManagementAPIOperation
    listKind: ApiManagementAPIOperationList
    plural: apimanagementapioperations
    singular: apimanagementapioperation
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            apiManagementName:
              type: string
            apiName:
              type: string
            description:
              type: string
            displayName:
              type: string
            id:
              type: string
            method:
              type: string
            operationID:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            request:
              items:
                properties:
                  description:
                    type: string
                  header:
                    items:
                      properties:
                        defaultValue:
                          type: string
                        description:
                          type: string
                        name:
                          type: string
                        required:
                          type: boolean
                        type:
                          type: string
                        values:
                          items:
                            type: string
                          type: array
                      required:
                      - name
                      - required
                      - type
                      type: object
                    type: array
                  queryParameter:
                    items:
                      properties:
                        defaultValue:
                          type: string
                        description:
                          type: string
                        name:
                          type: string
                        required:
                          type: boolean
                        type:
                          type: string
                        values:
                          items:
                            type: string
                          type: array
                      required:
                      - name
                      - required
                      - type
                      type: object
                    type: array
                  representation:
                    items:
                      properties:
                        contentType:
                          type: string
                        formParameter:
                          items:
                            properties:
                              defaultValue:
                                type: string
                              description:
                                type: string
                              name:
                                type: string
                              required:
                                type: boolean
                              type:
                                type: string
                              values:
                                items:
                                  type: string
                                type: array
                            required:
                            - name
                            - required
                            - type
                            type: object
                          type: array
                        sample:
                          type: string
                        schemaID:
                          type: string
                        typeName:
                          type: string
                      required:
                      - contentType
                      type: object
                    type: array
                type: object
              maxItems: 1
              type: array
            resourceGroupName:
              type: string
            response:
              items:
                properties:
                  description:
                    type: string
                  header:
                    items:
                      properties:
                        defaultValue:
                          type: string
                        description:
                          type: string
                        name:
                          type: string
                        required:
                          type: boolean
                        type:
                          type: string
                        values:
                          items:
                            type: string
                          type: array
                      required:
                      - name
                      - required
                      - type
                      type: object
                    type: array
                  representation:
                    items:
                      properties:
                        contentType:
                          type: string
                        formParameter:
                          items:
                            properties:
                              defaultValue:
                                type: string
                              description:
                                type: string
                              name:
                                type: string
                              required:
                                type: boolean
                              type:
                                type: string
                              values:
                                items:
                                  type: string
                                type: array
                            required:
                            - name
                            - required
                            - type
                            type: object
                          type: array
                        sample:
                          type: string
                        schemaID:
                          type: string
                        typeName:
                          type: string
                      required:
                      - contentType
                      type: object
                    type: array
                  statusCode:
                    format: int64
                    type: integer
                required:
                - statusCode
                type: object
              type: array
            templateParameter:
              items:
                properties:
                  defaultValue:
                    type: string
                  description:
                    type: string
                  name:
                    type: string
                  required:
                    type: boolean
                  type:
                    type: string
                  values:
                    items:
                      type: string
                    type: array
                required:
                - name
                - required
                - type
                type: object
              type: array
            urlTemplate:
              type: string
          required:
          - apiManagementName
          - apiName
          - displayName
          - method
          - operationID
          - providerRef
          - resourceGroupName
          - urlTemplate
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                apiManagementName:
                  type: string
                apiName:
                  type: string
                description:
                  type: string
                displayName:
                  type: string
                id:
                  type: string
                method:
                  type: string
                operationID:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                request:
                  items:
                    properties:
                      description:
                        type: string
                      header:
                        items:
                          properties:
                            defaultValue:
                              type: string
                            description:
                              type: string
                            name:
                              type: string
                            required:
                              type: boolean
                            type:
                              type: string
                            values:
                              items:
                                type: string
                              type: array
                          required:
                          - name
                          - required
                          - type
                          type: object
                        type: array
                      queryParameter:
                        items:
                          properties:
                            defaultValue:
                              type: string
                            description:
                              type: string
                            name:
                              type: string
                            required:
                              type: boolean
                            type:
                              type: string
                            values:
                              items:
                                type: string
                              type: array
                          required:
                          - name
                          - required
                          - type
                          type: object
                        type: array
                      representation:
                        items:
                          properties:
                            contentType:
                              type: string
                            formParameter:
                              items:
                                properties:
                                  defaultValue:
                                    type: string
                                  description:
                                    type: string
                                  name:
                                    type: string
                                  required:
                                    type: boolean
                                  type:
                                    type: string
                                  values:
                                    items:
                                      type: string
                                    type: array
                                required:
                                - name
                                - required
                                - type
                                type: object
                              type: array
                            sample:
                              type: string
                            schemaID:
                              type: string
                            typeName:
                              type: string
                          required:
                          - contentType
                          type: object
                        type: array
                    type: object
                  maxItems: 1
                  type: array
                resourceGroupName:
                  type: string
                response:
                  items:
                    properties:
                      description:
                        type: string
                      header:
                        items:
                          properties:
                            defaultValue:
                              type: string
                            description:
                              type: string
                            name:
                              type: string
                            required:
                              type: boolean
                            type:
                              type: string
                            values:
                              items:
                                type: string
                              type: array
                          required:
                          - name
                          - required
                          - type
                          type: object
                        type: array
                      representation:
                        items:
                          properties:
                            contentType:
                              type: string
                            formParameter:
                              items:
                                properties:
                                  defaultValue:
                                    type: string
                                  description:
                                    type: string
                                  name:
                                    type: string
                                  required:
                                    type: boolean
                                  type:
                                    type: string
                                  values:
                                    items:
                                      type: string
                                    type: array
                                required:
                                - name
                                - required
                                - type
                                type: object
                              type: array
                            sample:
                              type: string
                            schemaID:
                              type: string
                            typeName:
                              type: string
                          required:
                          - contentType
                          type: object
                        type: array
                      statusCode:
                        format: int64
                        type: integer
                    required:
                    - statusCode
                    type: object
                  type: array
                templateParameter:
                  items:
                    properties:
                      defaultValue:
                        type: string
                      description:
                        type: string
                      name:
                        type: string
                      required:
                        type: boolean
                      type:
                        type: string
                      values:
                        items:
                          type: string
                        type: array
                    required:
                    - name
                    - required
                    - type
                    type: object
                  type: array
                urlTemplate:
                  type: string
              required:
              - apiManagementName
              - apiName
              - displayName
              - method
              - operationID
              - providerRef
              - resourceGroupName
              - urlTemplate
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
