apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: schedulerjobs.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: SchedulerJob
    listKind: SchedulerJobList
    plural: schedulerjobs
    singular: schedulerjob
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            actionStorageQueue:
              items:
                properties:
                  message:
                    type: string
                  sasToken:
                    type: string
                  storageAccountName:
                    type: string
                  storageQueueName:
                    type: string
                required:
                - message
                - sasToken
                - storageAccountName
                - storageQueueName
                type: object
              maxItems: 1
              type: array
            actionWeb:
              items:
                properties:
                  authenticationActiveDirectory:
                    items:
                      properties:
                        audience:
                          type: string
                        clientID:
                          type: string
                        tenantID:
                          type: string
                      required:
                      - clientID
                      - tenantID
                      type: object
                    maxItems: 1
                    type: array
                  authenticationBasic:
                    items:
                      properties:
                        username:
                          type: string
                      required:
                      - username
                      type: object
                    maxItems: 1
                    type: array
                  authenticationCertificate:
                    items:
                      properties:
                        expiration:
                          type: string
                        subjectName:
                          type: string
                        thumbprint:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  body:
                    type: string
                  headers:
                    additionalProperties:
                      type: string
                    type: object
                  method:
                    type: string
                  url:
                    type: string
                required:
                - method
                - url
                type: object
              maxItems: 1
              type: array
            errorActionStorageQueue:
              items:
                properties:
                  message:
                    type: string
                  sasToken:
                    type: string
                  storageAccountName:
                    type: string
                  storageQueueName:
                    type: string
                required:
                - message
                - sasToken
                - storageAccountName
                - storageQueueName
                type: object
              maxItems: 1
              type: array
            errorActionWeb:
              items:
                properties:
                  authenticationActiveDirectory:
                    items:
                      properties:
                        audience:
                          type: string
                        clientID:
                          type: string
                        tenantID:
                          type: string
                      required:
                      - clientID
                      - tenantID
                      type: object
                    maxItems: 1
                    type: array
                  authenticationBasic:
                    items:
                      properties:
                        username:
                          type: string
                      required:
                      - username
                      type: object
                    maxItems: 1
                    type: array
                  authenticationCertificate:
                    items:
                      properties:
                        expiration:
                          type: string
                        subjectName:
                          type: string
                        thumbprint:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  body:
                    type: string
                  headers:
                    additionalProperties:
                      type: string
                    type: object
                  method:
                    type: string
                  url:
                    type: string
                required:
                - method
                - url
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            jobCollectionName:
              type: string
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            recurrence:
              items:
                properties:
                  count:
                    format: int64
                    type: integer
                  endTime:
                    type: string
                  frequency:
                    type: string
                  hours:
                    items:
                      format: int64
                      type: integer
                    type: array
                  interval:
                    format: int64
                    type: integer
                  minutes:
                    items:
                      format: int64
                      type: integer
                    type: array
                  monthDays:
                    items:
                      format: int64
                      type: integer
                    minItems: 1
                    type: array
                  monthlyOccurrences:
                    items:
                      properties:
                        day:
                          type: string
                        occurrence:
                          format: int64
                          type: integer
                      required:
                      - day
                      - occurrence
                      type: object
                    minItems: 1
                    type: array
                  weekDays:
                    items:
                      type: string
                    type: array
                required:
                - frequency
                type: object
              maxItems: 1
              minItems: 1
              type: array
            resourceGroupName:
              type: string
            retry:
              items:
                properties:
                  count:
                    format: int64
                    type: integer
                  interval:
                    type: string
                type: object
              maxItems: 1
              type: array
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            startTime:
              type: string
            state:
              type: string
          required:
          - jobCollectionName
          - name
          - providerRef
          - resourceGroupName
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                actionStorageQueue:
                  items:
                    properties:
                      message:
                        type: string
                      sasToken:
                        type: string
                      storageAccountName:
                        type: string
                      storageQueueName:
                        type: string
                    required:
                    - message
                    - sasToken
                    - storageAccountName
                    - storageQueueName
                    type: object
                  maxItems: 1
                  type: array
                actionWeb:
                  items:
                    properties:
                      authenticationActiveDirectory:
                        items:
                          properties:
                            audience:
                              type: string
                            clientID:
                              type: string
                            tenantID:
                              type: string
                          required:
                          - clientID
                          - tenantID
                          type: object
                        maxItems: 1
                        type: array
                      authenticationBasic:
                        items:
                          properties:
                            username:
                              type: string
                          required:
                          - username
                          type: object
                        maxItems: 1
                        type: array
                      authenticationCertificate:
                        items:
                          properties:
                            expiration:
                              type: string
                            subjectName:
                              type: string
                            thumbprint:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      body:
                        type: string
                      headers:
                        additionalProperties:
                          type: string
                        type: object
                      method:
                        type: string
                      url:
                        type: string
                    required:
                    - method
                    - url
                    type: object
                  maxItems: 1
                  type: array
                errorActionStorageQueue:
                  items:
                    properties:
                      message:
                        type: string
                      sasToken:
                        type: string
                      storageAccountName:
                        type: string
                      storageQueueName:
                        type: string
                    required:
                    - message
                    - sasToken
                    - storageAccountName
                    - storageQueueName
                    type: object
                  maxItems: 1
                  type: array
                errorActionWeb:
                  items:
                    properties:
                      authenticationActiveDirectory:
                        items:
                          properties:
                            audience:
                              type: string
                            clientID:
                              type: string
                            tenantID:
                              type: string
                          required:
                          - clientID
                          - tenantID
                          type: object
                        maxItems: 1
                        type: array
                      authenticationBasic:
                        items:
                          properties:
                            username:
                              type: string
                          required:
                          - username
                          type: object
                        maxItems: 1
                        type: array
                      authenticationCertificate:
                        items:
                          properties:
                            expiration:
                              type: string
                            subjectName:
                              type: string
                            thumbprint:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      body:
                        type: string
                      headers:
                        additionalProperties:
                          type: string
                        type: object
                      method:
                        type: string
                      url:
                        type: string
                    required:
                    - method
                    - url
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                jobCollectionName:
                  type: string
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                recurrence:
                  items:
                    properties:
                      count:
                        format: int64
                        type: integer
                      endTime:
                        type: string
                      frequency:
                        type: string
                      hours:
                        items:
                          format: int64
                          type: integer
                        type: array
                      interval:
                        format: int64
                        type: integer
                      minutes:
                        items:
                          format: int64
                          type: integer
                        type: array
                      monthDays:
                        items:
                          format: int64
                          type: integer
                        minItems: 1
                        type: array
                      monthlyOccurrences:
                        items:
                          properties:
                            day:
                              type: string
                            occurrence:
                              format: int64
                              type: integer
                          required:
                          - day
                          - occurrence
                          type: object
                        minItems: 1
                        type: array
                      weekDays:
                        items:
                          type: string
                        type: array
                    required:
                    - frequency
                    type: object
                  maxItems: 1
                  minItems: 1
                  type: array
                resourceGroupName:
                  type: string
                retry:
                  items:
                    properties:
                      count:
                        format: int64
                        type: integer
                      interval:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                startTime:
                  type: string
                state:
                  type: string
              required:
              - jobCollectionName
              - name
              - providerRef
              - resourceGroupName
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
