apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: networkinterfaces.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: NetworkInterface
    listKind: NetworkInterfaceList
    plural: networkinterfaces
    singular: networkinterface
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            appliedDNSServers:
              items:
                type: string
              type: array
            dnsServers:
              items:
                type: string
              type: array
            enableAcceleratedNetworking:
              type: boolean
            enableIPForwarding:
              type: boolean
            id:
              type: string
            internalDNSNameLabel:
              type: string
            internalFqdn:
              description: Deprecated
              type: string
            ipConfiguration:
              items:
                properties:
                  applicationGatewayBackendAddressPoolsIDS:
                    description: Deprecated
                    items:
                      type: string
                    type: array
                  applicationSecurityGroupIDS:
                    description: Deprecated
                    items:
                      type: string
                    type: array
                  loadBalancerBackendAddressPoolsIDS:
                    description: Deprecated
                    items:
                      type: string
                    type: array
                  loadBalancerInboundNATRulesIDS:
                    description: Deprecated
                    items:
                      type: string
                    type: array
                  name:
                    type: string
                  primary:
                    type: boolean
                  privateIPAddress:
                    type: string
                  privateIPAddressAllocation:
                    type: string
                  privateIPAddressVersion:
                    type: string
                  publicIPAddressID:
                    type: string
                  subnetID:
                    type: string
                required:
                - name
                - privateIPAddressAllocation
                type: object
              type: array
            location:
              type: string
            macAddress:
              type: string
            name:
              type: string
            networkSecurityGroupID:
              type: string
            privateIPAddress:
              type: string
            privateIPAddresses:
              items:
                type: string
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            remoteBackend:
              description: Backend specifies the configuration of the terraform backend
              properties:
                ref:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                type:
                  type: string
              type: object
            resourceGroupName:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            virtualMachineID:
              type: string
          required:
          - ipConfiguration
          - location
          - name
          - providerRef
          - resourceGroupName
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                appliedDNSServers:
                  items:
                    type: string
                  type: array
                dnsServers:
                  items:
                    type: string
                  type: array
                enableAcceleratedNetworking:
                  type: boolean
                enableIPForwarding:
                  type: boolean
                id:
                  type: string
                internalDNSNameLabel:
                  type: string
                internalFqdn:
                  description: Deprecated
                  type: string
                ipConfiguration:
                  items:
                    properties:
                      applicationGatewayBackendAddressPoolsIDS:
                        description: Deprecated
                        items:
                          type: string
                        type: array
                      applicationSecurityGroupIDS:
                        description: Deprecated
                        items:
                          type: string
                        type: array
                      loadBalancerBackendAddressPoolsIDS:
                        description: Deprecated
                        items:
                          type: string
                        type: array
                      loadBalancerInboundNATRulesIDS:
                        description: Deprecated
                        items:
                          type: string
                        type: array
                      name:
                        type: string
                      primary:
                        type: boolean
                      privateIPAddress:
                        type: string
                      privateIPAddressAllocation:
                        type: string
                      privateIPAddressVersion:
                        type: string
                      publicIPAddressID:
                        type: string
                      subnetID:
                        type: string
                    required:
                    - name
                    - privateIPAddressAllocation
                    type: object
                  type: array
                location:
                  type: string
                macAddress:
                  type: string
                name:
                  type: string
                networkSecurityGroupID:
                  type: string
                privateIPAddress:
                  type: string
                privateIPAddresses:
                  items:
                    type: string
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                remoteBackend:
                  description: Backend specifies the configuration of the terraform
                    backend
                  properties:
                    ref:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    type:
                      type: string
                  type: object
                resourceGroupName:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                virtualMachineID:
                  type: string
              required:
              - ipConfiguration
              - location
              - name
              - providerRef
              - resourceGroupName
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
