apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: eventgrideventsubscriptions.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: EventgridEventSubscription
    listKind: EventgridEventSubscriptionList
    plural: eventgrideventsubscriptions
    singular: eventgrideventsubscription
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            eventDeliverySchema:
              type: string
            eventhubEndpoint:
              items:
                properties:
                  eventhubID:
                    type: string
                required:
                - eventhubID
                type: object
              maxItems: 1
              type: array
            hybridConnectionEndpoint:
              items:
                properties:
                  hybridConnectionID:
                    type: string
                required:
                - hybridConnectionID
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            includedEventTypes:
              items:
                type: string
              type: array
            labels:
              items:
                type: string
              type: array
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            retryPolicy:
              items:
                properties:
                  eventTimeToLive:
                    format: int64
                    type: integer
                  maxDeliveryAttempts:
                    format: int64
                    type: integer
                required:
                - eventTimeToLive
                - maxDeliveryAttempts
                type: object
              maxItems: 1
              type: array
            scope:
              type: string
            storageBlobDeadLetterDestination:
              items:
                properties:
                  storageAccountID:
                    type: string
                  storageBlobContainerName:
                    type: string
                required:
                - storageAccountID
                - storageBlobContainerName
                type: object
              maxItems: 1
              type: array
            storageQueueEndpoint:
              items:
                properties:
                  queueName:
                    type: string
                  storageAccountID:
                    type: string
                required:
                - queueName
                - storageAccountID
                type: object
              maxItems: 1
              type: array
            subjectFilter:
              items:
                properties:
                  caseSensitive:
                    type: boolean
                  subjectBeginsWith:
                    type: string
                  subjectEndsWith:
                    type: string
                type: object
              maxItems: 1
              type: array
            topicName:
              type: string
            webhookEndpoint:
              items:
                properties:
                  url:
                    type: string
                required:
                - url
                type: object
              maxItems: 1
              type: array
          required:
          - name
          - providerRef
          - scope
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                eventDeliverySchema:
                  type: string
                eventhubEndpoint:
                  items:
                    properties:
                      eventhubID:
                        type: string
                    required:
                    - eventhubID
                    type: object
                  maxItems: 1
                  type: array
                hybridConnectionEndpoint:
                  items:
                    properties:
                      hybridConnectionID:
                        type: string
                    required:
                    - hybridConnectionID
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                includedEventTypes:
                  items:
                    type: string
                  type: array
                labels:
                  items:
                    type: string
                  type: array
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                retryPolicy:
                  items:
                    properties:
                      eventTimeToLive:
                        format: int64
                        type: integer
                      maxDeliveryAttempts:
                        format: int64
                        type: integer
                    required:
                    - eventTimeToLive
                    - maxDeliveryAttempts
                    type: object
                  maxItems: 1
                  type: array
                scope:
                  type: string
                storageBlobDeadLetterDestination:
                  items:
                    properties:
                      storageAccountID:
                        type: string
                      storageBlobContainerName:
                        type: string
                    required:
                    - storageAccountID
                    - storageBlobContainerName
                    type: object
                  maxItems: 1
                  type: array
                storageQueueEndpoint:
                  items:
                    properties:
                      queueName:
                        type: string
                      storageAccountID:
                        type: string
                    required:
                    - queueName
                    - storageAccountID
                    type: object
                  maxItems: 1
                  type: array
                subjectFilter:
                  items:
                    properties:
                      caseSensitive:
                        type: boolean
                      subjectBeginsWith:
                        type: string
                      subjectEndsWith:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                topicName:
                  type: string
                webhookEndpoint:
                  items:
                    properties:
                      url:
                        type: string
                    required:
                    - url
                    type: object
                  maxItems: 1
                  type: array
              required:
              - name
              - providerRef
              - scope
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
