apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: hdinsightrserverclusters.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: HdinsightRserverCluster
    listKind: HdinsightRserverClusterList
    plural: hdinsightrserverclusters
    singular: hdinsightrservercluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterVersion:
              type: string
            edgeSSHEndpoint:
              type: string
            gateway:
              items:
                properties:
                  enabled:
                    type: boolean
                  username:
                    type: string
                required:
                - enabled
                - username
                type: object
              maxItems: 1
              type: array
            httpsEndpoint:
              type: string
            id:
              type: string
            location:
              type: string
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            remoteBackend:
              description: Backend specifies the configuration of the terraform backend
              properties:
                ref:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                type:
                  type: string
              type: object
            resourceGroupName:
              type: string
            roles:
              items:
                properties:
                  edgeNode:
                    items:
                      properties:
                        sshKeys:
                          items:
                            type: string
                          type: array
                        subnetID:
                          type: string
                        username:
                          type: string
                        virtualNetworkID:
                          type: string
                        vmSize:
                          type: string
                      required:
                      - username
                      - vmSize
                      type: object
                    maxItems: 1
                    type: array
                  headNode:
                    items:
                      properties:
                        sshKeys:
                          items:
                            type: string
                          type: array
                        subnetID:
                          type: string
                        username:
                          type: string
                        virtualNetworkID:
                          type: string
                        vmSize:
                          type: string
                      required:
                      - username
                      - vmSize
                      type: object
                    maxItems: 1
                    type: array
                  workerNode:
                    items:
                      properties:
                        minInstanceCount:
                          format: int64
                          type: integer
                        sshKeys:
                          items:
                            type: string
                          type: array
                        subnetID:
                          type: string
                        targetInstanceCount:
                          format: int64
                          type: integer
                        username:
                          type: string
                        virtualNetworkID:
                          type: string
                        vmSize:
                          type: string
                      required:
                      - targetInstanceCount
                      - username
                      - vmSize
                      type: object
                    maxItems: 1
                    type: array
                  zookeeperNode:
                    items:
                      properties:
                        sshKeys:
                          items:
                            type: string
                          type: array
                        subnetID:
                          type: string
                        username:
                          type: string
                        virtualNetworkID:
                          type: string
                        vmSize:
                          type: string
                      required:
                      - username
                      - vmSize
                      type: object
                    maxItems: 1
                    type: array
                required:
                - edgeNode
                - headNode
                - workerNode
                - zookeeperNode
                type: object
              maxItems: 1
              type: array
            rstudio:
              type: boolean
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            sshEndpoint:
              type: string
            storageAccount:
              items:
                properties:
                  isDefault:
                    type: boolean
                  storageContainerID:
                    type: string
                required:
                - isDefault
                - storageContainerID
                type: object
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
            tier:
              type: string
          required:
          - clusterVersion
          - gateway
          - location
          - name
          - providerRef
          - resourceGroupName
          - roles
          - rstudio
          - tier
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                clusterVersion:
                  type: string
                edgeSSHEndpoint:
                  type: string
                gateway:
                  items:
                    properties:
                      enabled:
                        type: boolean
                      username:
                        type: string
                    required:
                    - enabled
                    - username
                    type: object
                  maxItems: 1
                  type: array
                httpsEndpoint:
                  type: string
                id:
                  type: string
                location:
                  type: string
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                remoteBackend:
                  description: Backend specifies the configuration of the terraform
                    backend
                  properties:
                    ref:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    type:
                      type: string
                  type: object
                resourceGroupName:
                  type: string
                roles:
                  items:
                    properties:
                      edgeNode:
                        items:
                          properties:
                            sshKeys:
                              items:
                                type: string
                              type: array
                            subnetID:
                              type: string
                            username:
                              type: string
                            virtualNetworkID:
                              type: string
                            vmSize:
                              type: string
                          required:
                          - username
                          - vmSize
                          type: object
                        maxItems: 1
                        type: array
                      headNode:
                        items:
                          properties:
                            sshKeys:
                              items:
                                type: string
                              type: array
                            subnetID:
                              type: string
                            username:
                              type: string
                            virtualNetworkID:
                              type: string
                            vmSize:
                              type: string
                          required:
                          - username
                          - vmSize
                          type: object
                        maxItems: 1
                        type: array
                      workerNode:
                        items:
                          properties:
                            minInstanceCount:
                              format: int64
                              type: integer
                            sshKeys:
                              items:
                                type: string
                              type: array
                            subnetID:
                              type: string
                            targetInstanceCount:
                              format: int64
                              type: integer
                            username:
                              type: string
                            virtualNetworkID:
                              type: string
                            vmSize:
                              type: string
                          required:
                          - targetInstanceCount
                          - username
                          - vmSize
                          type: object
                        maxItems: 1
                        type: array
                      zookeeperNode:
                        items:
                          properties:
                            sshKeys:
                              items:
                                type: string
                              type: array
                            subnetID:
                              type: string
                            username:
                              type: string
                            virtualNetworkID:
                              type: string
                            vmSize:
                              type: string
                          required:
                          - username
                          - vmSize
                          type: object
                        maxItems: 1
                        type: array
                    required:
                    - edgeNode
                    - headNode
                    - workerNode
                    - zookeeperNode
                    type: object
                  maxItems: 1
                  type: array
                rstudio:
                  type: boolean
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                sshEndpoint:
                  type: string
                storageAccount:
                  items:
                    properties:
                      isDefault:
                        type: boolean
                      storageContainerID:
                        type: string
                    required:
                    - isDefault
                    - storageContainerID
                    type: object
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
                tier:
                  type: string
              required:
              - clusterVersion
              - gateway
              - location
              - name
              - providerRef
              - resourceGroupName
              - roles
              - rstudio
              - tier
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
