apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: keyvaults.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: KeyVault
    listKind: KeyVaultList
    plural: keyvaults
    singular: keyvault
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            accessPolicy:
              items:
                properties:
                  applicationID:
                    type: string
                  certificatePermissions:
                    items:
                      type: string
                    type: array
                  keyPermissions:
                    items:
                      type: string
                    type: array
                  objectID:
                    type: string
                  secretPermissions:
                    items:
                      type: string
                    type: array
                  storagePermissions:
                    items:
                      type: string
                    type: array
                  tenantID:
                    type: string
                required:
                - objectID
                - tenantID
                type: object
              maxItems: 1024
              type: array
            enabledForDeployment:
              type: boolean
            enabledForDiskEncryption:
              type: boolean
            enabledForTemplateDeployment:
              type: boolean
            id:
              type: string
            location:
              type: string
            name:
              type: string
            networkAcls:
              items:
                properties:
                  bypass:
                    type: string
                  defaultAction:
                    type: string
                  ipRules:
                    items:
                      type: string
                    type: array
                  virtualNetworkSubnetIDS:
                    items:
                      type: string
                    type: array
                required:
                - bypass
                - defaultAction
                type: object
              maxItems: 1
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            remoteBackend:
              description: Backend specifies the configuration of the terraform backend
              properties:
                ref:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                type:
                  type: string
              type: object
            resourceGroupName:
              type: string
            sku:
              description: Deprecated
              items:
                properties:
                  name:
                    type: string
                type: object
              maxItems: 1
              type: array
            skuName:
              type: string
            tags:
              additionalProperties:
                type: string
              type: object
            tenantID:
              type: string
            vaultURI:
              type: string
          required:
          - location
          - name
          - providerRef
          - resourceGroupName
          - tenantID
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                accessPolicy:
                  items:
                    properties:
                      applicationID:
                        type: string
                      certificatePermissions:
                        items:
                          type: string
                        type: array
                      keyPermissions:
                        items:
                          type: string
                        type: array
                      objectID:
                        type: string
                      secretPermissions:
                        items:
                          type: string
                        type: array
                      storagePermissions:
                        items:
                          type: string
                        type: array
                      tenantID:
                        type: string
                    required:
                    - objectID
                    - tenantID
                    type: object
                  maxItems: 1024
                  type: array
                enabledForDeployment:
                  type: boolean
                enabledForDiskEncryption:
                  type: boolean
                enabledForTemplateDeployment:
                  type: boolean
                id:
                  type: string
                location:
                  type: string
                name:
                  type: string
                networkAcls:
                  items:
                    properties:
                      bypass:
                        type: string
                      defaultAction:
                        type: string
                      ipRules:
                        items:
                          type: string
                        type: array
                      virtualNetworkSubnetIDS:
                        items:
                          type: string
                        type: array
                    required:
                    - bypass
                    - defaultAction
                    type: object
                  maxItems: 1
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                remoteBackend:
                  description: Backend specifies the configuration of the terraform
                    backend
                  properties:
                    ref:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    type:
                      type: string
                  type: object
                resourceGroupName:
                  type: string
                sku:
                  description: Deprecated
                  items:
                    properties:
                      name:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                skuName:
                  type: string
                tags:
                  additionalProperties:
                    type: string
                  type: object
                tenantID:
                  type: string
                vaultURI:
                  type: string
              required:
              - location
              - name
              - providerRef
              - resourceGroupName
              - tenantID
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
