apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: appserviceplans.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: AppServicePlan
    listKind: AppServicePlanList
    plural: appserviceplans
    singular: appserviceplan
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            appServiceEnvironmentID:
              type: string
            id:
              type: string
            isXenon:
              type: boolean
            kind:
              type: string
            location:
              type: string
            maximumElasticWorkerCount:
              format: int64
              type: integer
            maximumNumberOfWorkers:
              format: int64
              type: integer
            name:
              type: string
            perSiteScaling:
              type: boolean
            properties:
              description: Deprecated
              items:
                properties:
                  appServiceEnvironmentID:
                    description: Deprecated
                    type: string
                  perSiteScaling:
                    description: Deprecated
                    type: boolean
                  reserved:
                    description: Deprecated
                    type: boolean
                type: object
              maxItems: 1
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            reserved:
              type: boolean
            resourceGroupName:
              type: string
            sku:
              items:
                properties:
                  capacity:
                    format: int64
                    type: integer
                  size:
                    type: string
                  tier:
                    type: string
                required:
                - size
                - tier
                type: object
              maxItems: 1
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
          required:
          - location
          - name
          - providerRef
          - resourceGroupName
          - sku
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                appServiceEnvironmentID:
                  type: string
                id:
                  type: string
                isXenon:
                  type: boolean
                kind:
                  type: string
                location:
                  type: string
                maximumElasticWorkerCount:
                  format: int64
                  type: integer
                maximumNumberOfWorkers:
                  format: int64
                  type: integer
                name:
                  type: string
                perSiteScaling:
                  type: boolean
                properties:
                  description: Deprecated
                  items:
                    properties:
                      appServiceEnvironmentID:
                        description: Deprecated
                        type: string
                      perSiteScaling:
                        description: Deprecated
                        type: boolean
                      reserved:
                        description: Deprecated
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                reserved:
                  type: boolean
                resourceGroupName:
                  type: string
                sku:
                  items:
                    properties:
                      capacity:
                        format: int64
                        type: integer
                      size:
                        type: string
                      tier:
                        type: string
                    required:
                    - size
                    - tier
                    type: object
                  maxItems: 1
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
              required:
              - location
              - name
              - providerRef
              - resourceGroupName
              - sku
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
