apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: monitoractiongroups.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: MonitorActionGroup
    listKind: MonitorActionGroupList
    plural: monitoractiongroups
    singular: monitoractiongroup
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            armRoleReceiver:
              items:
                properties:
                  name:
                    type: string
                  roleID:
                    type: string
                  useCommonAlertSchema:
                    type: boolean
                required:
                - name
                - roleID
                type: object
              type: array
            automationRunbookReceiver:
              items:
                properties:
                  automationAccountID:
                    type: string
                  isGlobalRunbook:
                    type: boolean
                  name:
                    type: string
                  runbookName:
                    type: string
                  serviceURI:
                    type: string
                  useCommonAlertSchema:
                    type: boolean
                  webhookResourceID:
                    type: string
                required:
                - automationAccountID
                - isGlobalRunbook
                - name
                - runbookName
                - serviceURI
                - webhookResourceID
                type: object
              type: array
            azureAppPushReceiver:
              items:
                properties:
                  emailAddress:
                    type: string
                  name:
                    type: string
                required:
                - emailAddress
                - name
                type: object
              type: array
            azureFunctionReceiver:
              items:
                properties:
                  functionAppResourceID:
                    type: string
                  functionName:
                    type: string
                  httpTriggerURL:
                    type: string
                  name:
                    type: string
                  useCommonAlertSchema:
                    type: boolean
                required:
                - functionAppResourceID
                - functionName
                - httpTriggerURL
                - name
                type: object
              type: array
            emailReceiver:
              items:
                properties:
                  emailAddress:
                    type: string
                  name:
                    type: string
                  useCommonAlertSchema:
                    type: boolean
                required:
                - emailAddress
                - name
                type: object
              type: array
            enabled:
              type: boolean
            id:
              type: string
            itsmReceiver:
              items:
                properties:
                  connectionID:
                    type: string
                  name:
                    type: string
                  region:
                    type: string
                  ticketConfiguration:
                    type: string
                  workspaceID:
                    type: string
                required:
                - connectionID
                - name
                - region
                - ticketConfiguration
                - workspaceID
                type: object
              type: array
            logicAppReceiver:
              items:
                properties:
                  callbackURL:
                    type: string
                  name:
                    type: string
                  resourceID:
                    type: string
                  useCommonAlertSchema:
                    type: boolean
                required:
                - callbackURL
                - name
                - resourceID
                type: object
              type: array
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            remoteBackend:
              description: Backend specifies the configuration of the terraform backend
              properties:
                ref:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                type:
                  type: string
              type: object
            resourceGroupName:
              type: string
            shortName:
              type: string
            smsReceiver:
              items:
                properties:
                  countryCode:
                    type: string
                  name:
                    type: string
                  phoneNumber:
                    type: string
                required:
                - countryCode
                - name
                - phoneNumber
                type: object
              type: array
            tags:
              additionalProperties:
                type: string
              type: object
            voiceReceiver:
              items:
                properties:
                  countryCode:
                    type: string
                  name:
                    type: string
                  phoneNumber:
                    type: string
                required:
                - countryCode
                - name
                - phoneNumber
                type: object
              type: array
            webhookReceiver:
              items:
                properties:
                  name:
                    type: string
                  serviceURI:
                    type: string
                  useCommonAlertSchema:
                    type: boolean
                required:
                - name
                - serviceURI
                type: object
              type: array
          required:
          - name
          - providerRef
          - resourceGroupName
          - shortName
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                armRoleReceiver:
                  items:
                    properties:
                      name:
                        type: string
                      roleID:
                        type: string
                      useCommonAlertSchema:
                        type: boolean
                    required:
                    - name
                    - roleID
                    type: object
                  type: array
                automationRunbookReceiver:
                  items:
                    properties:
                      automationAccountID:
                        type: string
                      isGlobalRunbook:
                        type: boolean
                      name:
                        type: string
                      runbookName:
                        type: string
                      serviceURI:
                        type: string
                      useCommonAlertSchema:
                        type: boolean
                      webhookResourceID:
                        type: string
                    required:
                    - automationAccountID
                    - isGlobalRunbook
                    - name
                    - runbookName
                    - serviceURI
                    - webhookResourceID
                    type: object
                  type: array
                azureAppPushReceiver:
                  items:
                    properties:
                      emailAddress:
                        type: string
                      name:
                        type: string
                    required:
                    - emailAddress
                    - name
                    type: object
                  type: array
                azureFunctionReceiver:
                  items:
                    properties:
                      functionAppResourceID:
                        type: string
                      functionName:
                        type: string
                      httpTriggerURL:
                        type: string
                      name:
                        type: string
                      useCommonAlertSchema:
                        type: boolean
                    required:
                    - functionAppResourceID
                    - functionName
                    - httpTriggerURL
                    - name
                    type: object
                  type: array
                emailReceiver:
                  items:
                    properties:
                      emailAddress:
                        type: string
                      name:
                        type: string
                      useCommonAlertSchema:
                        type: boolean
                    required:
                    - emailAddress
                    - name
                    type: object
                  type: array
                enabled:
                  type: boolean
                id:
                  type: string
                itsmReceiver:
                  items:
                    properties:
                      connectionID:
                        type: string
                      name:
                        type: string
                      region:
                        type: string
                      ticketConfiguration:
                        type: string
                      workspaceID:
                        type: string
                    required:
                    - connectionID
                    - name
                    - region
                    - ticketConfiguration
                    - workspaceID
                    type: object
                  type: array
                logicAppReceiver:
                  items:
                    properties:
                      callbackURL:
                        type: string
                      name:
                        type: string
                      resourceID:
                        type: string
                      useCommonAlertSchema:
                        type: boolean
                    required:
                    - callbackURL
                    - name
                    - resourceID
                    type: object
                  type: array
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                remoteBackend:
                  description: Backend specifies the configuration of the terraform
                    backend
                  properties:
                    ref:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    type:
                      type: string
                  type: object
                resourceGroupName:
                  type: string
                shortName:
                  type: string
                smsReceiver:
                  items:
                    properties:
                      countryCode:
                        type: string
                      name:
                        type: string
                      phoneNumber:
                        type: string
                    required:
                    - countryCode
                    - name
                    - phoneNumber
                    type: object
                  type: array
                tags:
                  additionalProperties:
                    type: string
                  type: object
                voiceReceiver:
                  items:
                    properties:
                      countryCode:
                        type: string
                      name:
                        type: string
                      phoneNumber:
                        type: string
                    required:
                    - countryCode
                    - name
                    - phoneNumber
                    type: object
                  type: array
                webhookReceiver:
                  items:
                    properties:
                      name:
                        type: string
                      serviceURI:
                        type: string
                      useCommonAlertSchema:
                        type: boolean
                    required:
                    - name
                    - serviceURI
                    type: object
                  type: array
              required:
              - name
              - providerRef
              - resourceGroupName
              - shortName
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
