apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: vpnserverconfigurations.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: VpnServerConfiguration
    listKind: VpnServerConfigurationList
    plural: vpnserverconfigurations
    singular: vpnserverconfiguration
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            azureActiveDirectoryAuthentication:
              items:
                properties:
                  audience:
                    type: string
                  issuer:
                    type: string
                  tenant:
                    type: string
                required:
                - audience
                - issuer
                - tenant
                type: object
              minItems: 1
              type: array
            clientRevokedCertificate:
              items:
                properties:
                  name:
                    type: string
                  thumbprint:
                    type: string
                required:
                - name
                - thumbprint
                type: object
              type: array
            clientRootCertificate:
              items:
                properties:
                  name:
                    type: string
                  publicCertData:
                    type: string
                required:
                - name
                - publicCertData
                type: object
              type: array
            id:
              type: string
            ipsecPolicy:
              items:
                properties:
                  dhGroup:
                    type: string
                  ikeEncryption:
                    type: string
                  ikeIntegrity:
                    type: string
                  ipsecEncryption:
                    type: string
                  ipsecIntegrity:
                    type: string
                  pfsGroup:
                    type: string
                  saDataSizeKilobytes:
                    format: int64
                    type: integer
                  saLifetimeSeconds:
                    format: int64
                    type: integer
                required:
                - dhGroup
                - ikeEncryption
                - ikeIntegrity
                - ipsecEncryption
                - ipsecIntegrity
                - pfsGroup
                - saDataSizeKilobytes
                - saLifetimeSeconds
                type: object
              maxItems: 1
              type: array
            location:
              type: string
            name:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            radiusServer:
              items:
                properties:
                  address:
                    type: string
                  clientRootCertificate:
                    items:
                      properties:
                        name:
                          type: string
                        thumbprint:
                          type: string
                      required:
                      - name
                      - thumbprint
                      type: object
                    type: array
                  serverRootCertificate:
                    items:
                      properties:
                        name:
                          type: string
                        publicCertData:
                          type: string
                      required:
                      - name
                      - publicCertData
                      type: object
                    type: array
                required:
                - address
                - serverRootCertificate
                type: object
              maxItems: 1
              type: array
            resourceGroupName:
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            tags:
              additionalProperties:
                type: string
              type: object
            vpnAuthenticationTypes:
              items:
                type: string
              maxItems: 1
              type: array
            vpnProtocols:
              items:
                type: string
              type: array
          required:
          - location
          - name
          - providerRef
          - resourceGroupName
          - vpnAuthenticationTypes
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                azureActiveDirectoryAuthentication:
                  items:
                    properties:
                      audience:
                        type: string
                      issuer:
                        type: string
                      tenant:
                        type: string
                    required:
                    - audience
                    - issuer
                    - tenant
                    type: object
                  minItems: 1
                  type: array
                clientRevokedCertificate:
                  items:
                    properties:
                      name:
                        type: string
                      thumbprint:
                        type: string
                    required:
                    - name
                    - thumbprint
                    type: object
                  type: array
                clientRootCertificate:
                  items:
                    properties:
                      name:
                        type: string
                      publicCertData:
                        type: string
                    required:
                    - name
                    - publicCertData
                    type: object
                  type: array
                id:
                  type: string
                ipsecPolicy:
                  items:
                    properties:
                      dhGroup:
                        type: string
                      ikeEncryption:
                        type: string
                      ikeIntegrity:
                        type: string
                      ipsecEncryption:
                        type: string
                      ipsecIntegrity:
                        type: string
                      pfsGroup:
                        type: string
                      saDataSizeKilobytes:
                        format: int64
                        type: integer
                      saLifetimeSeconds:
                        format: int64
                        type: integer
                    required:
                    - dhGroup
                    - ikeEncryption
                    - ikeIntegrity
                    - ipsecEncryption
                    - ipsecIntegrity
                    - pfsGroup
                    - saDataSizeKilobytes
                    - saLifetimeSeconds
                    type: object
                  maxItems: 1
                  type: array
                location:
                  type: string
                name:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                radiusServer:
                  items:
                    properties:
                      address:
                        type: string
                      clientRootCertificate:
                        items:
                          properties:
                            name:
                              type: string
                            thumbprint:
                              type: string
                          required:
                          - name
                          - thumbprint
                          type: object
                        type: array
                      serverRootCertificate:
                        items:
                          properties:
                            name:
                              type: string
                            publicCertData:
                              type: string
                          required:
                          - name
                          - publicCertData
                          type: object
                        type: array
                    required:
                    - address
                    - serverRootCertificate
                    type: object
                  maxItems: 1
                  type: array
                resourceGroupName:
                  type: string
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                tags:
                  additionalProperties:
                    type: string
                  type: object
                vpnAuthenticationTypes:
                  items:
                    type: string
                  maxItems: 1
                  type: array
                vpnProtocols:
                  items:
                    type: string
                  type: array
              required:
              - location
              - name
              - providerRef
              - resourceGroupName
              - vpnAuthenticationTypes
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
