apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: apimanagementapis.azurerm.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: azurerm.kubeform.com
  names:
    kind: ApiManagementAPI
    listKind: ApiManagementAPIList
    plural: apimanagementapis
    singular: apimanagementapi
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            apiManagementName:
              type: string
            description:
              type: string
            displayName:
              type: string
            id:
              type: string
            import:
              items:
                properties:
                  contentFormat:
                    type: string
                  contentValue:
                    type: string
                  wsdlSelector:
                    items:
                      properties:
                        endpointName:
                          type: string
                        serviceName:
                          type: string
                      required:
                      - endpointName
                      - serviceName
                      type: object
                    maxItems: 1
                    type: array
                required:
                - contentFormat
                - contentValue
                type: object
              maxItems: 1
              type: array
            isCurrent:
              type: boolean
            isOnline:
              type: boolean
            name:
              type: string
            path:
              type: string
            protocols:
              items:
                type: string
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            resourceGroupName:
              type: string
            revision:
              type: string
            serviceURL:
              type: string
            soapPassThrough:
              type: boolean
            subscriptionKeyParameterNames:
              items:
                properties:
                  header:
                    type: string
                  query:
                    type: string
                required:
                - header
                - query
                type: object
              maxItems: 1
              type: array
            version:
              type: string
            versionSetID:
              type: string
          required:
          - apiManagementName
          - displayName
          - name
          - path
          - protocols
          - providerRef
          - resourceGroupName
          - revision
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                apiManagementName:
                  type: string
                description:
                  type: string
                displayName:
                  type: string
                id:
                  type: string
                import:
                  items:
                    properties:
                      contentFormat:
                        type: string
                      contentValue:
                        type: string
                      wsdlSelector:
                        items:
                          properties:
                            endpointName:
                              type: string
                            serviceName:
                              type: string
                          required:
                          - endpointName
                          - serviceName
                          type: object
                        maxItems: 1
                        type: array
                    required:
                    - contentFormat
                    - contentValue
                    type: object
                  maxItems: 1
                  type: array
                isCurrent:
                  type: boolean
                isOnline:
                  type: boolean
                name:
                  type: string
                path:
                  type: string
                protocols:
                  items:
                    type: string
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                resourceGroupName:
                  type: string
                revision:
                  type: string
                serviceURL:
                  type: string
                soapPassThrough:
                  type: boolean
                subscriptionKeyParameterNames:
                  items:
                    properties:
                      header:
                        type: string
                      query:
                        type: string
                    required:
                    - header
                    - query
                    type: object
                  maxItems: 1
                  type: array
                version:
                  type: string
                versionSetID:
                  type: string
              required:
              - apiManagementName
              - displayName
              - name
              - path
              - protocols
              - providerRef
              - resourceGroupName
              - revision
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
