apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: projects.digitalocean.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: digitalocean.kubeform.com
  names:
    kind: Project
    listKind: ProjectList
    plural: projects
    singular: project
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            createdAt:
              description: the date and time when the project was created, (ISO8601)
              type: string
            description:
              description: the description of the project
              type: string
            environment:
              description: the environment of the project's resources
              type: string
            id:
              type: string
            isDefault:
              type: boolean
            name:
              description: the human-readable name for the project
              type: string
            ownerID:
              description: the id of the project owner.
              format: int64
              type: integer
            ownerUUID:
              description: the unique universal identifier of the project owner.
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            purpose:
              description: the purpose of the project
              type: string
            resources:
              description: the resources associated with the project
              items:
                type: string
              type: array
            updatedAt:
              description: the date and time when the project was last updated, (ISO8601)
              type: string
          required:
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                createdAt:
                  description: the date and time when the project was created, (ISO8601)
                  type: string
                description:
                  description: the description of the project
                  type: string
                environment:
                  description: the environment of the project's resources
                  type: string
                id:
                  type: string
                isDefault:
                  type: boolean
                name:
                  description: the human-readable name for the project
                  type: string
                ownerID:
                  description: the id of the project owner.
                  format: int64
                  type: integer
                ownerUUID:
                  description: the unique universal identifier of the project owner.
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                purpose:
                  description: the purpose of the project
                  type: string
                resources:
                  description: the resources associated with the project
                  items:
                    type: string
                  type: array
                updatedAt:
                  description: the date and time when the project was last updated,
                    (ISO8601)
                  type: string
              required:
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
