apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: spacesbuckets.digitalocean.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: digitalocean.kubeform.com
  names:
    kind: SpacesBucket
    listKind: SpacesBucketList
    plural: spacesbuckets
    singular: spacesbucket
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            acl:
              description: Canned ACL applied on bucket creation
              type: string
            bucketDomainName:
              description: The FQDN of the bucket
              type: string
            corsRule:
              description: A container holding a list of elements describing allowed
                methods for a specific origin.
              items:
                properties:
                  allowedHeaders:
                    description: A list of headers that will be included in the CORS
                      preflight request's Access-Control-Request-Headers. A header
                      may contain one wildcard (e.g. x-amz-*).
                    items:
                      type: string
                    type: array
                  allowedMethods:
                    description: A list of HTTP methods (e.g. GET) which are allowed
                      from the specified origin.
                    items:
                      type: string
                    type: array
                  allowedOrigins:
                    description: A list of hosts from which requests using the specified
                      methods are allowed. A host may contain one wildcard (e.g. http://*.example.com).
                    items:
                      type: string
                    type: array
                  maxAgeSeconds:
                    format: int64
                    type: integer
                required:
                - allowedMethods
                - allowedOrigins
                type: object
              type: array
            forceDestroy:
              description: Unless true, the bucket will only be destroyed if empty
              type: boolean
            id:
              type: string
            lifecycleRule:
              items:
                properties:
                  ID:
                    type: string
                  abortIncompleteMultipartUploadDays:
                    format: int64
                    type: integer
                  enabled:
                    type: boolean
                  expiration:
                    items:
                      properties:
                        date:
                          type: string
                        days:
                          format: int64
                          type: integer
                        expiredObjectDeleteMarker:
                          type: boolean
                      type: object
                    maxItems: 1
                    type: array
                  noncurrentVersionExpiration:
                    items:
                      properties:
                        days:
                          format: int64
                          type: integer
                      type: object
                    maxItems: 1
                    type: array
                  prefix:
                    type: string
                required:
                - enabled
                type: object
              type: array
            name:
              description: Bucket name
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              description: Bucket region
              type: string
            urn:
              description: the uniform resource name for the bucket
              type: string
            versioning:
              items:
                properties:
                  enabled:
                    type: boolean
                type: object
              maxItems: 1
              type: array
          required:
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                acl:
                  description: Canned ACL applied on bucket creation
                  type: string
                bucketDomainName:
                  description: The FQDN of the bucket
                  type: string
                corsRule:
                  description: A container holding a list of elements describing allowed
                    methods for a specific origin.
                  items:
                    properties:
                      allowedHeaders:
                        description: A list of headers that will be included in the
                          CORS preflight request's Access-Control-Request-Headers.
                          A header may contain one wildcard (e.g. x-amz-*).
                        items:
                          type: string
                        type: array
                      allowedMethods:
                        description: A list of HTTP methods (e.g. GET) which are allowed
                          from the specified origin.
                        items:
                          type: string
                        type: array
                      allowedOrigins:
                        description: A list of hosts from which requests using the
                          specified methods are allowed. A host may contain one wildcard
                          (e.g. http://*.example.com).
                        items:
                          type: string
                        type: array
                      maxAgeSeconds:
                        format: int64
                        type: integer
                    required:
                    - allowedMethods
                    - allowedOrigins
                    type: object
                  type: array
                forceDestroy:
                  description: Unless true, the bucket will only be destroyed if empty
                  type: boolean
                id:
                  type: string
                lifecycleRule:
                  items:
                    properties:
                      ID:
                        type: string
                      abortIncompleteMultipartUploadDays:
                        format: int64
                        type: integer
                      enabled:
                        type: boolean
                      expiration:
                        items:
                          properties:
                            date:
                              type: string
                            days:
                              format: int64
                              type: integer
                            expiredObjectDeleteMarker:
                              type: boolean
                          type: object
                        maxItems: 1
                        type: array
                      noncurrentVersionExpiration:
                        items:
                          properties:
                            days:
                              format: int64
                              type: integer
                          type: object
                        maxItems: 1
                        type: array
                      prefix:
                        type: string
                    required:
                    - enabled
                    type: object
                  type: array
                name:
                  description: Bucket name
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                region:
                  description: Bucket region
                  type: string
                urn:
                  description: the uniform resource name for the bucket
                  type: string
                versioning:
                  items:
                    properties:
                      enabled:
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
              required:
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
