apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: firewalls.digitalocean.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: digitalocean.kubeform.com
  names:
    kind: Firewall
    listKind: FirewallList
    plural: firewalls
    singular: firewall
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            createdAt:
              type: string
            dropletIDS:
              items:
                format: int64
                type: integer
              type: array
            id:
              type: string
            inboundRule:
              items:
                properties:
                  portRange:
                    type: string
                  protocol:
                    type: string
                  sourceAddresses:
                    items:
                      type: string
                    type: array
                  sourceDropletIDS:
                    items:
                      format: int64
                      type: integer
                    type: array
                  sourceLoadBalancerUids:
                    items:
                      type: string
                    type: array
                  sourceTags:
                    items:
                      type: string
                    type: array
                required:
                - protocol
                type: object
              type: array
            name:
              type: string
            outboundRule:
              items:
                properties:
                  destinationAddresses:
                    items:
                      type: string
                    type: array
                  destinationDropletIDS:
                    items:
                      format: int64
                      type: integer
                    type: array
                  destinationLoadBalancerUids:
                    items:
                      type: string
                    type: array
                  destinationTags:
                    items:
                      type: string
                    type: array
                  portRange:
                    type: string
                  protocol:
                    type: string
                required:
                - protocol
                type: object
              type: array
            pendingChanges:
              items:
                properties:
                  dropletID:
                    format: int64
                    type: integer
                  removing:
                    type: boolean
                  status:
                    type: string
                type: object
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            remoteBackend:
              description: Backend specifies the configuration of the terraform backend
              properties:
                ref:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                type:
                  type: string
              type: object
            status:
              type: string
            tags:
              items:
                type: string
              type: array
          required:
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                createdAt:
                  type: string
                dropletIDS:
                  items:
                    format: int64
                    type: integer
                  type: array
                id:
                  type: string
                inboundRule:
                  items:
                    properties:
                      portRange:
                        type: string
                      protocol:
                        type: string
                      sourceAddresses:
                        items:
                          type: string
                        type: array
                      sourceDropletIDS:
                        items:
                          format: int64
                          type: integer
                        type: array
                      sourceLoadBalancerUids:
                        items:
                          type: string
                        type: array
                      sourceTags:
                        items:
                          type: string
                        type: array
                    required:
                    - protocol
                    type: object
                  type: array
                name:
                  type: string
                outboundRule:
                  items:
                    properties:
                      destinationAddresses:
                        items:
                          type: string
                        type: array
                      destinationDropletIDS:
                        items:
                          format: int64
                          type: integer
                        type: array
                      destinationLoadBalancerUids:
                        items:
                          type: string
                        type: array
                      destinationTags:
                        items:
                          type: string
                        type: array
                      portRange:
                        type: string
                      protocol:
                        type: string
                    required:
                    - protocol
                    type: object
                  type: array
                pendingChanges:
                  items:
                    properties:
                      dropletID:
                        format: int64
                        type: integer
                      removing:
                        type: boolean
                      status:
                        type: string
                    type: object
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                remoteBackend:
                  description: Backend specifies the configuration of the terraform
                    backend
                  properties:
                    ref:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    type:
                      type: string
                  type: object
                status:
                  type: string
                tags:
                  items:
                    type: string
                  type: array
              required:
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
