apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: cdns.digitalocean.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: digitalocean.kubeform.com
  names:
    kind: Cdn
    listKind: CdnList
    plural: cdns
    singular: cdn
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            certificateID:
              description: ID of a DigitalOcean managed TLS certificate for use with
                custom domains
              type: string
            createdAt:
              description: The date and time (ISO8601) of when the CDN endpoint was
                created.
              type: string
            customDomain:
              description: fully qualified domain name (FQDN) for custom subdomain,
                (requires certificate_id)
              type: string
            endpoint:
              description: fully qualified domain name (FQDN) to serve the CDN content
              type: string
            id:
              type: string
            origin:
              description: fully qualified domain name (FQDN) for the origin server
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            ttl:
              description: The amount of time the content is cached in the CDN
              format: int64
              type: integer
          required:
          - origin
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                certificateID:
                  description: ID of a DigitalOcean managed TLS certificate for use
                    with custom domains
                  type: string
                createdAt:
                  description: The date and time (ISO8601) of when the CDN endpoint
                    was created.
                  type: string
                customDomain:
                  description: fully qualified domain name (FQDN) for custom subdomain,
                    (requires certificate_id)
                  type: string
                endpoint:
                  description: fully qualified domain name (FQDN) to serve the CDN
                    content
                  type: string
                id:
                  type: string
                origin:
                  description: fully qualified domain name (FQDN) for the origin server
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                ttl:
                  description: The amount of time the content is cached in the CDN
                  format: int64
                  type: integer
              required:
              - origin
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
