apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: kubernetesclusters.digitalocean.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: digitalocean.kubeform.com
  names:
    kind: KubernetesCluster
    listKind: KubernetesClusterList
    plural: kubernetesclusters
    singular: kubernetescluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            clusterSubnet:
              type: string
            createdAt:
              type: string
            endpoint:
              type: string
            id:
              type: string
            ipv4Address:
              type: string
            name:
              type: string
            nodePool:
              items:
                properties:
                  ID:
                    type: string
                  actualNodeCount:
                    format: int64
                    type: integer
                  autoScale:
                    type: boolean
                  labels:
                    additionalProperties:
                      type: string
                    type: object
                  maxNodes:
                    format: int64
                    type: integer
                  minNodes:
                    format: int64
                    type: integer
                  name:
                    type: string
                  nodeCount:
                    format: int64
                    type: integer
                  nodes:
                    items:
                      properties:
                        ID:
                          type: string
                        createdAt:
                          type: string
                        dropletID:
                          type: string
                        name:
                          type: string
                        status:
                          type: string
                        updatedAt:
                          type: string
                      type: object
                    type: array
                  size:
                    type: string
                  tags:
                    items:
                      type: string
                    type: array
                required:
                - name
                - size
                type: object
              maxItems: 1
              minItems: 1
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              type: string
            remoteBackend:
              description: Backend specifies the configuration of the terraform backend
              properties:
                ref:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                type:
                  type: string
              type: object
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            serviceSubnet:
              type: string
            status:
              type: string
            tags:
              items:
                type: string
              type: array
            updatedAt:
              type: string
            version:
              type: string
            vpcUUID:
              type: string
          required:
          - nodePool
          - providerRef
          - region
          - version
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                clusterSubnet:
                  type: string
                createdAt:
                  type: string
                endpoint:
                  type: string
                id:
                  type: string
                ipv4Address:
                  type: string
                name:
                  type: string
                nodePool:
                  items:
                    properties:
                      ID:
                        type: string
                      actualNodeCount:
                        format: int64
                        type: integer
                      autoScale:
                        type: boolean
                      labels:
                        additionalProperties:
                          type: string
                        type: object
                      maxNodes:
                        format: int64
                        type: integer
                      minNodes:
                        format: int64
                        type: integer
                      name:
                        type: string
                      nodeCount:
                        format: int64
                        type: integer
                      nodes:
                        items:
                          properties:
                            ID:
                              type: string
                            createdAt:
                              type: string
                            dropletID:
                              type: string
                            name:
                              type: string
                            status:
                              type: string
                            updatedAt:
                              type: string
                          type: object
                        type: array
                      size:
                        type: string
                      tags:
                        items:
                          type: string
                        type: array
                    required:
                    - name
                    - size
                    type: object
                  maxItems: 1
                  minItems: 1
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                region:
                  type: string
                remoteBackend:
                  description: Backend specifies the configuration of the terraform
                    backend
                  properties:
                    ref:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    type:
                      type: string
                  type: object
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                serviceSubnet:
                  type: string
                status:
                  type: string
                tags:
                  items:
                    type: string
                  type: array
                updatedAt:
                  type: string
                version:
                  type: string
                vpcUUID:
                  type: string
              required:
              - nodePool
              - providerRef
              - region
              - version
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
