apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: monitoringalertpolicies.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: MonitoringAlertPolicy
    listKind: MonitoringAlertPolicyList
    plural: monitoringalertpolicies
    singular: monitoringalertpolicy
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            combiner:
              type: string
            conditions:
              items:
                properties:
                  conditionAbsent:
                    items:
                      properties:
                        aggregations:
                          items:
                            properties:
                              alignmentPeriod:
                                type: string
                              crossSeriesReducer:
                                type: string
                              groupByFields:
                                items:
                                  type: string
                                type: array
                              perSeriesAligner:
                                type: string
                            type: object
                          type: array
                        duration:
                          type: string
                        filter:
                          type: string
                        trigger:
                          items:
                            properties:
                              count:
                                format: int64
                                type: integer
                              percent:
                                format: float
                                type: number
                            type: object
                          maxItems: 1
                          type: array
                      required:
                      - duration
                      type: object
                    maxItems: 1
                    type: array
                  conditionThreshold:
                    items:
                      properties:
                        aggregations:
                          items:
                            properties:
                              alignmentPeriod:
                                type: string
                              crossSeriesReducer:
                                type: string
                              groupByFields:
                                items:
                                  type: string
                                type: array
                              perSeriesAligner:
                                type: string
                            type: object
                          type: array
                        comparison:
                          type: string
                        denominatorAggregations:
                          items:
                            properties:
                              alignmentPeriod:
                                type: string
                              crossSeriesReducer:
                                type: string
                              groupByFields:
                                items:
                                  type: string
                                type: array
                              perSeriesAligner:
                                type: string
                            type: object
                          type: array
                        denominatorFilter:
                          type: string
                        duration:
                          type: string
                        filter:
                          type: string
                        thresholdValue:
                          format: float
                          type: number
                        trigger:
                          items:
                            properties:
                              count:
                                format: int64
                                type: integer
                              percent:
                                format: float
                                type: number
                            type: object
                          maxItems: 1
                          type: array
                      required:
                      - comparison
                      - duration
                      type: object
                    maxItems: 1
                    type: array
                  displayName:
                    type: string
                  name:
                    type: string
                required:
                - displayName
                type: object
              type: array
            creationRecord:
              items:
                properties:
                  mutateTime:
                    type: string
                  mutatedBy:
                    type: string
                type: object
              maxItems: 1
              type: array
            displayName:
              type: string
            documentation:
              items:
                properties:
                  content:
                    type: string
                  mimeType:
                    type: string
                type: object
              maxItems: 1
              type: array
            enabled:
              type: boolean
            id:
              type: string
            labels:
              description: Deprecated
              items:
                type: string
              type: array
            name:
              type: string
            notificationChannels:
              items:
                type: string
              type: array
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            userLabels:
              additionalProperties:
                type: string
              type: object
          required:
          - combiner
          - conditions
          - displayName
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                combiner:
                  type: string
                conditions:
                  items:
                    properties:
                      conditionAbsent:
                        items:
                          properties:
                            aggregations:
                              items:
                                properties:
                                  alignmentPeriod:
                                    type: string
                                  crossSeriesReducer:
                                    type: string
                                  groupByFields:
                                    items:
                                      type: string
                                    type: array
                                  perSeriesAligner:
                                    type: string
                                type: object
                              type: array
                            duration:
                              type: string
                            filter:
                              type: string
                            trigger:
                              items:
                                properties:
                                  count:
                                    format: int64
                                    type: integer
                                  percent:
                                    format: float
                                    type: number
                                type: object
                              maxItems: 1
                              type: array
                          required:
                          - duration
                          type: object
                        maxItems: 1
                        type: array
                      conditionThreshold:
                        items:
                          properties:
                            aggregations:
                              items:
                                properties:
                                  alignmentPeriod:
                                    type: string
                                  crossSeriesReducer:
                                    type: string
                                  groupByFields:
                                    items:
                                      type: string
                                    type: array
                                  perSeriesAligner:
                                    type: string
                                type: object
                              type: array
                            comparison:
                              type: string
                            denominatorAggregations:
                              items:
                                properties:
                                  alignmentPeriod:
                                    type: string
                                  crossSeriesReducer:
                                    type: string
                                  groupByFields:
                                    items:
                                      type: string
                                    type: array
                                  perSeriesAligner:
                                    type: string
                                type: object
                              type: array
                            denominatorFilter:
                              type: string
                            duration:
                              type: string
                            filter:
                              type: string
                            thresholdValue:
                              format: float
                              type: number
                            trigger:
                              items:
                                properties:
                                  count:
                                    format: int64
                                    type: integer
                                  percent:
                                    format: float
                                    type: number
                                type: object
                              maxItems: 1
                              type: array
                          required:
                          - comparison
                          - duration
                          type: object
                        maxItems: 1
                        type: array
                      displayName:
                        type: string
                      name:
                        type: string
                    required:
                    - displayName
                    type: object
                  type: array
                creationRecord:
                  items:
                    properties:
                      mutateTime:
                        type: string
                      mutatedBy:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                displayName:
                  type: string
                documentation:
                  items:
                    properties:
                      content:
                        type: string
                      mimeType:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                enabled:
                  type: boolean
                id:
                  type: string
                labels:
                  description: Deprecated
                  items:
                    type: string
                  type: array
                name:
                  type: string
                notificationChannels:
                  items:
                    type: string
                  type: array
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                userLabels:
                  additionalProperties:
                    type: string
                  type: object
              required:
              - combiner
              - conditions
              - displayName
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
