apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: computereservations.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: ComputeReservation
    listKind: ComputeReservationList
    plural: computereservations
    singular: computereservation
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            commitment:
              type: string
            creationTimestamp:
              type: string
            description:
              type: string
            id:
              type: string
            name:
              type: string
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            selfLink:
              type: string
            specificReservation:
              items:
                properties:
                  count:
                    format: int64
                    type: integer
                  inUseCount:
                    format: int64
                    type: integer
                  instanceProperties:
                    items:
                      properties:
                        guestAccelerators:
                          items:
                            properties:
                              acceleratorCount:
                                format: int64
                                type: integer
                              acceleratorType:
                                type: string
                            required:
                            - acceleratorCount
                            - acceleratorType
                            type: object
                          type: array
                        localSsds:
                          items:
                            properties:
                              diskSizeGb:
                                format: int64
                                type: integer
                              interface:
                                type: string
                            required:
                            - diskSizeGb
                            type: object
                          type: array
                        machineType:
                          type: string
                        minCPUPlatform:
                          type: string
                      required:
                      - machineType
                      type: object
                    maxItems: 1
                    type: array
                required:
                - count
                - instanceProperties
                type: object
              maxItems: 1
              type: array
            specificReservationRequired:
              type: boolean
            status:
              type: string
            zone:
              type: string
          required:
          - name
          - providerRef
          - specificReservation
          - zone
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                commitment:
                  type: string
                creationTimestamp:
                  type: string
                description:
                  type: string
                id:
                  type: string
                name:
                  type: string
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                selfLink:
                  type: string
                specificReservation:
                  items:
                    properties:
                      count:
                        format: int64
                        type: integer
                      inUseCount:
                        format: int64
                        type: integer
                      instanceProperties:
                        items:
                          properties:
                            guestAccelerators:
                              items:
                                properties:
                                  acceleratorCount:
                                    format: int64
                                    type: integer
                                  acceleratorType:
                                    type: string
                                required:
                                - acceleratorCount
                                - acceleratorType
                                type: object
                              type: array
                            localSsds:
                              items:
                                properties:
                                  diskSizeGb:
                                    format: int64
                                    type: integer
                                  interface:
                                    type: string
                                required:
                                - diskSizeGb
                                type: object
                              type: array
                            machineType:
                              type: string
                            minCPUPlatform:
                              type: string
                          required:
                          - machineType
                          type: object
                        maxItems: 1
                        type: array
                    required:
                    - count
                    - instanceProperties
                    type: object
                  maxItems: 1
                  type: array
                specificReservationRequired:
                  type: boolean
                status:
                  type: string
                zone:
                  type: string
              required:
              - name
              - providerRef
              - specificReservation
              - zone
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
