apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: composerenvironments.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: ComposerEnvironment
    listKind: ComposerEnvironmentList
    plural: composerenvironments
    singular: composerenvironment
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            config:
              items:
                properties:
                  airflowURI:
                    type: string
                  dagGcsPrefix:
                    type: string
                  gkeCluster:
                    type: string
                  nodeConfig:
                    items:
                      properties:
                        diskSizeGb:
                          format: int64
                          type: integer
                        ipAllocationPolicy:
                          items:
                            properties:
                              clusterIpv4CIDRBlock:
                                type: string
                              clusterSecondaryRangeName:
                                type: string
                              servicesIpv4CIDRBlock:
                                type: string
                              servicesSecondaryRangeName:
                                type: string
                              useIPAliases:
                                type: boolean
                            type: object
                          maxItems: 1
                          type: array
                        machineType:
                          type: string
                        network:
                          type: string
                        oauthScopes:
                          items:
                            type: string
                          type: array
                        serviceAccount:
                          type: string
                        subnetwork:
                          type: string
                        tags:
                          items:
                            type: string
                          type: array
                        zone:
                          type: string
                      required:
                      - zone
                      type: object
                    maxItems: 1
                    type: array
                  nodeCount:
                    format: int64
                    type: integer
                  privateEnvironmentConfig:
                    items:
                      properties:
                        enablePrivateEndpoint:
                          type: boolean
                        masterIpv4CIDRBlock:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  softwareConfig:
                    items:
                      properties:
                        airflowConfigOverrides:
                          additionalProperties:
                            type: string
                          type: object
                        envVariables:
                          additionalProperties:
                            type: string
                          type: object
                        imageVersion:
                          type: string
                        pypiPackages:
                          additionalProperties:
                            type: string
                          type: object
                        pythonVersion:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            labels:
              additionalProperties:
                type: string
              type: object
            name:
              type: string
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              type: string
          required:
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                config:
                  items:
                    properties:
                      airflowURI:
                        type: string
                      dagGcsPrefix:
                        type: string
                      gkeCluster:
                        type: string
                      nodeConfig:
                        items:
                          properties:
                            diskSizeGb:
                              format: int64
                              type: integer
                            ipAllocationPolicy:
                              items:
                                properties:
                                  clusterIpv4CIDRBlock:
                                    type: string
                                  clusterSecondaryRangeName:
                                    type: string
                                  servicesIpv4CIDRBlock:
                                    type: string
                                  servicesSecondaryRangeName:
                                    type: string
                                  useIPAliases:
                                    type: boolean
                                type: object
                              maxItems: 1
                              type: array
                            machineType:
                              type: string
                            network:
                              type: string
                            oauthScopes:
                              items:
                                type: string
                              type: array
                            serviceAccount:
                              type: string
                            subnetwork:
                              type: string
                            tags:
                              items:
                                type: string
                              type: array
                            zone:
                              type: string
                          required:
                          - zone
                          type: object
                        maxItems: 1
                        type: array
                      nodeCount:
                        format: int64
                        type: integer
                      privateEnvironmentConfig:
                        items:
                          properties:
                            enablePrivateEndpoint:
                              type: boolean
                            masterIpv4CIDRBlock:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      softwareConfig:
                        items:
                          properties:
                            airflowConfigOverrides:
                              additionalProperties:
                                type: string
                              type: object
                            envVariables:
                              additionalProperties:
                                type: string
                              type: object
                            imageVersion:
                              type: string
                            pypiPackages:
                              additionalProperties:
                                type: string
                              type: object
                            pythonVersion:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                labels:
                  additionalProperties:
                    type: string
                  type: object
                name:
                  type: string
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                region:
                  type: string
              required:
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
