apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: cloudschedulerjobs.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: CloudSchedulerJob
    listKind: CloudSchedulerJobList
    plural: cloudschedulerjobs
    singular: cloudschedulerjob
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            appEngineHTTPTarget:
              items:
                properties:
                  appEngineRouting:
                    items:
                      properties:
                        instance:
                          type: string
                        service:
                          type: string
                        version:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  body:
                    type: string
                  headers:
                    additionalProperties:
                      type: string
                    type: object
                  httpMethod:
                    type: string
                  relativeURI:
                    type: string
                required:
                - relativeURI
                type: object
              maxItems: 1
              type: array
            description:
              type: string
            httpTarget:
              items:
                properties:
                  body:
                    type: string
                  headers:
                    additionalProperties:
                      type: string
                    type: object
                  httpMethod:
                    type: string
                  oauthToken:
                    items:
                      properties:
                        scope:
                          type: string
                        serviceAccountEmail:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  oidcToken:
                    items:
                      properties:
                        audience:
                          type: string
                        serviceAccountEmail:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  uri:
                    type: string
                required:
                - uri
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            name:
              type: string
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            pubsubTarget:
              items:
                properties:
                  attributes:
                    additionalProperties:
                      type: string
                    type: object
                  data:
                    type: string
                  topicName:
                    type: string
                required:
                - topicName
                type: object
              maxItems: 1
              type: array
            region:
              type: string
            remoteBackend:
              description: Backend specifies the configuration of the terraform backend
              properties:
                ref:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                type:
                  type: string
              type: object
            retryConfig:
              items:
                properties:
                  maxBackoffDuration:
                    type: string
                  maxDoublings:
                    format: int64
                    type: integer
                  maxRetryDuration:
                    type: string
                  minBackoffDuration:
                    type: string
                  retryCount:
                    format: int64
                    type: integer
                type: object
              maxItems: 1
              type: array
            schedule:
              type: string
            timeZone:
              type: string
          required:
          - name
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                appEngineHTTPTarget:
                  items:
                    properties:
                      appEngineRouting:
                        items:
                          properties:
                            instance:
                              type: string
                            service:
                              type: string
                            version:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      body:
                        type: string
                      headers:
                        additionalProperties:
                          type: string
                        type: object
                      httpMethod:
                        type: string
                      relativeURI:
                        type: string
                    required:
                    - relativeURI
                    type: object
                  maxItems: 1
                  type: array
                description:
                  type: string
                httpTarget:
                  items:
                    properties:
                      body:
                        type: string
                      headers:
                        additionalProperties:
                          type: string
                        type: object
                      httpMethod:
                        type: string
                      oauthToken:
                        items:
                          properties:
                            scope:
                              type: string
                            serviceAccountEmail:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      oidcToken:
                        items:
                          properties:
                            audience:
                              type: string
                            serviceAccountEmail:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      uri:
                        type: string
                    required:
                    - uri
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                name:
                  type: string
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                pubsubTarget:
                  items:
                    properties:
                      attributes:
                        additionalProperties:
                          type: string
                        type: object
                      data:
                        type: string
                      topicName:
                        type: string
                    required:
                    - topicName
                    type: object
                  maxItems: 1
                  type: array
                region:
                  type: string
                remoteBackend:
                  description: Backend specifies the configuration of the terraform
                    backend
                  properties:
                    ref:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    type:
                      type: string
                  type: object
                retryConfig:
                  items:
                    properties:
                      maxBackoffDuration:
                        type: string
                      maxDoublings:
                        format: int64
                        type: integer
                      maxRetryDuration:
                        type: string
                      minBackoffDuration:
                        type: string
                      retryCount:
                        format: int64
                        type: integer
                    type: object
                  maxItems: 1
                  type: array
                schedule:
                  type: string
                timeZone:
                  type: string
              required:
              - name
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
