apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: monitoringuptimecheckconfigs.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: MonitoringUptimeCheckConfig
    listKind: MonitoringUptimeCheckConfigList
    plural: monitoringuptimecheckconfigs
    singular: monitoringuptimecheckconfig
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            contentMatchers:
              items:
                properties:
                  content:
                    type: string
                type: object
              type: array
            displayName:
              type: string
            httpCheck:
              items:
                properties:
                  authInfo:
                    items:
                      properties:
                        username:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  headers:
                    additionalProperties:
                      type: string
                    type: object
                  maskHeaders:
                    type: boolean
                  path:
                    type: string
                  port:
                    format: int64
                    type: integer
                  useSSL:
                    type: boolean
                type: object
              maxItems: 1
              type: array
            id:
              type: string
            internalCheckers:
              description: Deprecated
              items:
                properties:
                  displayName:
                    description: Deprecated
                    type: string
                  gcpZone:
                    description: Deprecated
                    type: string
                  name:
                    description: Deprecated
                    type: string
                  network:
                    description: Deprecated
                    type: string
                  peerProjectID:
                    description: Deprecated
                    type: string
                type: object
              type: array
            isInternal:
              description: Deprecated
              type: boolean
            monitoredResource:
              items:
                properties:
                  labels:
                    additionalProperties:
                      type: string
                    type: object
                  type:
                    type: string
                required:
                - labels
                - type
                type: object
              maxItems: 1
              type: array
            name:
              type: string
            period:
              type: string
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            resourceGroup:
              items:
                properties:
                  groupID:
                    type: string
                  resourceType:
                    type: string
                type: object
              maxItems: 1
              type: array
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            selectedRegions:
              items:
                type: string
              type: array
            tcpCheck:
              items:
                properties:
                  port:
                    format: int64
                    type: integer
                required:
                - port
                type: object
              maxItems: 1
              type: array
            timeout:
              type: string
            uptimeCheckID:
              type: string
          required:
          - displayName
          - providerRef
          - timeout
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                contentMatchers:
                  items:
                    properties:
                      content:
                        type: string
                    type: object
                  type: array
                displayName:
                  type: string
                httpCheck:
                  items:
                    properties:
                      authInfo:
                        items:
                          properties:
                            username:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      headers:
                        additionalProperties:
                          type: string
                        type: object
                      maskHeaders:
                        type: boolean
                      path:
                        type: string
                      port:
                        format: int64
                        type: integer
                      useSSL:
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
                id:
                  type: string
                internalCheckers:
                  description: Deprecated
                  items:
                    properties:
                      displayName:
                        description: Deprecated
                        type: string
                      gcpZone:
                        description: Deprecated
                        type: string
                      name:
                        description: Deprecated
                        type: string
                      network:
                        description: Deprecated
                        type: string
                      peerProjectID:
                        description: Deprecated
                        type: string
                    type: object
                  type: array
                isInternal:
                  description: Deprecated
                  type: boolean
                monitoredResource:
                  items:
                    properties:
                      labels:
                        additionalProperties:
                          type: string
                        type: object
                      type:
                        type: string
                    required:
                    - labels
                    - type
                    type: object
                  maxItems: 1
                  type: array
                name:
                  type: string
                period:
                  type: string
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                resourceGroup:
                  items:
                    properties:
                      groupID:
                        type: string
                      resourceType:
                        type: string
                    type: object
                  maxItems: 1
                  type: array
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                selectedRegions:
                  items:
                    type: string
                  type: array
                tcpCheck:
                  items:
                    properties:
                      port:
                        format: int64
                        type: integer
                    required:
                    - port
                    type: object
                  maxItems: 1
                  type: array
                timeout:
                  type: string
                uptimeCheckID:
                  type: string
              required:
              - displayName
              - providerRef
              - timeout
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
