apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: storagetransferjobs.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: StorageTransferJob
    listKind: StorageTransferJobList
    plural: storagetransferjobs
    singular: storagetransferjob
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            creationTime:
              type: string
            deletionTime:
              type: string
            description:
              type: string
            id:
              type: string
            lastModificationTime:
              type: string
            name:
              type: string
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            schedule:
              items:
                properties:
                  scheduleEndDate:
                    items:
                      properties:
                        day:
                          format: int64
                          type: integer
                        month:
                          format: int64
                          type: integer
                        year:
                          format: int64
                          type: integer
                      required:
                      - day
                      - month
                      - year
                      type: object
                    maxItems: 1
                    type: array
                  scheduleStartDate:
                    items:
                      properties:
                        day:
                          format: int64
                          type: integer
                        month:
                          format: int64
                          type: integer
                        year:
                          format: int64
                          type: integer
                      required:
                      - day
                      - month
                      - year
                      type: object
                    maxItems: 1
                    type: array
                  startTimeOfDay:
                    items:
                      properties:
                        hours:
                          format: int64
                          type: integer
                        minutes:
                          format: int64
                          type: integer
                        nanos:
                          format: int64
                          type: integer
                        seconds:
                          format: int64
                          type: integer
                      required:
                      - hours
                      - minutes
                      - nanos
                      - seconds
                      type: object
                    maxItems: 1
                    type: array
                required:
                - scheduleStartDate
                type: object
              maxItems: 1
              type: array
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            status:
              type: string
            transferSpec:
              items:
                properties:
                  awsS3DataSource:
                    items:
                      properties:
                        awsAccessKey:
                          items:
                            type: object
                          maxItems: 1
                          type: array
                        bucketName:
                          type: string
                      required:
                      - awsAccessKey
                      - bucketName
                      type: object
                    maxItems: 1
                    type: array
                  gcsDataSink:
                    items:
                      properties:
                        bucketName:
                          type: string
                      required:
                      - bucketName
                      type: object
                    maxItems: 1
                    type: array
                  gcsDataSource:
                    items:
                      properties:
                        bucketName:
                          type: string
                      required:
                      - bucketName
                      type: object
                    maxItems: 1
                    type: array
                  httpDataSource:
                    items:
                      properties:
                        listURL:
                          type: string
                      required:
                      - listURL
                      type: object
                    maxItems: 1
                    type: array
                  objectConditions:
                    items:
                      properties:
                        excludePrefixes:
                          items:
                            type: string
                          type: array
                        includePrefixes:
                          items:
                            type: string
                          type: array
                        maxTimeElapsedSinceLastModification:
                          type: string
                        minTimeElapsedSinceLastModification:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  transferOptions:
                    items:
                      properties:
                        deleteObjectsFromSourceAfterTransfer:
                          type: boolean
                        deleteObjectsUniqueInSink:
                          type: boolean
                        overwriteObjectsAlreadyExistingInSink:
                          type: boolean
                      type: object
                    maxItems: 1
                    type: array
                type: object
              maxItems: 1
              type: array
          required:
          - description
          - providerRef
          - schedule
          - transferSpec
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                creationTime:
                  type: string
                deletionTime:
                  type: string
                description:
                  type: string
                id:
                  type: string
                lastModificationTime:
                  type: string
                name:
                  type: string
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                schedule:
                  items:
                    properties:
                      scheduleEndDate:
                        items:
                          properties:
                            day:
                              format: int64
                              type: integer
                            month:
                              format: int64
                              type: integer
                            year:
                              format: int64
                              type: integer
                          required:
                          - day
                          - month
                          - year
                          type: object
                        maxItems: 1
                        type: array
                      scheduleStartDate:
                        items:
                          properties:
                            day:
                              format: int64
                              type: integer
                            month:
                              format: int64
                              type: integer
                            year:
                              format: int64
                              type: integer
                          required:
                          - day
                          - month
                          - year
                          type: object
                        maxItems: 1
                        type: array
                      startTimeOfDay:
                        items:
                          properties:
                            hours:
                              format: int64
                              type: integer
                            minutes:
                              format: int64
                              type: integer
                            nanos:
                              format: int64
                              type: integer
                            seconds:
                              format: int64
                              type: integer
                          required:
                          - hours
                          - minutes
                          - nanos
                          - seconds
                          type: object
                        maxItems: 1
                        type: array
                    required:
                    - scheduleStartDate
                    type: object
                  maxItems: 1
                  type: array
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                status:
                  type: string
                transferSpec:
                  items:
                    properties:
                      awsS3DataSource:
                        items:
                          properties:
                            awsAccessKey:
                              items:
                                type: object
                              maxItems: 1
                              type: array
                            bucketName:
                              type: string
                          required:
                          - awsAccessKey
                          - bucketName
                          type: object
                        maxItems: 1
                        type: array
                      gcsDataSink:
                        items:
                          properties:
                            bucketName:
                              type: string
                          required:
                          - bucketName
                          type: object
                        maxItems: 1
                        type: array
                      gcsDataSource:
                        items:
                          properties:
                            bucketName:
                              type: string
                          required:
                          - bucketName
                          type: object
                        maxItems: 1
                        type: array
                      httpDataSource:
                        items:
                          properties:
                            listURL:
                              type: string
                          required:
                          - listURL
                          type: object
                        maxItems: 1
                        type: array
                      objectConditions:
                        items:
                          properties:
                            excludePrefixes:
                              items:
                                type: string
                              type: array
                            includePrefixes:
                              items:
                                type: string
                              type: array
                            maxTimeElapsedSinceLastModification:
                              type: string
                            minTimeElapsedSinceLastModification:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      transferOptions:
                        items:
                          properties:
                            deleteObjectsFromSourceAfterTransfer:
                              type: boolean
                            deleteObjectsUniqueInSink:
                              type: boolean
                            overwriteObjectsAlreadyExistingInSink:
                              type: boolean
                          type: object
                        maxItems: 1
                        type: array
                    type: object
                  maxItems: 1
                  type: array
              required:
              - description
              - providerRef
              - schedule
              - transferSpec
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
