apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: bigquerydatasets.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: BigqueryDataset
    listKind: BigqueryDatasetList
    plural: bigquerydatasets
    singular: bigquerydataset
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            access:
              items:
                properties:
                  domain:
                    type: string
                  groupByEmail:
                    type: string
                  role:
                    type: string
                  specialGroup:
                    type: string
                  userByEmail:
                    type: string
                  view:
                    items:
                      properties:
                        datasetID:
                          type: string
                        projectID:
                          type: string
                        tableID:
                          type: string
                      required:
                      - datasetID
                      - projectID
                      - tableID
                      type: object
                    maxItems: 1
                    type: array
                type: object
              type: array
            creationTime:
              format: int64
              type: integer
            datasetID:
              type: string
            defaultEncryptionConfiguration:
              items:
                properties:
                  kmsKeyName:
                    type: string
                required:
                - kmsKeyName
                type: object
              maxItems: 1
              type: array
            defaultPartitionExpirationMs:
              format: int64
              type: integer
            defaultTableExpirationMs:
              format: int64
              type: integer
            deleteContentsOnDestroy:
              type: boolean
            description:
              type: string
            etag:
              type: string
            friendlyName:
              type: string
            id:
              type: string
            labels:
              additionalProperties:
                type: string
              type: object
            lastModifiedTime:
              format: int64
              type: integer
            location:
              type: string
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            selfLink:
              type: string
          required:
          - datasetID
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                access:
                  items:
                    properties:
                      domain:
                        type: string
                      groupByEmail:
                        type: string
                      role:
                        type: string
                      specialGroup:
                        type: string
                      userByEmail:
                        type: string
                      view:
                        items:
                          properties:
                            datasetID:
                              type: string
                            projectID:
                              type: string
                            tableID:
                              type: string
                          required:
                          - datasetID
                          - projectID
                          - tableID
                          type: object
                        maxItems: 1
                        type: array
                    type: object
                  type: array
                creationTime:
                  format: int64
                  type: integer
                datasetID:
                  type: string
                defaultEncryptionConfiguration:
                  items:
                    properties:
                      kmsKeyName:
                        type: string
                    required:
                    - kmsKeyName
                    type: object
                  maxItems: 1
                  type: array
                defaultPartitionExpirationMs:
                  format: int64
                  type: integer
                defaultTableExpirationMs:
                  format: int64
                  type: integer
                deleteContentsOnDestroy:
                  type: boolean
                description:
                  type: string
                etag:
                  type: string
                friendlyName:
                  type: string
                id:
                  type: string
                labels:
                  additionalProperties:
                    type: string
                  type: object
                lastModifiedTime:
                  format: int64
                  type: integer
                location:
                  type: string
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                selfLink:
                  type: string
              required:
              - datasetID
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
