apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: computeinstancetemplates.google.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: google.kubeform.com
  names:
    kind: ComputeInstanceTemplate
    listKind: ComputeInstanceTemplateList
    plural: computeinstancetemplates
    singular: computeinstancetemplate
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            canIPForward:
              type: boolean
            description:
              type: string
            disk:
              items:
                properties:
                  autoDelete:
                    type: boolean
                  boot:
                    type: boolean
                  deviceName:
                    type: string
                  diskEncryptionKey:
                    items:
                      properties:
                        kmsKeySelfLink:
                          type: string
                      type: object
                    maxItems: 1
                    type: array
                  diskName:
                    type: string
                  diskSizeGb:
                    format: int64
                    type: integer
                  diskType:
                    type: string
                  interface:
                    type: string
                  labels:
                    additionalProperties:
                      type: string
                    type: object
                  mode:
                    type: string
                  source:
                    type: string
                  sourceImage:
                    type: string
                  type:
                    type: string
                type: object
              type: array
            guestAccelerator:
              items:
                properties:
                  count:
                    format: int64
                    type: integer
                  type:
                    type: string
                required:
                - count
                - type
                type: object
              type: array
            id:
              type: string
            instanceDescription:
              type: string
            labels:
              additionalProperties:
                type: string
              type: object
            machineType:
              type: string
            metadata:
              additionalProperties:
                type: string
              type: object
            metadataFingerprint:
              type: string
            metadataStartupScript:
              type: string
            minCPUPlatform:
              type: string
            name:
              type: string
            namePrefix:
              type: string
            networkInterface:
              items:
                properties:
                  accessConfig:
                    items:
                      properties:
                        natIP:
                          type: string
                        networkTier:
                          type: string
                      type: object
                    type: array
                  aliasIPRange:
                    items:
                      properties:
                        ipCIDRRange:
                          type: string
                        subnetworkRangeName:
                          type: string
                      required:
                      - ipCIDRRange
                      type: object
                    type: array
                  network:
                    type: string
                  networkIP:
                    type: string
                  subnetwork:
                    type: string
                  subnetworkProject:
                    type: string
                type: object
              type: array
            project:
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              type: string
            remoteBackend:
              description: Backend specifies the configuration of the terraform backend
              properties:
                ref:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                type:
                  type: string
              type: object
            scheduling:
              items:
                properties:
                  automaticRestart:
                    type: boolean
                  nodeAffinities:
                    items:
                      properties:
                        key:
                          type: string
                        operator:
                          type: string
                        values:
                          items:
                            type: string
                          type: array
                      required:
                      - key
                      - operator
                      - values
                      type: object
                    type: array
                  onHostMaintenance:
                    type: string
                  preemptible:
                    type: boolean
                type: object
              maxItems: 1
              type: array
            selfLink:
              type: string
            serviceAccount:
              items:
                properties:
                  email:
                    type: string
                  scopes:
                    items:
                      type: string
                    type: array
                required:
                - scopes
                type: object
              maxItems: 1
              type: array
            shieldedInstanceConfig:
              items:
                properties:
                  enableIntegrityMonitoring:
                    type: boolean
                  enableSecureBoot:
                    type: boolean
                  enableVtpm:
                    type: boolean
                type: object
              maxItems: 1
              type: array
            tags:
              items:
                type: string
              type: array
            tagsFingerprint:
              type: string
          required:
          - disk
          - machineType
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                canIPForward:
                  type: boolean
                description:
                  type: string
                disk:
                  items:
                    properties:
                      autoDelete:
                        type: boolean
                      boot:
                        type: boolean
                      deviceName:
                        type: string
                      diskEncryptionKey:
                        items:
                          properties:
                            kmsKeySelfLink:
                              type: string
                          type: object
                        maxItems: 1
                        type: array
                      diskName:
                        type: string
                      diskSizeGb:
                        format: int64
                        type: integer
                      diskType:
                        type: string
                      interface:
                        type: string
                      labels:
                        additionalProperties:
                          type: string
                        type: object
                      mode:
                        type: string
                      source:
                        type: string
                      sourceImage:
                        type: string
                      type:
                        type: string
                    type: object
                  type: array
                guestAccelerator:
                  items:
                    properties:
                      count:
                        format: int64
                        type: integer
                      type:
                        type: string
                    required:
                    - count
                    - type
                    type: object
                  type: array
                id:
                  type: string
                instanceDescription:
                  type: string
                labels:
                  additionalProperties:
                    type: string
                  type: object
                machineType:
                  type: string
                metadata:
                  additionalProperties:
                    type: string
                  type: object
                metadataFingerprint:
                  type: string
                metadataStartupScript:
                  type: string
                minCPUPlatform:
                  type: string
                name:
                  type: string
                namePrefix:
                  type: string
                networkInterface:
                  items:
                    properties:
                      accessConfig:
                        items:
                          properties:
                            natIP:
                              type: string
                            networkTier:
                              type: string
                          type: object
                        type: array
                      aliasIPRange:
                        items:
                          properties:
                            ipCIDRRange:
                              type: string
                            subnetworkRangeName:
                              type: string
                          required:
                          - ipCIDRRange
                          type: object
                        type: array
                      network:
                        type: string
                      networkIP:
                        type: string
                      subnetwork:
                        type: string
                      subnetworkProject:
                        type: string
                    type: object
                  type: array
                project:
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                region:
                  type: string
                remoteBackend:
                  description: Backend specifies the configuration of the terraform
                    backend
                  properties:
                    ref:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    type:
                      type: string
                  type: object
                scheduling:
                  items:
                    properties:
                      automaticRestart:
                        type: boolean
                      nodeAffinities:
                        items:
                          properties:
                            key:
                              type: string
                            operator:
                              type: string
                            values:
                              items:
                                type: string
                              type: array
                          required:
                          - key
                          - operator
                          - values
                          type: object
                        type: array
                      onHostMaintenance:
                        type: string
                      preemptible:
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
                selfLink:
                  type: string
                serviceAccount:
                  items:
                    properties:
                      email:
                        type: string
                      scopes:
                        items:
                          type: string
                        type: array
                    required:
                    - scopes
                    type: object
                  maxItems: 1
                  type: array
                shieldedInstanceConfig:
                  items:
                    properties:
                      enableIntegrityMonitoring:
                        type: boolean
                      enableSecureBoot:
                        type: boolean
                      enableVtpm:
                        type: boolean
                    type: object
                  maxItems: 1
                  type: array
                tags:
                  items:
                    type: string
                  type: array
                tagsFingerprint:
                  type: string
              required:
              - disk
              - machineType
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
