apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: nodebalancernodes.linode.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: linode.kubeform.com
  names:
    kind: NodebalancerNode
    listKind: NodebalancerNodeList
    plural: nodebalancernodes
    singular: nodebalancernode
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            address:
              description: The private IP Address and port (IP:PORT) where this backend
                can be reached. This must be a private IP address.
              type: string
            configID:
              description: The ID of the NodeBalancerConfig to access.
              format: int64
              type: integer
            id:
              type: string
            label:
              description: The label for this node. This is for display purposes only.
              type: string
            mode:
              description: The mode this NodeBalancer should use when sending traffic
                to this backend. If set to `accept` this backend is accepting traffic.
                If set to `reject` this backend will not receive traffic. If set to
                `drain` this backend will not receive new traffic, but connections
                already pinned to it will continue to be routed to it. If set to `backup`
                this backend will only accept traffic if all other nodes are down.
              type: string
            nodebalancerID:
              description: The ID of the NodeBalancer to access.
              format: int64
              type: integer
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            status:
              description: The current status of this node, based on the configured
                checks of its NodeBalancer Config. (unknown, UP, DOWN)
              type: string
            weight:
              description: Used when picking a backend to serve a request and is not
                pinned to a single backend yet. Nodes with a higher weight will receive
                more traffic. (1-255)
              format: int64
              type: integer
          required:
          - address
          - configID
          - label
          - nodebalancerID
          - providerRef
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                address:
                  description: The private IP Address and port (IP:PORT) where this
                    backend can be reached. This must be a private IP address.
                  type: string
                configID:
                  description: The ID of the NodeBalancerConfig to access.
                  format: int64
                  type: integer
                id:
                  type: string
                label:
                  description: The label for this node. This is for display purposes
                    only.
                  type: string
                mode:
                  description: The mode this NodeBalancer should use when sending
                    traffic to this backend. If set to `accept` this backend is accepting
                    traffic. If set to `reject` this backend will not receive traffic.
                    If set to `drain` this backend will not receive new traffic, but
                    connections already pinned to it will continue to be routed to
                    it. If set to `backup` this backend will only accept traffic if
                    all other nodes are down.
                  type: string
                nodebalancerID:
                  description: The ID of the NodeBalancer to access.
                  format: int64
                  type: integer
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                status:
                  description: The current status of this node, based on the configured
                    checks of its NodeBalancer Config. (unknown, UP, DOWN)
                  type: string
                weight:
                  description: Used when picking a backend to serve a request and
                    is not pinned to a single backend yet. Nodes with a higher weight
                    will receive more traffic. (1-255)
                  format: int64
                  type: integer
              required:
              - address
              - configID
              - label
              - nodebalancerID
              - providerRef
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
