apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: lkeclusters.linode.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: linode.kubeform.com
  names:
    kind: LkeCluster
    listKind: LkeClusterList
    plural: lkeclusters
    singular: lkecluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            apiEndpoints:
              description: The API endpoints for the cluster.
              items:
                type: string
              type: array
            id:
              type: string
            k8sVersion:
              description: The desired Kubernetes version for this Kubernetes cluster
                in the format of <major>.<minor>. The latest supported patch version
                will be deployed.
              type: string
            label:
              description: The unique label for the cluster.
              type: string
            pool:
              description: A node pool in the cluster.
              items:
                properties:
                  ID:
                    description: The ID of the Node Pool.
                    format: int64
                    type: integer
                  count:
                    description: The number of nodes in the Node Pool.
                    format: int64
                    type: integer
                  nodes:
                    description: The nodes in the node pool.
                    items:
                      properties:
                        ID:
                          description: The ID of the node.
                          type: string
                        instanceID:
                          description: The ID of the underlying Linode instance.
                          format: int64
                          type: integer
                        status:
                          description: The status of the node.
                          type: string
                      type: object
                    type: array
                  type:
                    description: A Linode Type for all of the nodes in the Node Pool.
                    type: string
                required:
                - count
                - type
                type: object
              minItems: 1
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            region:
              description: This cluster's location.
              type: string
            secretRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            status:
              description: The status of the cluster.
              type: string
            tags:
              description: An array of tags applied to this object. Tags are for organizational
                purposes only.
              items:
                type: string
              type: array
          required:
          - k8sVersion
          - label
          - pool
          - providerRef
          - region
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                apiEndpoints:
                  description: The API endpoints for the cluster.
                  items:
                    type: string
                  type: array
                id:
                  type: string
                k8sVersion:
                  description: The desired Kubernetes version for this Kubernetes
                    cluster in the format of <major>.<minor>. The latest supported
                    patch version will be deployed.
                  type: string
                label:
                  description: The unique label for the cluster.
                  type: string
                pool:
                  description: A node pool in the cluster.
                  items:
                    properties:
                      ID:
                        description: The ID of the Node Pool.
                        format: int64
                        type: integer
                      count:
                        description: The number of nodes in the Node Pool.
                        format: int64
                        type: integer
                      nodes:
                        description: The nodes in the node pool.
                        items:
                          properties:
                            ID:
                              description: The ID of the node.
                              type: string
                            instanceID:
                              description: The ID of the underlying Linode instance.
                              format: int64
                              type: integer
                            status:
                              description: The status of the node.
                              type: string
                          type: object
                        type: array
                      type:
                        description: A Linode Type for all of the nodes in the Node
                          Pool.
                        type: string
                    required:
                    - count
                    - type
                    type: object
                  minItems: 1
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                region:
                  description: This cluster's location.
                  type: string
                secretRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                status:
                  description: The status of the cluster.
                  type: string
                tags:
                  description: An array of tags applied to this object. Tags are for
                    organizational purposes only.
                  items:
                    type: string
                  type: array
              required:
              - k8sVersion
              - label
              - pool
              - providerRef
              - region
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
