apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: domains.linode.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: linode.kubeform.com
  names:
    kind: Domain
    listKind: DomainList
    plural: domains
    singular: domain
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            axfrIPS:
              description: The list of IPs that may perform a zone transfer for this
                Domain. This is potentially dangerous, and should be set to an empty
                list unless you intend to use it.
              items:
                type: string
              type: array
            description:
              description: A description for this Domain. This is for display purposes
                only.
              type: string
            domain:
              description: The domain this Domain represents. These must be unique
                in our system; you cannot have two Domains representing the same domain.
              type: string
            expireSec:
              description: The amount of time in seconds that may pass before this
                Domain is no longer authoritative. Valid values are 0, 00, 3600, 7200,
                14400, 28800, 57600, 86400, 172800, 345600, 604800, 1209600, and 2419200
                - any other value will be rounded to the nearest valid value.
              format: int64
              type: integer
            group:
              description: The group this Domain belongs to. This is for display purposes
                only.
              type: string
            id:
              type: string
            masterIPS:
              description: The IP addresses representing the master DNS for this Domain.
              items:
                type: string
              type: array
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            refreshSec:
              description: The amount of time in seconds before this Domain should
                be refreshed. Valid values are 0, 300, 3600, 7200, 14400, 28800, 57600,
                86400, 172800, 345600, 604800, 1209600, and 2419200 - any other value
                will be rounded to the nearest valid value.
              format: int64
              type: integer
            retrySec:
              description: The interval, in seconds, at which a failed refresh should
                be retried. Valid values are 0, 300, 3600, 7200, 14400, 28800, 57600,
                86400, 172800, 345600, 604800, 1209600, and 2419200 - any other value
                will be rounded to the nearest valid value.
              format: int64
              type: integer
            soaEmail:
              description: Start of Authority email address. This is required for
                master Domains.
              type: string
            status:
              description: Used to control whether this Domain is currently being
                rendered.
              type: string
            tags:
              description: An array of tags applied to this object. Tags are for organizational
                purposes only.
              items:
                type: string
              type: array
            ttlSec:
              description: '''Time to Live'' - the amount of time in seconds that
                this Domain''s records may be cached by resolvers or other domain
                servers. Valid values are 0, 300, 3600, 7200, 14400, 28800, 57600,
                86400, 172800, 345600, 604800, 1209600, and 2419200 - any other value
                will be rounded to the nearest valid value.'
              format: int64
              type: integer
            type:
              description: If this Domain represents the authoritative source of information
                for the domain it describes, or if it is a read-only copy of a master
                (also called a slave).
              type: string
          required:
          - domain
          - providerRef
          - type
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                axfrIPS:
                  description: The list of IPs that may perform a zone transfer for
                    this Domain. This is potentially dangerous, and should be set
                    to an empty list unless you intend to use it.
                  items:
                    type: string
                  type: array
                description:
                  description: A description for this Domain. This is for display
                    purposes only.
                  type: string
                domain:
                  description: The domain this Domain represents. These must be unique
                    in our system; you cannot have two Domains representing the same
                    domain.
                  type: string
                expireSec:
                  description: The amount of time in seconds that may pass before
                    this Domain is no longer authoritative. Valid values are 0, 00,
                    3600, 7200, 14400, 28800, 57600, 86400, 172800, 345600, 604800,
                    1209600, and 2419200 - any other value will be rounded to the
                    nearest valid value.
                  format: int64
                  type: integer
                group:
                  description: The group this Domain belongs to. This is for display
                    purposes only.
                  type: string
                id:
                  type: string
                masterIPS:
                  description: The IP addresses representing the master DNS for this
                    Domain.
                  items:
                    type: string
                  type: array
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                refreshSec:
                  description: The amount of time in seconds before this Domain should
                    be refreshed. Valid values are 0, 300, 3600, 7200, 14400, 28800,
                    57600, 86400, 172800, 345600, 604800, 1209600, and 2419200 - any
                    other value will be rounded to the nearest valid value.
                  format: int64
                  type: integer
                retrySec:
                  description: The interval, in seconds, at which a failed refresh
                    should be retried. Valid values are 0, 300, 3600, 7200, 14400,
                    28800, 57600, 86400, 172800, 345600, 604800, 1209600, and 2419200
                    - any other value will be rounded to the nearest valid value.
                  format: int64
                  type: integer
                soaEmail:
                  description: Start of Authority email address. This is required
                    for master Domains.
                  type: string
                status:
                  description: Used to control whether this Domain is currently being
                    rendered.
                  type: string
                tags:
                  description: An array of tags applied to this object. Tags are for
                    organizational purposes only.
                  items:
                    type: string
                  type: array
                ttlSec:
                  description: '''Time to Live'' - the amount of time in seconds that
                    this Domain''s records may be cached by resolvers or other domain
                    servers. Valid values are 0, 300, 3600, 7200, 14400, 28800, 57600,
                    86400, 172800, 345600, 604800, 1209600, and 2419200 - any other
                    value will be rounded to the nearest valid value.'
                  format: int64
                  type: integer
                type:
                  description: If this Domain represents the authoritative source
                    of information for the domain it describes, or if it is a read-only
                    copy of a master (also called a slave).
                  type: string
              required:
              - domain
              - providerRef
              - type
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
