apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubeform
  name: stackscripts.linode.kubeform.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: linode.kubeform.com
  names:
    kind: Stackscript
    listKind: StackscriptList
    plural: stackscripts
    singular: stackscript
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            created:
              description: The date this StackScript was created.
              type: string
            deploymentsActive:
              description: Count of currently active, deployed Linodes created from
                this StackScript.
              format: int64
              type: integer
            deploymentsTotal:
              description: The total number of times this StackScript has been deployed.
              format: int64
              type: integer
            description:
              description: A description for the StackScript.
              type: string
            id:
              type: string
            images:
              description: An array of Image IDs representing the Images that this
                StackScript is compatible for deploying with.
              items:
                type: string
              type: array
            isPublic:
              description: This determines whether other users can use your StackScript.
                Once a StackScript is made public, it cannot be made private.
              type: boolean
            label:
              description: The StackScript's label is for display purposes only.
              type: string
            providerRef:
              description: LocalObjectReference contains enough information to let
                you locate the referenced object inside the same namespace.
              properties:
                name:
                  description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                    TODO: Add other useful fields. apiVersion, kind, uid?'
                  type: string
              type: object
            remoteBackend:
              description: Backend specifies the configuration of the terraform backend
              properties:
                ref:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                type:
                  type: string
              type: object
            revNote:
              description: This field allows you to add notes for the set of revisions
                made to this StackScript.
              type: string
            script:
              description: The script to execute when provisioning a new Linode with
                this StackScript.
              type: string
            updated:
              description: The date this StackScript was updated.
              type: string
            userDefinedFields:
              description: This is a list of fields defined with a special syntax
                inside this StackScript that allow for supplying customized parameters
                during deployment.
              items:
                properties:
                  default:
                    type: string
                  example:
                    type: string
                  label:
                    type: string
                  manyOf:
                    type: string
                  name:
                    type: string
                  oneOf:
                    type: string
                type: object
              type: array
            userGravatarID:
              description: The Gravatar ID for the User who created the StackScript.
              type: string
            username:
              description: The User who created the StackScript.
              type: string
          required:
          - description
          - images
          - label
          - providerRef
          - script
          type: object
        status:
          properties:
            observedGeneration:
              description: Resource generation, which is updated on mutation by the
                API Server.
              format: int64
              type: integer
            output:
              properties:
                created:
                  description: The date this StackScript was created.
                  type: string
                deploymentsActive:
                  description: Count of currently active, deployed Linodes created
                    from this StackScript.
                  format: int64
                  type: integer
                deploymentsTotal:
                  description: The total number of times this StackScript has been
                    deployed.
                  format: int64
                  type: integer
                description:
                  description: A description for the StackScript.
                  type: string
                id:
                  type: string
                images:
                  description: An array of Image IDs representing the Images that
                    this StackScript is compatible for deploying with.
                  items:
                    type: string
                  type: array
                isPublic:
                  description: This determines whether other users can use your StackScript.
                    Once a StackScript is made public, it cannot be made private.
                  type: boolean
                label:
                  description: The StackScript's label is for display purposes only.
                  type: string
                providerRef:
                  description: LocalObjectReference contains enough information to
                    let you locate the referenced object inside the same namespace.
                  properties:
                    name:
                      description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        TODO: Add other useful fields. apiVersion, kind, uid?'
                      type: string
                  type: object
                remoteBackend:
                  description: Backend specifies the configuration of the terraform
                    backend
                  properties:
                    ref:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    type:
                      type: string
                  type: object
                revNote:
                  description: This field allows you to add notes for the set of revisions
                    made to this StackScript.
                  type: string
                script:
                  description: The script to execute when provisioning a new Linode
                    with this StackScript.
                  type: string
                updated:
                  description: The date this StackScript was updated.
                  type: string
                userDefinedFields:
                  description: This is a list of fields defined with a special syntax
                    inside this StackScript that allow for supplying customized parameters
                    during deployment.
                  items:
                    properties:
                      default:
                        type: string
                      example:
                        type: string
                      label:
                        type: string
                      manyOf:
                        type: string
                      name:
                        type: string
                      oneOf:
                        type: string
                    type: object
                  type: array
                userGravatarID:
                  description: The Gravatar ID for the User who created the StackScript.
                  type: string
                username:
                  description: The User who created the StackScript.
                  type: string
              required:
              - description
              - images
              - label
              - providerRef
              - script
              type: object
            phase:
              type: string
            state:
              properties:
                lineage:
                  type: string
                serial:
                  format: int64
                  type: integer
                terraform_version:
                  type: string
                version:
                  format: int64
                  type: integer
              required:
              - lineage
              - serial
              - terraform_version
              - version
              type: object
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
